["Land_Pod_Heli_Transport_04_covered_F", ["Black",1]],
["I_Truck_02_MRL_F", ["Opfor", 1, "Indep",0]],
["O_Heli_Transport_04_bench_F", ["Black", 0.3, "Opfor", 0.7]],
["O_Heli_Transport_04_covered_F", ["Black", 0.3, "Opfor", 0.7]],
["O_Heli_Attack_02_dynamicLoadout_F", ["Black", 0.3, "Opfor", 0.7]],
["O_LSV_02_armed_F", ["Black", 0.3, "Arid",0.7]],
["O_LSV_02_unarmed_F", ["Black", 0.3, "Arid",0.7]],
["O_LSV_02_AT_F", ["Black", 0.3, "Arid",0.7]],
["a3a_Offroad_02_LMG_black_F", ["Black", 0.4, "Brown", 0.6]],
["I_C_Offroad_02_unarmed_F", ["Black", 0.4, "Brown", 0.6]],
["O_MBT_02_railgun_F", ["Grey", 0.4, "Hex", 0.6]],
["O_MBT_04_command_F", ["Grey", 0.4, "Hex", 0.6]],
["O_MBT_04_cannon_F", ["Grey", 0.4, "Hex", 0.6]],
["O_MBT_02_cannon_F", ["Grey", 0.4, "Hex", 0.6]],
["O_Heli_Light_02_unarmed_F", ["Opfor",0.6, "Black", 0.2 , "Blackcustom", 0.2]],
["O_Heli_Light_02_dynamicLoadout_F", ["Opfor",0.6, "Black", 0.2 , "Blackcustom", 0.2]],
["O_T_VTOL_02_infantry_dynamicLoadout_F", ["Hex", 1]]