_staticMG append ["SPE_ST_MG34_Lafette_Deployed","SPE_ST_MG42_Lafette_Deployed","SPE_GER_SearchLight","SPE_FR_M1919A6_Bipod","SPE_FR_M1919_M2_Trench_Deployed"];
_staticAT append ["SPE_ST_FlaK_36","SPE_ST_Pak40","SPE_ST_leFH18_AT","SPE_FR_57mm_M1"];
_staticAA append ["SPE_ST_FlaK_36_AA","SPE_ST_FlaK_38"];
_CivTruck append ["SPE_FFI_OpelBlitz_noinsignia","SPE_FFI_OpelBlitz_Open_noinsignia"];
_VehTruck append ["SPE_FR_M3_Halftrack_Unarmed_Open_noinsignia","SPE_FR_M3_Halftrack_Unarmed_noinsignia","SPE_FR_M3_Halftrack_noinsignia","SPE_CCKW_353_noinsignia","SPE_CCKW_353_Open_noinsignia","SPE_CCKW_353_M2_noinsignia"];
_vehiclesCivCar append ["SPE_Milice_R200_Unarmed_noinsignia", "SPE_Milice_R200_Hood_noinsignia"]; 
_vehiclesLightUnarmed append ["SPE_US_G503_MB_noinsignia","SPE_US_G503_MB_Open_noinsignia"]; 
_vehiclesLightArmed append ["SPE_Milice_R200_MG34_noinsignia","SPE_US_G503_MB_M1919_Armoured_noinsignia","SPE_US_G503_MB_M1919_noinsignia","SPE_US_G503_MB_M2_Armoured_noinsignia","SPE_US_G503_MB_M2_noinsignia","SPE_US_G503_MB_M2_PATROL_noinsignia","SPE_US_G503_MB_M1919_PATROL_noinsignia"]; 
//_vehiclesBasic append [];
//_vehiclesAt append [];
_vehicleAA append ["SPE_FR_M16_Halftrack_noinsignia","SPE_OpelBlitz_Flak38_noinsignia"];