["CSLA_PLdvK59V3S_noinsignia",["CSLAd",1]],
["CSLA_BVP1_noinsignia",["CSLAd",1]],
["CSLA_BPzV_noinsignia",["CSLAd",1]],
["CSLA_DTP90_noinsignia",["CSLAd",1]],
["CSLA_MU90_noinsignia",["CSLAd",1]],
["CSLA_OT62_noinsignia",["CSLAd",1]],
["CSLA_OT64C_noinsignia",["CSLAd",1]],
["CSLA_OT65A_noinsignia",["CSLAd",1]],
["CSLA_OZV90_noinsignia",["CSLAd",1]],
["CSLA_RM51_noinsignia",["CSLAd",1]],
["CSLA_RM70_noinsignia",["CSLAd",1]],
["CSLA_ShKH77_noinsignia",["CSLAd",1]],
["CSLA_AZU_noinsignia",["CSLAd",1]],
["CSLA_AZU_para_noinsignia",["CSLAd",1]],
["CSLA_AZU_R2_noinsignia",["CSLAd",1]],
["CSLA_F813o_noinsignia",["CSLAd",1]],
["CSLA_F813_noinsignia",["CSLAd",1]],
["CSLA_V3SLizard_noinsignia",["CSLAd",1]],

["CSLA_V3Sa_noinsignia",["CSLAd",1]],
["CSLA_V3Sf_noinsignia",["CSLAd",1]],
["CSLA_V3So_noinsignia",["CSLAd",1]],
["CSLA_V3S_noinsignia",["CSLAd",1]],
["CSLA_V3Sr_noinsignia",["CSLAd",1]],

["CSLA_Mi17_noinsignia",["desert",1]],
["CSLA_Mi17mg_noinsignia",["desert",1]],
["CSLA_Mi17pylons_noinsignia",["desert",1]],

["CSLA_Mi24V_noinsignia",["camo3",1]],

["CSLA_T72_noinsignia",["CSLAd",1]],
["CSLA_T72M_noinsignia",["CSLAd",1]],
["CSLA_T72M1_noinsignia",["CSLAd",1]],

["FIA_BTR40_noinsignia",["FIAd",1]],
["FIA_BTR40_DSKM_noinsignia",["FIAd",1]]
