_basic append ["SPE_ST_R200_Unarmed"];
_unarmedVehicles append ["SPE_GER_R200_Hood","SPE_ST_R200_Hood","SPE_GER_R200_Unarmed"];
_armedVehicles append ["SPE_GER_R200_MG34", "SPE_ST_OpelBlitz_Flak38"];
_Trucks append ["SPE_ST_OpelBlitz_Open", "SPE_ST_OpelBlitz"];
_cargoTrucks append ["SPE_ST_OpelBlitz_Open"];
_ammoTrucks append ["SPE_ST_OpelBlitz_Ammo"];
_repairTrucks append ["SPE_ST_OpelBlitz_Repair"];
_fuelTrucks append ["SPE_ST_OpelBlitz_Fuel"];
_medicalTrucks append ["SPE_ST_OpelBlitz_Ambulance"];
_lightAPCs append ["SPE_SdKfz250_1","SPE_ST_SdKfz250_1"];
_APCs append ["SPE_PzKpfwIII_J","SPE_PzKpfwIII_N", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"];
_IFVs append ["SPE_PzKpfwIII_N", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L", "SPE_StuG_III_G_Early", "SPE_StuG_III_G_Late", "SPE_StuG_III_G_SKB", 
"SPE_StuH_42","SPE_ST_StuG_III_G_Early","SPE_ST_StuG_III_G_Late","SPE_ST_StuG_III_G_SKB","SPE_ST_StuH_42","SPE_ST_StuG_III_G_Early_DLV","SPE_ST_StuG_III_G_Late_DLV",
"SPE_ST_StuG_III_G_SKB_DLV","SPE_ST_StuH_42_DLV","SPE_StuG_III_G_Early_DLV","SPE_StuG_III_G_Late_DLV","SPE_StuG_III_G_SKB_DLV","SPE_StuH_42_DLV"];
_airborneVehicles append ["SPE_SdKfz250_1"];
_tanks append ["SPE_PzKpfwVI_H1", "SPE_PzKpfwV_G", "SPE_PzKpfwIV_G", "SPE_Jagdpanther_G1","SPE_ST_PzKpfwIV_G","SPE_ST_PzKpfwV_G","SPE_ST_PzKpfwVI_H1",
"SPE_ST_Jagdpanther_G1","SPE_ST_PzKpfwV_G_DLV","SPE_ST_PzKpfwVI_H1_DLV","SPE_ST_Jagdpanther_G1_DLV","SPE_PzKpfwV_G_DLV","SPE_PzKpfwVI_H1_DLV","SPE_Jagdpanther_G1_DLV"];
_lightTanks append ["SPE_PzKpfwIII_J","SPE_PzKpfwIII_N", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L","SPE_ST_PzKpfwIII_J","SPE_ST_PzKpfwIII_L","SPE_ST_PzKpfwIII_M",
"SPE_ST_PzKpfwIII_N","SPE_ST_PzKpfwIII_J_DLV","SPE_ST_PzKpfwIII_L_DLV","SPE_ST_PzBefWgIII_K_DLV","SPE_ST_PzKpfwIII_N_DLV","SPE_ST_PzKpfwIV_G_DLV","SPE_Nashorn",
"SPE_PzKpfwIII_J_DLV","SPE_PzKpfwIII_L_DLV","SPE_PzKpfwIII_M_DLV","SPE_PzBefWgIII_K_DLV","SPE_PzKpfwIII_N_DLV","SPE_PzKpfwIV_G_DLV","SPE_Nashorn_DLV"];
_aa append ["SPE_ST_OpelBlitz_Flak38"];

_transportBoat append ["I_G_Boat_Transport_01_F"];
_gunBoat append ["I_G_Boat_Transport_01_F"];

_planesCAS append ["SPE_FW190F8"];
_planesAA append ["SPE_FW190F8"];

if (isClass (configFile >> "CfgPatches" >> "WW2_SPEX_Assets_m_Vehicles_Planes_m")) then {
    _planesTransport append ["SPEX_C47_Skytrain"];
};

_artillery append ["SPE_leFH18"];

_militiaLightArmed append ["SPE_ST_R200_MG34"];
_militiaTrucks append ["SPE_OpelBlitz"];
_militiaCars append ["SPE_ST_R200_Unarmed"];
_militiaAPCs append ["SPE_SdKfz250_1","SPE_ST_SdKfz250_1"]; 

_policeVehs append ["SPE_ST_GER_R200_Hood","SPE_Milice_R200_Unarmed","SPE_Milice_R200_Hood","SPE_Milice_R200_MG34"];

_staticMG append ["SPE_MG42_Lafette_trench_Deployed", "SPE_MG34_Lafette_Trench_Deployed","SPE_FM24_M24_Bipod",
"SPE_ST_MG34_Lafette_Deployed","SPE_ST_MG34_Lafette_Trench_Deployed","SPE_ST_MG42_Lafette_Deployed","SPE_ST_MG42_Lafette_trench_Deployed","SPE_GER_SearchLight"];
_staticAT append ["SPE_leFH18_AT", "SPE_Pak40","SPE_ST_leFH18_AT","SPE_ST_FlaK_36","SPE_ST_Pak40","SPE_FlaK_36"];
_staticAA append ["SPE_FlaK_30", "SPE_FlaK_38","SPE_ST_FlaK_38"];
_staticMortars append ["SPE_GrW278_1","SPE_ST_GrW278_1"];
_howitzers append ["SPE_leFH18","SPE_ST_leFH18"];

_radar append ["SPE_FlaK_36_AA"];
_SAM append ["SPE_FlaK_36_AA"];

_mortarMagazineHE append ["SPE_8Rnd_81mm_FA_Mle_1932_HE"];
_mortarMagazineSmoke append ["SPE_8Rnd_81mm_FA_Mle_1932_Smoke"];

_minefieldAT append ["SPE_TMI_42_MINE"];
_minefieldAPERS append ["SPE_SMI_35_Pressure_MINE", "SPE_SMI_35_MINE"];

_howitzerMagazineHE append ["SPE_20x_Shell_105L28_Gr38_HE"];

_baseClassSquadLeaderArray append ["SPE_Milice_FG_Lieutenant","SPE_Milice_FG_SquadLead","SPE_Milice_FG_TeamLeader","SPE_Milice_FG_NP_Lieutenant",
"SPE_Milice_FG_NP_SquadLead","SPE_Milice_FG_NP_TeamLeader","SPE_sturmtrooper_Assist_SquadLead","SPE_sturmtrooper_SquadLead","SPE_ST_AT_Soldier_SquadLead",
"SPE_GER_Assist_SquadLead","SPE_GER_SquadLead","SPE_GER_AT_Soldier_SquadLead","SPE_OST_CSK_Assist_SquadLead","SPE_GER_gun_SquadLead","SPE_OST_CSK_lieutenant",
"SPE_OST_CSK_SquadLead","SPE_FSJ_Assist_SquadLead","SPE_FSJ_Lieutenant","SPE_FSJ_SquadLead","SPE_FSJ_AT_Soldier_SquadLead","SPE_GER_flak_gun_SquadLead",
"SPE_OST_Assist_SquadLead","SPE_OST_SquadLead","SPE_GER_lehr_Assist_SquadLead","SPE_GER_lehr_SquadLead","SPE_GER_scout_Assist_SquadLead","SPE_GER_scout_lieutenant","SPE_GER_scout_SquadLead"];
_baseClassRiflemanArray append ["SPE_Milice_FG_Assist_Autorifleman","SPE_Milice_FG_Rifleman","SPE_Milice_FG_Sentry","SPE_Milice_FG_Sentry_Sten",
"SPE_Milice_FG_NP_Assist_Autorifleman","SPE_Milice_FG_NP_Rifleman","SPE_Milice_FG_NP_Sentry","SPE_Milice_FG_NP_Sentry_Sten","SPE_ST_Driver",
"SPE_ST_Driver_Lite","SPE_sturmtrooper_Flamethrower_Operator","SPE_ST_Halftrack_Driver","SPE_sturmtrooper_rifleman","SPE_sturmtrooper_rifleman_lite",
"SPE_sturmtrooper_ober_rifleman","SPE_sturmtrooper_stggunner","SPE_ST_Sentry_K98k","SPE_ST_Sentry_MP35","SPE_ST_Sentry_MP40","SPE_GER_Driver","SPE_GER_Driver_Lite",
"SPE_GER_Flamethrower_Operator","SPE_GER_amgunner","SPE_GER_rifleman_2","SPE_GER_rifleman","SPE_GER_rifleman_lite","SPE_GER_ober_rifleman","SPE_GER_stggunner",
"SPE_GER_Sentry_K98k","SPE_GER_Sentry_MP40","SPE_GER_gun_crew","SPE_OST_CSK_amgunner","SPE_OST_CSK_rifleman","SPE_OST_CSK_ober_rifleman","SPE_FSJ_amgunner",
"SPE_FSJ_Soldier","SPE_FSJ_Soldier_FG42","SPE_FSJ_Soldier_STG44","SPE_GER_flak_gun_crew","SPE_OST_amgunner","SPE_OST_Flamethrower_Operator","SPE_OST_rifleman_2",
"SPE_OST_rifleman","SPE_OST_rifleman_lite","SPE_OST_ober_rifleman","SPE_OST_stggunner","SPE_OST_Sentry_K98k","SPE_OST_Sentry_MP40","SPE_GER_lehr_amgunner",
"SPE_GER_lehr_Rifleman","SPE_GER_scout_Halftrack_Driver","SPE_GER_scout_amgunner","SPE_GER_scout_rifleman","SPE_GER_scout_ober_rifleman"];
_baseClassRadiomanArray append ["SPE_Milice_FG_Radioman","SPE_Milice_FG_NP_Radioman","SPE_sturmtrooper_radioman","SPE_GER_radioman","SPE_FSJ_radioman","SPE_OST_radioman"];
_baseClassMedicArray append ["SPE_Milice_FG_Medic","SPE_Milice_FG_NP_Medic","SPE_sturmtrooper_medic","SPE_GER_medic","SPE_FSJ_medic","SPE_OST_Medic"];
_baseClassEngineerArray append ["SPE_sturmtrooper_sapper","SPE_sturmtrooper_sapper_gefr","SPE_GER_sapper","SPE_GER_sapper_gefr","SPE_FSJ_sapper",
"SPE_FSJ_sapper_gefr","SPE_OST_sapper","SPE_OST_sapper_gefr"];
_baseClassExplosivesArray append ["SPE_sturmtrooper_sapper","SPE_sturmtrooper_sapper_gefr","SPE_GER_sapper","SPE_GER_sapper_gefr","SPE_FSJ_sapper",
"SPE_FSJ_sapper_gefr","SPE_OST_sapper","SPE_OST_sapper_gefr"];
_baseClassGrenadierArray append ["SPE_Milice_FG_AT_grenadier","SPE_Milice_FG_NP_AT_grenadier","SPE_sturmtrooper_AT_grenadier","SPE_sturmtrooper_ober_grenadier",
"SPE_GER_AT_grenadier","SPE_GER_ober_grenadier","SPE_OST_CSK_ober_grenadier","SPE_FSJ_AT_grenadier","SPE_FSJ_grenadier","SPE_OST_AT_grenadier","SPE_OST_ober_grenadier",
"SPE_GER_lehr_grenadier","SPE_GER_scout_ober_grenadier"];
_baseClassLATArray append ["SPE_Milice_FG_LAT_rifleman","SPE_Milice_FG_NP_LAT_rifleman","SPE_sturmtrooper_LAT_Klein_Rifleman",
"SPE_sturmtrooper_LAT_30m_Rifleman","SPE_sturmtrooper_LAT_rifleman","SPE_GER_LAT_Klein_Rifleman","SPE_GER_LAT_30m_Rifleman","SPE_GER_LAT_Rifleman","SPE_FSJ_LAT_Soldier",
"SPE_OST_LAT_Klein_Rifleman","SPE_OST_LAT_30m_Rifleman","SPE_OST_LAT_Rifleman","SPE_GER_lehr_LAT_Rifleman"];
_baseClassATArray append ["SPE_ST_AT_Soldier","SPE_GER_AT_Soldier","SPE_FSJ_AT_soldier"];
_baseClassAAArray append ["SPE_Milice_FG_NP_Rifleman","SPE_Milice_FG_NP_Sentry","SPE_Milice_FG_NP_Sentry_Sten","SPE_ST_Driver","SPE_FSJ_Soldier","SPE_FSJ_Soldier_FG42","SPE_FSJ_Soldier_STG44","SPE_GER_flak_gun_crew"];
_baseClassMachineGunnerArray append ["SPE_Milice_FG_Autorifleman","SPE_Milice_FG_NP_Autorifleman","SPE_GER_mgunner2","SPE_GER_mgunner","SPE_OST_CSK_mgunner2",
"SPE_OST_CSK_mgunner","SPE_FSJ_hmgunner2","SPE_FSJ_Mgunner","SPE_OST_mgunner","SPE_OST_mgunner2","SPE_OST_hmgunner","SPE_GER_lehr_mgunner2","SPE_GER_lehr_mgunner",
"SPE_GER_scout_mgunner2","SPE_GER_scout_mgunner"];
_baseClassMarksmanArray append ["SPE_FSJ_Sniper_FG42"];
_baseClassSniperArray append ["SPE_sturmtrooper_sniper","SPE_OST_CSK_sniper","SPE_FSJ_Sniper","SPE_GER_scout_sniper"];
_baseClassPatrolSniperArray append ["SPE_sturmtrooper_sniper","SPE_OST_CSK_sniper","SPE_FSJ_Sniper","SPE_GER_scout_sniper"];
_baseClassPatrolSpotterArray append ["SPE_FSJ_Sniper_FG42"];
// ================== Специальные роли ==================
_baseClassPoliceArray append ["SPE_Milice_FG_Assist_Autorifleman","SPE_Milice_FG_Rifleman","SPE_Milice_FG_Sentry","SPE_Milice_FG_Sentry_Sten",
"SPE_Milice_FG_NP_Assist_Autorifleman","SPE_Milice_FG_NP_Rifleman","SPE_Milice_FG_NP_Sentry","SPE_Milice_FG_NP_Sentry_Sten"];

_baseClassCrewArray append ["SPE_ST_spg_crew","SPE_ST_spg_unterofficer","SPE_ST_spg_lieutenant","SPE_ST_tank_crew","SPE_ST_tank_unterofficer",
"SPE_sturmtrooper_tank_crew","SPE_sturmtrooper_tank_unterofficer","SPE_sturmtrooper_tank_lieutenant","SPE_ST_tank_lieutenant","SPE_GER_gun_lieutenant","SPE_GER_spg_crew",
"SPE_GER_spg_unterofficer","SPE_GER_spg_lieutenant","SPE_GER_tank_crew","SPE_GER_tank_unterofficer","SPE_GER_tank_lieutenant"];
_baseClassPilotArray append ["SPE_GER_pilot"];
_baseClassOfficialArray append ["SPE_Milice_FG_Regional_Commander","SPE_sturmtrooper_hauptsturmfuhrer","SPE_sturmtrooper_standartenfuhrer",
"SPE_sturmtrooper_obersturmfuhrer","SPE_sturmtrooper_untersturmfuhrer","SPE_GER_hauptmann","SPE_GER_oberst","SPE_GER_ober_lieutenant","SPE_GER_lieutenant",
"SPE_GER_gun_lieutenant","SPE_OST_CSK_lieutenant","SPE_FSJ_Lieutenant","SPE_OST_lieutenant","SPE_GER_lehr_lieutenant","SPE_GER_scout_lieutenant"];
_baseClassTraitorArray append ["SPE_FFI_CellLeader","SPE_FFI_Doctor","SPE_FFI_Fighter_G43","SPE_FFI_Fighter_Garand","SPE_FFI_MGunner","SPE_FFI_Sapper_Mle208"];
_baseClassUnarmedArray append ["SPE_GER_spg_lieutenant","SPE_GER_tank_lieutenant"];

_voices append ["SPE_Male01GER", "SPE_Male02GER"];
_faces append ["LivonianHead_6","SPE_boyartsev","SPE_bykov","SPE_Connors","SPE_DAgostino","SPE_Davidson","SPE_Elliot","SPE_Grishka","SPE_Hauptmann","SPE_Klimakov","SPE_Krueger","SPE_Kuzmin","SPE_Neumann","SPE_Oberst","SPE_OBrien","SPE_Vasiliev","SPE_Walter","SPE_Wolf","Sturrock","WhiteHead_01","WhiteHead_02","WhiteHead_03","WhiteHead_04","WhiteHead_05","WhiteHead_06","WhiteHead_08","WhiteHead_09","WhiteHead_11","WhiteHead_12","WhiteHead_13","WhiteHead_14","WhiteHead_15","WhiteHead_18","WhiteHead_19","WhiteHead_20","WhiteHead_21"];

_KAR98muzzle = ["SPE_ACC_K98_Bayo","SPE_ACC_GW_SB_Empty"];

// Оружие
(_loadoutData get "slRifles") append [
	["SPE_FG42_E", "", "", "SPE_Optic_ZFG42", ["SPE_20Rnd_792x57","SPE_20Rnd_792x57_t2","SPE_20Rnd_792x57_SMK","SPE_20Rnd_792x57_sS","SPE_20Rnd_792x57_t"], [], ""],
	["SPE_FG42_E", "", "", "", ["SPE_20Rnd_792x57","SPE_20Rnd_792x57_t2","SPE_20Rnd_792x57_SMK","SPE_20Rnd_792x57_sS","SPE_20Rnd_792x57_t"], [], ""],
	["SPE_Flammenwerfer41", "", "", "", ["SPE_Flammenwerfer41_Mag","SPE_Flammenwerfer41_Mag","SPE_Flammenwerfer41_Mag"], [], ""]
];
(_loadoutData get "rifles") append [
	["SPE_G43", "", "", "",["SPE_10Rnd_792x57","SPE_10Rnd_792x57_T2","SPE_10Rnd_792x57_SMK","SPE_10Rnd_792x57_sS","SPE_10Rnd_792x57_T"], [], ""],
	["SPE_K98", _KAR98muzzle, "", "",["SPE_10Rnd_792x57","SPE_10Rnd_792x57_T2","SPE_10Rnd_792x57_SMK","SPE_10Rnd_792x57_sS","SPE_10Rnd_792x57_T"], [], ""],
	["SPE_K98_Late", _KAR98muzzle, "", "",["SPE_10Rnd_792x57","SPE_10Rnd_792x57_T2","SPE_10Rnd_792x57_SMK","SPE_10Rnd_792x57_sS","SPE_10Rnd_792x57_T"], [], ""],
	["SPE_STG44", "", "", "",["SPE_30Rnd_792x33","SPE_30rnd_792x33_t","SPE_30Rnd_792x33","SPE_30rnd_792x33_t"], [], ""]
];
(_loadoutData get "carbines") append [
	["SPE_Fusil_Mle_208_12", "", "", "",["SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug","SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug"], [], ""],
	["SPE_Fusil_Mle_208_12_Sawedoff", "", "", "",["SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug","SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug"], [], ""],
	["SPE_FG42_E", "", "", "", ["SPE_20Rnd_792x57","SPE_20Rnd_792x57_t2","SPE_20Rnd_792x57_SMK","SPE_20Rnd_792x57_sS","SPE_20Rnd_792x57_t"], [], ""]
];
(_loadoutData get "grenadeLaunchers") append [
	["SPE_K98", "SPE_ACC_GW_SB_Empty", "", "", ["SPE_5Rnd_792x57"], ["SPE_1Rnd_G_SPRGR_30","SPE_1Rnd_G_PZGR_30","SPE_1Rnd_G_PZGR_40"], ""],
    ["SPE_K98_Late", "SPE_ACC_GW_SB_Empty", "", "", ["SPE_5Rnd_792x57"], ["SPE_1Rnd_G_SPRGR_30","SPE_1Rnd_G_PZGR_30","SPE_1Rnd_G_PZGR_40"], ""]
];
(_loadoutData get "SMGs") append [
	["SPE_MP35", "", "", "", ["SPE_24Rnd_MP35_9x19","SPE_24rnd_MP35_9x19_t","SPE_32Rnd_MP35_9x19","SPE_32rnd_MP35_9x19_t"], [], ""],
	["SPE_MP40", "", "", "", ["SPE_32Rnd_9x19","SPE_32rnd_9x19_t","SPE_32Rnd_9x19","SPE_32rnd_9x19_t"], [], ""]
];
(_loadoutData get "machineGuns") append [
	["SPE_FM_24_M29", "", "", "", ["SPE_25Rnd_75x54","SPE_25Rnd_75x54_35P_AP","SPE_25Rnd_75x54","SPE_25Rnd_75x54_35P_AP"], [], ""],
	["SPE_MG34", "", "", "", ["SPE_100Rnd_792x57","SPE_100Rnd_792x57_SMK","SPE_100Rnd_792x57_sS","SPE_50Rnd_792x57","SPE_50Rnd_792x57_SMK","SPE_50Rnd_792x57_sS"], [], ""],
	["SPE_MG42", "", "", "", ["SPE_100Rnd_792x57","SPE_100Rnd_792x57_SMK","SPE_100Rnd_792x57_sS","SPE_50Rnd_792x57","SPE_50Rnd_792x57_SMK","SPE_50Rnd_792x57_sS"], [], ""]
];
(_loadoutData get "marksmanRifles") append [
	["SPE_FG42_E", "", "", "SPE_Optic_ZFG42", ["SPE_20Rnd_792x57","SPE_20Rnd_792x57_t2","SPE_20Rnd_792x57_SMK","SPE_20Rnd_792x57_sS","SPE_20Rnd_792x57_t"], [], ""],
	["SPE_K98ZF39", "", "", "",["SPE_10Rnd_792x57","SPE_10Rnd_792x57_T2","SPE_10Rnd_792x57_SMK","SPE_10Rnd_792x57_sS","SPE_10Rnd_792x57_T"], [], ""]
];
(_loadoutData get "sniperRifles") append [
	["SPE_K98ZF39", "", "", "",["SPE_10Rnd_792x57","SPE_10Rnd_792x57_T2","SPE_10Rnd_792x57_SMK","SPE_10Rnd_792x57_sS","SPE_10Rnd_792x57_T"], [], ""]
];

// Пусковые установки
(_loadoutData get "lightATLaunchers") append [
	["SPE_PzFaust_30m", "", "", "", ["SPE_1Rnd_PzFaust_30m"], [], ""],
	["SPE_PzFaust_60m", "", "", "", ["SPE_1Rnd_PzFaust_60m"], [], ""]
];
(_loadoutData get "ATLaunchers") append [
	["SPE_RPzB_43", "", "", "", ["SPE_1Rnd_RPzBGr_4322","SPE_1Rnd_RPzBGr_4322"], [], ""],
	["SPE_RPzB_54", "", "", "", ["SPE_1Rnd_RPzBGr_4322","SPE_1Rnd_RPzBGr_4322"], [], ""]
];
(_loadoutData get "sidearms") append [
	["SPE_P08", "", "", "", ["SPE_8Rnd_9x19_P08","SPE_8Rnd_9x19_P08"], [], ""]
];

// Взрывчатка
(_loadoutData get "ATMines") append ["SPE_TMI_42_MINE_mag"];
(_loadoutData get "APMines") append ["SPE_SMI_35_Pressure_MINE_mag"];
(_loadoutData get "lightExplosives") append ["SPE_Ladung_Small_MINE_mag"];
(_loadoutData get "heavyExplosives") append ["SPE_Ladung_Big_MINE_mag"];

// Гранаты
(_loadoutData get "antiInfantryGrenades") append ["SPE_Shg24", "SPE_M39","SPE_Shg24x7"];
(_loadoutData get "smokeGrenades") append ["SPE_NB39"];
(_loadoutData get "signalsmokeGrenades") append ["SmokeShellYellow", "SmokeShellRed", "SmokeShellPurple", "SmokeShellOrange", "SmokeShellGreen", "SmokeShellBlue"];

// Базовое снаряжение
(_loadoutData get "maps") append ["ItemMap"];
(_loadoutData get "watches") append ["SPE_GER_ItemWatch"];
(_loadoutData get "compasses") append ["SPE_GER_ItemCompass_deg", "SPE_GER_ItemCompass"];
(_loadoutData get "radios") append ["TFAR_SCR536"];
//(_loadoutData get "gpses") append [];
(_loadoutData get "NVGs") append ["SPE_GER_FL_Signal_Flashlight","SPE_GER_Headset"];
(_loadoutData get "binoculars") append ["SPE_Binocular_GER"];
(_loadoutData get "rangefinders") append ["SPE_Binocular_GER"];

// Предательская экипировка
(_loadoutData get "traitorUniforms") append [
	"U_SPE_FFI_Casual_1",
	"U_SPE_FFI_Casual_1_trop",
	"U_SPE_FFI_Casual_2",
	"U_SPE_FFI_Casual_2_trop",
	"U_SPE_FFI_Casual_3",
	"U_SPE_FFI_Casual_3_trop",
	"U_SPE_FFI_Casual_4",
	"U_SPE_FFI_Casual_4_trop",
	"U_SPE_FFI_Casual_5",
	"U_SPE_FFI_Casual_5_trop",
	"U_SPE_FFI_Casual_6",
	"U_SPE_FFI_Casual_6_trop",
	"U_SPE_FFI_Casual_7",
	"U_SPE_FFI_Casual_7_trop",
	"U_SPE_FFI_Jacket_zwart",
	"U_SPE_FFI_Jacket_zwart_Alt",
	"U_SPE_FFI_Jacket_zwart_swetr",
	"U_SPE_FFI_Jacket_bruin",
	"U_SPE_FFI_Jacket_bruin_swetr",
	"U_SPE_FFI_Jacket_grijs",
	"U_SPE_FFI_Jacket_grijs_swetr",
	"U_SPE_FFI_Worker_1",
	"U_SPE_FFI_Worker_1_trop",
	"U_SPE_FFI_Worker_2",
	"U_SPE_FFI_Worker_2_trop",
	"U_SPE_FFI_Worker_3",
	"U_SPE_FFI_Worker_3_trop",
	"U_SPE_FFI_Worker_4",
	"U_SPE_FFI_Worker_4_trop"
];
(_loadoutData get "traitorVests") append [
	"V_SPE_FFI_Vest_SMG_pouch",
	"V_SPE_FFI_Vest_SMG_frag",
	"V_SPE_FFI_Vest_SMG",
	"V_SPE_FFI_Vest_rifle_pouch",
	"V_SPE_FFI_Vest_rifle_frag",
	"V_SPE_FFI_Vest_rifle",
	"V_SPE_FFI_Vest_Pouch_frag",
	"V_SPE_FFI_Vest_Pouch"
];
(_loadoutData get "traitorHats") append [
	"H_SPE_CIV_Worker_Cap_1",
	"H_SPE_CIV_Worker_Cap_2",
	"H_SPE_CIV_Worker_Cap_3",
	"H_SPE_CIV_Fedora_Cap_3",
	"H_SPE_CIV_Fedora_Cap_4",
	"H_SPE_CIV_Fedora_Cap_2",
	"H_SPE_CIV_Fedora_Cap_1",
	"H_SPE_CIV_Fedora_Cap_6",
	"H_SPE_CIV_Fedora_Cap_5"
];

// Офицерская экипировка
(_loadoutData get "officerUniforms") append [
	"U_SPE_GER_Unterofficer",
	"U_SPE_GER_Art_unterofficer",
	"U_SPE_GER_Unterofficer_hbt",
	"U_SPE_GER_Hauptmann",
	"U_SPE_GER_Leutnant",
	"U_SPE_GER_Oberleutnant",
	"U_SPE_GER_Oberst",
	"U_SPE_GER_Art_leutnant",
	"U_SPE_CSK_offz",
	"U_SPE_OST_offz",
	"U_SPE_GER_lehr_unterofficer",
	"U_SPE_GER_Spg_crew_unterofficer"
];
(_loadoutData get "officerVests") append [
	"V_SPE_OST_officer",
	"V_SPE_OST_sword",
	"V_SPE_GER_FieldOfficer",
	"V_SPE_GER_VestUnterofficer",
	"V_SPE_erla_VestUnterofficer"
];
(_loadoutData get "officerHats") append [
	"H_SPE_GER_Cap_Offz",
	"H_SPE_GER_TankOffzCap3",
	"H_SPE_GER_ArtOfficerCap",
	"H_SPE_GER_OfficerCap",
	"H_SPE_GER_PzgrenOfficerCap",
	"H_SPE_GER_TankOfficerCap",
	"H_SPE_GER_TankOfficerCap2",
	"H_SPE_GER_M38_PzGren_Offz",
	"H_SPE_GER_M38_PzGren_Offz_2",
	"H_SPE_GER_ST_M40_cap_Offz",
	"H_SPE_GER_ST_M40_cap_Offz_hp"
];

// Основная экипировка
(_loadoutData get "uniforms") append [
	"U_SPE_GER_Soldier_camo",
	"U_SPE_GER_Soldier_camo2",
	"U_SPE_GER_Soldier_camo4",
	"U_SPE_GER_Soldier_camo5",
	"U_SPE_GER_Soldier_camo5_boot",
	"U_SPE_GER_Soldier_camo5_gaiter",
	"U_SPE_GER_Soldier_camo3",
	"U_SPE_GER_Soldier_M36_Boots",
	"U_SPE_GER_Soldier_m36_Gefreiter",
	"U_SPE_GER_Soldier_M36_Boots_open",
	"U_SPE_GER_Soldier_M36_Boots_Rolled",
	"U_SPE_GER_Soldier_m36_uffz",
	"U_SPE_GER_Soldier_M40_Boots",
	"U_SPE_GER_Soldier_M40_Gaiters",
	"U_SPE_GER_Soldier_M40_Gaiters_closed",
	"U_SPE_GER_Soldier_M40_Gaiters_Rolled",
	"U_SPE_GER_Soldier_M40_Gefreiter",
	"U_SPE_GER_Soldier_M40_Gefreiter_gaiters",
	"U_SPE_GER_Soldier_M40_Boots_open",
	"U_SPE_GER_Soldier_M40_Boots_Rolled",
	"U_SPE_GER_Soldier_M40_uffz",
	"U_SPE_GER_Soldier_M40_uffz_gaiters",
	"U_SPE_GER_Soldier_M40_Unbloused",
	"U_SPE_GER_Soldier_Boots",
	"U_SPE_GER_Soldier_Gaiters",
	"U_SPE_GER_Soldier_Gaiters_closed",
	"U_SPE_GER_MG_schutze",
	"U_SPE_GER_Gefreiter_Gaiters",
	"U_SPE_GER_Oberschutze",
	"U_SPE_GER_Soldier_Boots_open",
	"U_SPE_GER_Soldier_Boots_Rolled",
	"U_SPE_GER_Gefreiter",
	"U_SPE_GER_Medic",
	"U_SPE_GER_Soldier_Unbloused",
	"U_SPE_GER_Unterofficer",
	"U_SPE_GER_Art_schutze",
	"U_SPE_GER_Art_unterofficer",
	"U_SPE_GER_Schutze_hbt",
	"U_SPE_GER_MG_schutze_hbt",
	"U_SPE_GER_Unterofficer_hbt",
	"U_SPE_FSJ_mk1",
	"U_SPE_FSJ_mk1_gefr",
	"U_SPE_FSJ_mk1_gloves",
	"U_SPE_FSJ_mk1_gloves_pads",
	"U_SPE_FSJ_mk1_pads",
	"U_SPE_FSJ_mk1_pads_roll",
	"U_SPE_FSJ_mk1_roll",
	"U_SPE_FSJ_mk1_uffz",
	"U_SPE_FSJ_mk1_uffz_gloves",
	"U_SPE_FSJ_mk1_uffz_gloves_pads",
	"U_SPE_FSJ_mk1_uffz_pads",
	"U_SPE_FSJ_mk2",
	"U_SPE_FSJ_mk2_gefr",
	"U_SPE_FSJ_mk2_gloves",
	"U_SPE_FSJ_mk2_gloves_pads",
	"U_SPE_FSJ_mk2_pads",
	"U_SPE_FSJ_mk2_pads_roll",
	"U_SPE_FSJ_mk2_roll",
	"U_SPE_FSJ_mk2_split",
	"U_SPE_FSJ_mk2_split_gefr",
	"U_SPE_FSJ_mk2_split_gloves",
	"U_SPE_FSJ_mk2_split_gloves_pads",
	"U_SPE_FSJ_mk2_split_pads",
	"U_SPE_FSJ_mk2_split_pads_roll",
	"U_SPE_FSJ_mk2_split_roll",
	"U_SPE_FSJ_mk2_split_uffz",
	"U_SPE_FSJ_mk2_split_uffz_gloves",
	"U_SPE_FSJ_mk2_split_uffz_gloves_pads",
	"U_SPE_FSJ_mk2_split_uffz_pads",
	"U_SPE_FSJ_mk2_uffz",
	"U_SPE_FSJ_mk2_uffz_gloves",
	"U_SPE_FSJ_mk2_uffz_gloves_pads",
	"U_SPE_FSJ_mk2_uffz_pads",
	"U_SPE_FSJ_mk3_split",
	"U_SPE_FSJ_mk3_split_gefr",
	"U_SPE_FSJ_mk3_split_gloves",
	"U_SPE_FSJ_mk3_split_gloves_pads",
	"U_SPE_FSJ_mk3_split_trop",
	"U_SPE_FSJ_mk3_split_trop_roll",
	"U_SPE_FSJ_mk3_split_pads",
	"U_SPE_FSJ_mk3_split_pads_roll",
	"U_SPE_FSJ_mk3_split_roll",
	"U_SPE_FSJ_mk3_split_uffz",
	"U_SPE_FSJ_mk3_split_uffz_gloves",
	"U_SPE_FSJ_mk3_split_uffz_gloves_pads",
	"U_SPE_FSJ_mk3_split_uffz_pads",
	"U_SPE_FSJ_mk3_sumpf",
	"U_SPE_FSJ_mk3_sumpf_gefr",
	"U_SPE_FSJ_mk3_sumpf_gloves",
	"U_SPE_FSJ_mk3_sumpf_gloves_pads",
	"U_SPE_FSJ_mk3_sumpf_trop",
	"U_SPE_FSJ_mk3_sumpf_trop_roll",
	"U_SPE_FSJ_mk3_sumpf_pads",
	"U_SPE_FSJ_mk3_sumpf_pads_roll",
	"U_SPE_FSJ_mk3_sumpf_roll",
	"U_SPE_FSJ_mk3_sumpf_uffz",
	"U_SPE_FSJ_mk3_sumpf_uffz_gloves",
	"U_SPE_FSJ_mk3_sumpf_uffz_gloves_pads",
	"U_SPE_FSJ_mk3_sumpf_uffz_pads",
	"U_SPE_FSJ_mk1_offz",
	"U_SPE_FSJ_mk1_offz_gloves",
	"U_SPE_FSJ_mk1_offz_gloves_pads",
	"U_SPE_FSJ_mk1_offz_pads",
	"U_SPE_FSJ_mk2_offz",
	"U_SPE_FSJ_mk2_offz_gloves",
	"U_SPE_FSJ_mk2_offz_gloves_pads",
	"U_SPE_FSJ_mk2_offz_pads",
	"U_SPE_FSJ_mk2_split_offz",
	"U_SPE_FSJ_mk2_split_offz_gloves",
	"U_SPE_FSJ_mk2_split_offz_gloves_pads",
	"U_SPE_FSJ_mk2_split_offz_pads",
	"U_SPE_FSJ_mk3_split_offz",
	"U_SPE_FSJ_mk3_split_offz_gloves",
	"U_SPE_FSJ_mk3_split_offz_gloves_pads",
	"U_SPE_FSJ_mk3_split_offz_pads",
	"U_SPE_FSJ_mk3_sumpf_offz",
	"U_SPE_FSJ_mk3_sumpf_offz_gloves",
	"U_SPE_FSJ_mk3_sumpf_offz_gloves_pads",
	"U_SPE_FSJ_mk3_sumpf_offz_pads",
	"U_SPE_LW_FSJ_base",
	"U_SPE_LW_FSJ_gefr",
	"U_SPE_LW_FSJ_roll",
	"U_SPE_LW_FSJ_uffz",
	"U_SPE_LW_FSJ_mk3",
	"U_SPE_LW_FSJ_mk3_gefr",
	"U_SPE_LW_FSJ_mk3_roll",
	"U_SPE_LW_FSJ_mk3_uffz",
	"U_SPE_LW_base",
	"U_SPE_LW_Feldwebel",
	"U_SPE_LW_2_Feldwebel",
	"U_SPE_LW_2",
	"U_SPE_LW_2_op",
	"U_SPE_LW_2_roll",
	"U_SPE_LW_gefr",
	"U_SPE_LW_2_gefr",
	"U_SPE_LW_op",
	"U_SPE_LW_roll",
	"U_SPE_LW_Uffz",
	"U_SPE_LW_2_Uffz",
	"U_SPE_CSK_base",
	"U_SPE_CSK_2",
	"U_SPE_CSK_2_op",
	"U_SPE_CSK_2_roll",
	"U_SPE_CSK_gefreiter",
	"U_SPE_CSK_2_gefreiter",
	"U_SPE_CSK_offz",
	"U_SPE_CSK_op",
	"U_SPE_CSK_roll",
	"U_SPE_CSK_uffz",
	"U_SPE_CSK_2_uffz",
	"U_SPE_OST_base",
	"U_SPE_OST_2",
	"U_SPE_OST_2_op",
	"U_SPE_OST_2_roll",
	"U_SPE_OST_gefreiter",
	"U_SPE_OST_2_gefreiter",
	"U_SPE_OST_offz",
	"U_SPE_OST_op",
	"U_SPE_OST_roll",
	"U_SPE_OST_uffz",
	"U_SPE_OST_2_uffz",
	"U_SPE_GER_lehr_private",
	"U_SPE_GER_lehr_gefreiter",
	"U_SPE_GER_lehr_unterofficer",
	"U_SPE_ST_Soldier_Camo2",
	"U_SPE_ST_Soldier_Camo2_Boots",
	"U_SPE_ST_Sniper2",
	"U_SPE_ST_Soldier_Camo6",
	"U_SPE_ST_Soldier_Camo6_Boots",
	"U_SPE_ST_Soldier_Camo4",
	"U_SPE_ST_Soldier_Camo4_Boots",
	"U_SPE_ST_Soldier_Camo",
	"U_SPE_ST_Soldier_Camo_Boots",
	"U_SPE_ST_Sniper",
	"U_SPE_ST_Soldier_Camo5",
	"U_SPE_ST_Soldier_Camo5_Boots",
	"U_SPE_ST_Soldier_Camo3",
	"U_SPE_ST_Soldier_Camo3_Boots",
	"U_SPE_ST_Soldier_M36_Boots",
	"U_SPE_ST_Soldier_M36_Boots_open",
	"U_SPE_ST_Soldier_M36_Boots_rolled",
	"U_SPE_ST_Soldier_m36_Sturmmann",
	"U_SPE_ST_Soldier_m36_uscharf",
	"U_SPE_ST_Soldier_M40_Boots",
	"U_SPE_ST_Soldier_M40_Gaiters",
	"U_SPE_ST_Soldier_M40_Gaiters_closed",
	"U_SPE_ST_Soldier_M40_rolled",
	"U_SPE_ST_Soldier_M40_Boots_open",
	"U_SPE_ST_Soldier_M40_Boots_rolled",
	"U_SPE_ST_Soldier_M40_Sturmmann",
	"U_SPE_ST_Soldier_M40_Sturmmann_gaiters",
	"U_SPE_ST_Soldier_M40_Unbloused",
	"U_SPE_ST_Soldier_M40_uscharf",
	"U_SPE_ST_Soldier_M40_uscharf_gaiters",
	"U_SPE_ST_Soldier_Boots",
	"U_SPE_ST_Soldier_Gaiters",
	"U_SPE_ST_Soldier_Gaiters_closed",
	"U_SPE_ST_Soldier_rolled",
	"U_SPE_ST_Soldier_Boots_open",
	"U_SPE_ST_Soldier_Boots_rolled",
	"U_SPE_ST_Soldier_Unbloused",
	"U_SPE_ST_Mix_E44",
	"U_SPE_ST_Mix_E44_roll",
	"U_SPE_ST_Sturmmann_E44",
	"U_SPE_ST_Unterofficier_E44",
	"U_SPE_ST_Soldier_E44",
	"U_SPE_ST_Soldier_E44_Camo2",
	"U_SPE_ST_Soldier_E44_Camo6",
	"U_SPE_ST_Soldier_E44_Camo4",
	"U_SPE_ST_Soldier_E44_Boots",
	"U_SPE_ST_Soldier_E44_Boots_rolled",
	"U_SPE_ST_Medic_E44",
	"U_SPE_ST_MGunner_E44",
	"U_SPE_ST_Soldier_E44_Camo",
	"U_SPE_ST_Soldier_E44_Camo5",
	"U_SPE_ST_Soldier_E44_Camo3",
	"U_SPE_ST_Soldier_E44_Unbloused"
];
(_loadoutData get "slUniforms") append [
	"U_SPE_GER_Leutnant",
	"U_SPE_GER_Oberleutnant",
	"U_SPE_GER_Soldier_camo_lieutenant",
	"U_SPE_GER_Soldier_camo_lieutenant_2",
	"U_SPE_GER_Art_leutnant",
	"U_SPE_CSK_offz",
	"U_SPE_OST_offz",
	"U_SPE_GER_lehr_leutnant"
];
(_loadoutData get "vests") append [
	"V_SPE_DAK_VestG43",
	"V_SPE_DAK_VestMG",
	"V_SPE_DAK_VestKar98",
	"V_SPE_DAK_FWOVest",
	"V_SPE_DAK_VestMP40",
	"V_SPE_DAK_VestSTG",
	"V_SPE_DAK_VestUnterofficer",
	"V_SPE_DAK_SaniVest2",
	"V_SPE_OST_officer",
	"V_SPE_OST_sword",
	"V_SPE_GER_SniperBelt",
	"V_SPE_GER_VestG43",
	"V_SPE_GER_SaniVest2",
	"V_SPE_GER_VestMG",
	"V_SPE_GER_FieldOfficer",
	"V_SPE_GER_VestKar98",
	"V_SPE_GER_SaniVest",
	"V_SPE_GER_FWOVest",
	"V_SPE_GER_VestMP40",
	"V_SPE_GER_VestSTG",
	"V_SPE_GER_VestUnterofficer",
	"V_SPE_GER_LW_Schwimm",
	"V_SPE_erla_VestG43",
	"V_SPE_erla_SaniVest2",
	"V_SPE_erla_VestMG",
	"V_SPE_erla_VestKar98",
	"V_SPE_erla_FWOVest",
	"V_SPE_erla_VestMP40",
	"V_SPE_erla_VestSTG",
	"V_SPE_erla_VestUnterofficer",
	"V_SPE_GER_FSJ_blau_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_blau_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_blau_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_blau_VestFG42_Bandoleer_pistol",
	"V_SPE_GER_FSJ_blau_G43",
	"V_SPE_GER_FSJ_blau_MG",
	"V_SPE_GER_FSJ_blau_VestKar98",
	"V_SPE_GER_FSJ_blau_FWO",
	"V_SPE_GER_FSJ_blau_SMG",
	"V_SPE_GER_FSJ_blau_STG",
	"V_SPE_GER_FSJ_blau_NCO",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_gelb",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_split",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_gelb",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_split",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_G43",
	"V_SPE_GER_FSJ_MG",
	"V_SPE_GER_FSJ_VestKar98",
	"V_SPE_GER_FSJ_FWO",
	"V_SPE_GER_FSJ_SMG",
	"V_SPE_GER_FSJ_STG",
	"V_SPE_GER_FSJ_NCO",
	"V_SPE_GER_FSJ_Sani2",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_gelb",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_split",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_gelb",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_split",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_camo_G43",
	"V_SPE_GER_FSJ_camo_MG",
	"V_SPE_GER_FSJ_camo_VestKar98",
	"V_SPE_GER_FSJ_camo_FWO",
	"V_SPE_GER_FSJ_camo_SMG",
	"V_SPE_GER_FSJ_camo_STG",
	"V_SPE_GER_FSJ_camo_NCO",
	"V_SPE_GER_PistolBelt",
	"V_SPE_GER_TankPrivateBelt"
];
(_loadoutData get "Hvests") append [
	"V_SPE_DAK_PioneerVest",
	"V_SPE_GER_PioneerVest",
	"V_SPE_erla_PioneerVest",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol",
	"V_SPE_GER_FSJ_Pio"
];
(_loadoutData get "sniVests") append [
	"V_SPE_DAK_VestG43",
	"V_SPE_DAK_VestMG",
	"V_SPE_DAK_VestKar98",
	"V_SPE_DAK_FWOVest",
	"V_SPE_DAK_VestMP40",
	"V_SPE_DAK_VestSTG",
	"V_SPE_DAK_VestUnterofficer",
	"V_SPE_DAK_SaniVest2",
	"V_SPE_OST_officer",
	"V_SPE_OST_sword",
	"V_SPE_GER_SniperBelt",
	"V_SPE_GER_VestG43",
	"V_SPE_GER_SaniVest2",
	"V_SPE_GER_VestMG",
	"V_SPE_GER_FieldOfficer",
	"V_SPE_GER_VestKar98",
	"V_SPE_GER_SaniVest",
	"V_SPE_GER_FWOVest",
	"V_SPE_GER_VestMP40",
	"V_SPE_GER_VestSTG",
	"V_SPE_GER_VestUnterofficer",
	"V_SPE_GER_LW_Schwimm",
	"V_SPE_erla_VestG43",
	"V_SPE_erla_SaniVest2",
	"V_SPE_erla_VestMG",
	"V_SPE_erla_VestKar98",
	"V_SPE_erla_FWOVest",
	"V_SPE_erla_VestMP40",
	"V_SPE_erla_VestSTG",
	"V_SPE_erla_VestUnterofficer",
	"V_SPE_GER_FSJ_blau_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_blau_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_blau_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_blau_VestFG42_Bandoleer_pistol",
	"V_SPE_GER_FSJ_blau_G43",
	"V_SPE_GER_FSJ_blau_MG",
	"V_SPE_GER_FSJ_blau_VestKar98",
	"V_SPE_GER_FSJ_blau_FWO",
	"V_SPE_GER_FSJ_blau_SMG",
	"V_SPE_GER_FSJ_blau_STG",
	"V_SPE_GER_FSJ_blau_NCO",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_gelb",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_split",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_gelb",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_split",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_G43",
	"V_SPE_GER_FSJ_MG",
	"V_SPE_GER_FSJ_VestKar98",
	"V_SPE_GER_FSJ_FWO",
	"V_SPE_GER_FSJ_SMG",
	"V_SPE_GER_FSJ_STG",
	"V_SPE_GER_FSJ_NCO",
	"V_SPE_GER_FSJ_Sani2",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_gelb",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_gelb",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_split",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_split",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_sumpf",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer",
	"V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_gelb",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_split",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_sumpf",
	"V_SPE_GER_FSJ_camo_VestFG42_Bandoleer",
	"V_SPE_GER_FSJ_camo_G43",
	"V_SPE_GER_FSJ_camo_MG",
	"V_SPE_GER_FSJ_camo_VestKar98",
	"V_SPE_GER_FSJ_camo_FWO",
	"V_SPE_GER_FSJ_camo_SMG",
	"V_SPE_GER_FSJ_camo_STG",
	"V_SPE_GER_FSJ_camo_NCO",
	"V_SPE_GER_PistolBelt",
	"V_SPE_GER_TankPrivateBelt"
];
(_loadoutData get "backpacks") append [
	"B_SPE_GER_A_frame_kit",
	"B_SPE_GER_A_frame_sturm",
	"B_SPE_GER_A_frame_zeltbahn",
	"B_SPE_GER_A_frame_MGCan",
	"B_SPE_GER_A_frame_MGCan_zelt",
	"B_SPE_GER_A_frame_sturm_licht",
	"B_SPE_GER_A_frame_zeltbahn_licht",
	"B_SPE_GER_A_frame",
	"B_SPE_GER_A_frame_Full",
	"B_SPE_GER_Belt_bag_zelt",
	"B_SPE_GER_Belt_bag_zelt_trop",
	"B_SPE_GER_Belt_bag",
	"B_SPE_GER_erla_bag",
	"B_SPE_GER_erla_bag_zelt",
	"B_SPE_GER_RPzB_Belt_bag_zelt",
	"B_SPE_GER_Flammenwerfer_41",
	"B_SPE_GER_FSJ_Belt_bag_zelt",
	"B_SPE_GER_FSJ_Belt_bag_zelt_trop",
	"B_SPE_GER_FSJ_Belt_bag",
	"B_SPE_GER_FSJ_RPzB_Belt_bag_zelt",
	"B_SPE_GER_Belt_bag_zelt_camo",
	"B_SPE_GER_Belt_bag_camo",
	"B_SPE_GER_Radio_battery",
	"B_SPE_GER_A_frame_ST_MGCan",
	"B_SPE_GER_A_frame_ST_MGCan_zelt",
	"B_SPE_GER_A_frame_ST_zeltbahn_licht",
	"B_SPE_GER_A_frame_ST",
	"B_SPE_GER_A_frame_ST_Full",
	"B_SPE_GER_Belt_bag_ST_zelt",
	"B_SPE_GER_erla_bag_ST_zelt",
	"B_SPE_GER_Belt_bag_ST_zelt_trop",
	"B_SPE_GER_Belt_bag_ST_zelt_camo",
	"B_SPE_GER_Tonister41_Frame_ST",
	"B_SPE_GER_MedicBackpack_Empty",
	"B_SPE_GER_Tonister34_canvas",
	"B_SPE_GER_Tonister41_Frame"
];
(_loadoutData get "longRangeRadios") append [
	"B_SPE_GER_Radio_battery",
	"B_SPE_GER_Radio"
];
(_loadoutData get "atBackpacks") append [
	"B_SPE_GER_ammo_Belt_bag",
	"B_SPE_GER_ammo_Belt_bag_alt",
	"B_SPE_GER_ammo_Belt_bag_zelt",
	"B_SPE_GER_ammo_Belt_bag_medic",
	"B_SPE_GER_Pzf_Belt_bag",
	"B_SPE_GER_Pzf_Belt_bag_zelt",
	"B_SPE_GER_RPzB_Belt_bag",
	"B_SPE_GER_Flammenwerfer_41",
	"B_SPE_GER_FSJ_ammo_Belt_bag",
	"B_SPE_GER_FSJ_ammo_Belt_bag_zelt",
	"B_SPE_GER_FSJ_Pzf_Belt_bag",
	"B_SPE_GER_FSJ_Pzf_Belt_bag_zelt",
	"B_SPE_GER_FSJ_RPzB_Belt_bag",
	"B_SPE_GER_FSJ_RPzB_Belt_bag_zelt",
	"B_SPE_GER_FSJ_ammo_Belt_bag_camo",
	"B_SPE_GER_FSJ_ammo_Belt_bag_zelt_camo",
	"B_SPE_GER_ammo_Belt_bag_camo",
	"B_SPE_GER_ammo_Belt_bag_zelt_camo",
	"B_SPE_ST_ammo_Belt_bag_zelt",
	"B_SPE_ST_Pzf_Belt_bag_zelt",
	"B_SPE_ST_RPzB_Belt_bag_zelt",
	"B_SPE_ST_ammo_Belt_bag_zelt_camo",
	"B_SPE_GER_Tonister41_Frame_Full_ST",
	"B_SPE_GER_Tonister41_Frame_Full"
];
(_loadoutData get "helmets") append [
	"H_SPE_GER_Cap",
	"H_SPE_GER_SPGPrivateCap2",
	"H_SPE_GER_SPGPrivateCap",
	"H_SPE_GER_FSJ_M38_Helmet",
	"H_SPE_GER_FSJ_M38_Helmet_kentang",
	"H_SPE_GER_FSJ_M38_Helmet_Cover",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_fade",
	"H_SPE_GER_FSJ_M38_Helmet_erla",
	"H_SPE_GER_FSJ_M38_Helmet_medic_alt",
	"H_SPE_GER_FSJ_M38_Helmet_medic",
	"H_SPE_GER_FSJ_M38_Helmet_Net",
	"H_SPE_GER_FSJ_M38_Helmet_Net_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Net_camo",
	"H_SPE_GER_FSJ_M38_Helmet_camo1",
	"H_SPE_GER_FSJ_M38_Helmet_camo2",
	"H_SPE_GER_FSJ_M38_Helmet_camo3",
	"H_SPE_GER_FSJ_M38_Helmet_camo4",
	"H_SPE_GER_FSJ_M38_Helmet_camo5",
	"H_SPE_GER_FSJ_M38_Helmet_camo",
	"H_SPE_GER_FSJ_M38_Helmet_sutra",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split2",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split1",
	"H_SPE_GER_FSJ_M38_Helmet_BB",
	"H_SPE_GER_FSJ_M38_Helmet_BB_erla",
	"H_SPE_GER_FSJ_M38_Helmet_BB_camo",
	"H_SPE_GER_FSJ_M38_Helmet_Wire",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_camo",
	"H_SPE_GER_LW_Cap",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW_Offz",
	"H_SPE_GER_M40_LW_Offz_2",
	"H_SPE_GER_M40_LW_2",
	"H_SPE_GER_Helmet_M35_LW",
	"H_SPE_GER_Helmet_M35_LW_ns",
	"H_SPE_GER_Helmet_M40_lw",
	"H_SPE_GER_Helmet_M40_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw",
	"H_SPE_GER_Helmet_M40_lw_camo",
	"H_SPE_GER_Helmet_M40_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_camo",
	"H_SPE_GER_Cuba",
	"H_SPE_GER_M38",
	"H_SPE_GER_M38_art_headset",
	"H_SPE_GER_M38_Art_Offz",
	"H_SPE_GER_M38_Art_Offz_headset",
	"H_SPE_GER_M38_Art_Offz_2",
	"H_SPE_GER_M38_art_2",
	"H_SPE_GER_M38_art",
	"H_SPE_GER_M38_headset",
	"H_SPE_GER_M38_inf_Offz",
	"H_SPE_GER_M38_inf_Offz_2",
	"H_SPE_GER_M38_inf_2",
	"H_SPE_GER_M38_inf",
	"H_SPE_GER_M38_Offz",
	"H_SPE_GER_M38_Offz_2",
	"H_SPE_GER_M38_Pz_headset",
	"H_SPE_GER_M38_Pz_Offz",
	"H_SPE_GER_M38_Pz_Offz_headset",
	"H_SPE_GER_M38_Pz_Offz_2",
	"H_SPE_GER_M38_Pz_2",
	"H_SPE_GER_M38_Pz",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_M38_PzGren_Offz",
	"H_SPE_GER_M38_PzGren_Offz_2",
	"H_SPE_GER_M38_pzgren_2",
	"H_SPE_GER_M38_pzgren",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_ST_Tanker_Cap2",
	"H_SPE_GER_ST_Tanker_Cap",
	"H_SPE_GER_Fieldcap",
	"H_SPE_GER_ST_M40_cap",
	"H_SPE_GER_ST_M40_cap_hp",
	"H_SPE_GER_ST_M40_cap_Offz",
	"H_SPE_GER_ST_M40_cap_Offz_hp",
	"H_SPE_GER_ST_M40_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap",
	"H_SPE_GER_ST_M40_Pz_cap_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap_2",
	"H_SPE_GER_ST_M40_cap_2",
	"H_SPE_ST_Helmet2",
	"H_SPE_ST_Helmet2_OS",
	"H_SPE_ST_Helmet",
	"H_SPE_ST_Helmet_OS",
	"H_SPE_ST_Helmet6",
	"H_SPE_ST_Helmet6_OS",
	"H_SPE_ST_Helmet5",
	"H_SPE_ST_Helmet5_OS",
	"H_SPE_ST_Helmet4",
	"H_SPE_ST_Helmet4_OS",
	"H_SPE_ST_Helmet3",
	"H_SPE_ST_Helmet3_OS",
	"H_SPE_GER_Helmet_M40_burlap_band",
	"H_SPE_GER_Helmet_M40_burlap_band_ns",
	"H_SPE_GER_HelmetCamo3",
	"H_SPE_GER_HelmetCamo3_OS",
	"H_SPE_GER_HelmetCamo4",
	"H_SPE_GER_HelmetCamo",
	"H_SPE_GER_HelmetCamo2",
	"H_SPE_GER_Helmet_M35",
	"H_SPE_GER_Helmet_M35_Glasses",
	"H_SPE_GER_Helmet_M35_Glasses_ns",
	"H_SPE_GER_Helmet_M35_ns",
	"H_SPE_GER_Helmet_M40",
	"H_SPE_GER_Helmet_M40Utility",
	"H_SPE_GER_Helmet_M40Utility_OS",
	"H_SPE_GER_Helmet_M40_Glasses",
	"H_SPE_GER_Helmet_M40_Glasses_ns",
	"H_SPE_GER_Helmet_M40Utility_Grass",
	"H_SPE_GER_Helmet_M40Utility_Grass_OS",
	"H_SPE_GER_Helmet_M40_net",
	"H_SPE_GER_Helmet_M40_ns_net",
	"H_SPE_GER_Helmet_M40Utility_Oak",
	"H_SPE_GER_Helmet_M40Utility_Oak_OS",
	"H_SPE_GER_Helmet_M40_ns",
	"H_SPE_GER_Helmet_M40_ns_wire",
	"H_SPE_GER_Helmet_M40_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted_ns",
	"H_SPE_GER_Helmet_M40_net_painted",
	"H_SPE_GER_Helmet_M40_ns_net_painted",
	"H_SPE_GER_Helmet_M40_ns_painted",
	"H_SPE_GER_Helmet_M40_wire_painted",
	"H_SPE_GER_Helmet_M40_ns_wire_painted",
	"H_SPE_GER_Helmet_M40_wire",
	"H_SPE_GER_Helmet",
	"H_SPE_GER_HelmetUtility",
	"H_SPE_GER_HelmetUtility_OS",
	"H_SPE_GER_Helmet_Glasses",
	"H_SPE_GER_HelmetUtility_Grass",
	"H_SPE_GER_HelmetUtility_Grass_OS",
	"H_SPE_GER_Helmet_Medic",
	"H_SPE_GER_Helmet_net",
	"H_SPE_GER_Helmet_net_ns",
	"H_SPE_GER_HelmetUtility_Oak",
	"H_SPE_GER_HelmetUtility_Oak_OS",
	"H_SPE_GER_Helmet_ns",
	"H_SPE_GER_Helmet_painted",
	"H_SPE_GER_Helmet_Glasses_painted",
	"H_SPE_GER_Helmet_net_painted",
	"H_SPE_GER_Helmet_net_painted_ns",
	"H_SPE_GER_Helmet_ns_painted",
	"H_SPE_GER_Helmet_os_painted",
	"H_SPE_GER_Helmet_ns_wire_painted",
	"H_SPE_GER_Helmet_os",
	"H_SPE_GER_Helmet_ns_wire"
];
(_loadoutData get "slHat") append [
	"H_SPE_GER_Cap",
	"H_SPE_GER_SPGPrivateCap2",
	"H_SPE_GER_SPGPrivateCap",
	"H_SPE_GER_FSJ_M38_Helmet",
	"H_SPE_GER_FSJ_M38_Helmet_kentang",
	"H_SPE_GER_FSJ_M38_Helmet_Cover",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_fade",
	"H_SPE_GER_FSJ_M38_Helmet_erla",
	"H_SPE_GER_FSJ_M38_Helmet_medic_alt",
	"H_SPE_GER_FSJ_M38_Helmet_medic",
	"H_SPE_GER_FSJ_M38_Helmet_Net",
	"H_SPE_GER_FSJ_M38_Helmet_Net_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Net_camo",
	"H_SPE_GER_FSJ_M38_Helmet_camo1",
	"H_SPE_GER_FSJ_M38_Helmet_camo2",
	"H_SPE_GER_FSJ_M38_Helmet_camo3",
	"H_SPE_GER_FSJ_M38_Helmet_camo4",
	"H_SPE_GER_FSJ_M38_Helmet_camo5",
	"H_SPE_GER_FSJ_M38_Helmet_camo",
	"H_SPE_GER_FSJ_M38_Helmet_sutra",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split2",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split1",
	"H_SPE_GER_FSJ_M38_Helmet_BB",
	"H_SPE_GER_FSJ_M38_Helmet_BB_erla",
	"H_SPE_GER_FSJ_M38_Helmet_BB_camo",
	"H_SPE_GER_FSJ_M38_Helmet_Wire",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_camo",
	"H_SPE_GER_LW_Cap",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW_Offz",
	"H_SPE_GER_M40_LW_Offz_2",
	"H_SPE_GER_M40_LW_2",
	"H_SPE_GER_Helmet_M35_LW",
	"H_SPE_GER_Helmet_M35_LW_ns",
	"H_SPE_GER_Helmet_M40_lw",
	"H_SPE_GER_Helmet_M40_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw",
	"H_SPE_GER_Helmet_M40_lw_camo",
	"H_SPE_GER_Helmet_M40_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_camo",
	"H_SPE_GER_Cuba",
	"H_SPE_GER_M38",
	"H_SPE_GER_M38_art_headset",
	"H_SPE_GER_M38_Art_Offz",
	"H_SPE_GER_M38_Art_Offz_headset",
	"H_SPE_GER_M38_Art_Offz_2",
	"H_SPE_GER_M38_art_2",
	"H_SPE_GER_M38_art",
	"H_SPE_GER_M38_headset",
	"H_SPE_GER_M38_inf_Offz",
	"H_SPE_GER_M38_inf_Offz_2",
	"H_SPE_GER_M38_inf_2",
	"H_SPE_GER_M38_inf",
	"H_SPE_GER_M38_Offz",
	"H_SPE_GER_M38_Offz_2",
	"H_SPE_GER_M38_Pz_headset",
	"H_SPE_GER_M38_Pz_Offz",
	"H_SPE_GER_M38_Pz_Offz_headset",
	"H_SPE_GER_M38_Pz_Offz_2",
	"H_SPE_GER_M38_Pz_2",
	"H_SPE_GER_M38_Pz",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_M38_PzGren_Offz",
	"H_SPE_GER_M38_PzGren_Offz_2",
	"H_SPE_GER_M38_pzgren_2",
	"H_SPE_GER_M38_pzgren",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_ST_Tanker_Cap2",
	"H_SPE_GER_ST_Tanker_Cap",
	"H_SPE_GER_Fieldcap",
	"H_SPE_GER_ST_M40_cap",
	"H_SPE_GER_ST_M40_cap_hp",
	"H_SPE_GER_ST_M40_cap_Offz",
	"H_SPE_GER_ST_M40_cap_Offz_hp",
	"H_SPE_GER_ST_M40_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap",
	"H_SPE_GER_ST_M40_Pz_cap_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap_2",
	"H_SPE_GER_ST_M40_cap_2",
	"H_SPE_ST_Helmet2",
	"H_SPE_ST_Helmet2_OS",
	"H_SPE_ST_Helmet",
	"H_SPE_ST_Helmet_OS",
	"H_SPE_ST_Helmet6",
	"H_SPE_ST_Helmet6_OS",
	"H_SPE_ST_Helmet5",
	"H_SPE_ST_Helmet5_OS",
	"H_SPE_ST_Helmet4",
	"H_SPE_ST_Helmet4_OS",
	"H_SPE_ST_Helmet3",
	"H_SPE_ST_Helmet3_OS",
	"H_SPE_GER_Helmet_M40_burlap_band",
	"H_SPE_GER_Helmet_M40_burlap_band_ns",
	"H_SPE_GER_HelmetCamo3",
	"H_SPE_GER_HelmetCamo3_OS",
	"H_SPE_GER_HelmetCamo4",
	"H_SPE_GER_HelmetCamo",
	"H_SPE_GER_HelmetCamo2",
	"H_SPE_GER_Helmet_M35",
	"H_SPE_GER_Helmet_M35_Glasses",
	"H_SPE_GER_Helmet_M35_Glasses_ns",
	"H_SPE_GER_Helmet_M35_ns",
	"H_SPE_GER_Helmet_M40",
	"H_SPE_GER_Helmet_M40Utility",
	"H_SPE_GER_Helmet_M40Utility_OS",
	"H_SPE_GER_Helmet_M40_Glasses",
	"H_SPE_GER_Helmet_M40_Glasses_ns",
	"H_SPE_GER_Helmet_M40Utility_Grass",
	"H_SPE_GER_Helmet_M40Utility_Grass_OS",
	"H_SPE_GER_Helmet_M40_net",
	"H_SPE_GER_Helmet_M40_ns_net",
	"H_SPE_GER_Helmet_M40Utility_Oak",
	"H_SPE_GER_Helmet_M40Utility_Oak_OS",
	"H_SPE_GER_Helmet_M40_ns",
	"H_SPE_GER_Helmet_M40_ns_wire",
	"H_SPE_GER_Helmet_M40_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted_ns",
	"H_SPE_GER_Helmet_M40_net_painted",
	"H_SPE_GER_Helmet_M40_ns_net_painted",
	"H_SPE_GER_Helmet_M40_ns_painted",
	"H_SPE_GER_Helmet_M40_wire_painted",
	"H_SPE_GER_Helmet_M40_ns_wire_painted",
	"H_SPE_GER_Helmet_M40_wire",
	"H_SPE_GER_Helmet",
	"H_SPE_GER_HelmetUtility",
	"H_SPE_GER_HelmetUtility_OS",
	"H_SPE_GER_Helmet_Glasses",
	"H_SPE_GER_HelmetUtility_Grass",
	"H_SPE_GER_HelmetUtility_Grass_OS",
	"H_SPE_GER_Helmet_Medic",
	"H_SPE_GER_Helmet_net",
	"H_SPE_GER_Helmet_net_ns",
	"H_SPE_GER_HelmetUtility_Oak",
	"H_SPE_GER_HelmetUtility_Oak_OS",
	"H_SPE_GER_Helmet_ns",
	"H_SPE_GER_Helmet_painted",
	"H_SPE_GER_Helmet_Glasses_painted",
	"H_SPE_GER_Helmet_net_painted",
	"H_SPE_GER_Helmet_net_painted_ns",
	"H_SPE_GER_Helmet_ns_painted",
	"H_SPE_GER_Helmet_os_painted",
	"H_SPE_GER_Helmet_ns_wire_painted",
	"H_SPE_GER_Helmet_os",
	"H_SPE_GER_Helmet_ns_wire"
];
(_loadoutData get "sniHats") append [
	"H_SPE_GER_Cap",
	"H_SPE_GER_SPGPrivateCap2",
	"H_SPE_GER_SPGPrivateCap",
	"H_SPE_GER_FSJ_M38_Helmet",
	"H_SPE_GER_FSJ_M38_Helmet_kentang",
	"H_SPE_GER_FSJ_M38_Helmet_Cover",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_fade",
	"H_SPE_GER_FSJ_M38_Helmet_erla",
	"H_SPE_GER_FSJ_M38_Helmet_medic_alt",
	"H_SPE_GER_FSJ_M38_Helmet_medic",
	"H_SPE_GER_FSJ_M38_Helmet_Net",
	"H_SPE_GER_FSJ_M38_Helmet_Net_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Net_camo",
	"H_SPE_GER_FSJ_M38_Helmet_camo1",
	"H_SPE_GER_FSJ_M38_Helmet_camo2",
	"H_SPE_GER_FSJ_M38_Helmet_camo3",
	"H_SPE_GER_FSJ_M38_Helmet_camo4",
	"H_SPE_GER_FSJ_M38_Helmet_camo5",
	"H_SPE_GER_FSJ_M38_Helmet_camo",
	"H_SPE_GER_FSJ_M38_Helmet_sutra",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split2",
	"H_SPE_GER_FSJ_M38_Helmet_Cover_split1",
	"H_SPE_GER_FSJ_M38_Helmet_BB",
	"H_SPE_GER_FSJ_M38_Helmet_BB_erla",
	"H_SPE_GER_FSJ_M38_Helmet_BB_camo",
	"H_SPE_GER_FSJ_M38_Helmet_Wire",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_erla",
	"H_SPE_GER_FSJ_M38_Helmet_Wire_camo",
	"H_SPE_GER_LW_Cap",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW",
	"H_SPE_GER_M40_LW_Offz",
	"H_SPE_GER_M40_LW_Offz_2",
	"H_SPE_GER_M40_LW_2",
	"H_SPE_GER_Helmet_M35_LW",
	"H_SPE_GER_Helmet_M35_LW_ns",
	"H_SPE_GER_Helmet_M40_lw",
	"H_SPE_GER_Helmet_M40_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw_net",
	"H_SPE_GER_Helmet_M40_ns_lw",
	"H_SPE_GER_Helmet_M40_lw_camo",
	"H_SPE_GER_Helmet_M40_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_net_camo",
	"H_SPE_GER_Helmet_M40_ns_lw_camo",
	"H_SPE_GER_Cuba",
	"H_SPE_GER_M38",
	"H_SPE_GER_M38_art_headset",
	"H_SPE_GER_M38_Art_Offz",
	"H_SPE_GER_M38_Art_Offz_headset",
	"H_SPE_GER_M38_Art_Offz_2",
	"H_SPE_GER_M38_art_2",
	"H_SPE_GER_M38_art",
	"H_SPE_GER_M38_headset",
	"H_SPE_GER_M38_inf_Offz",
	"H_SPE_GER_M38_inf_Offz_2",
	"H_SPE_GER_M38_inf_2",
	"H_SPE_GER_M38_inf",
	"H_SPE_GER_M38_Offz",
	"H_SPE_GER_M38_Offz_2",
	"H_SPE_GER_M38_Pz_headset",
	"H_SPE_GER_M38_Pz_Offz",
	"H_SPE_GER_M38_Pz_Offz_headset",
	"H_SPE_GER_M38_Pz_Offz_2",
	"H_SPE_GER_M38_Pz_2",
	"H_SPE_GER_M38_Pz",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_M38_PzGren_Offz",
	"H_SPE_GER_M38_PzGren_Offz_2",
	"H_SPE_GER_M38_pzgren_2",
	"H_SPE_GER_M38_pzgren",
	"H_SPE_GER_M38_2",
	"H_SPE_GER_Fieldcap2",
	"H_SPE_GER_ST_Tanker_Cap2",
	"H_SPE_GER_ST_Tanker_Cap",
	"H_SPE_GER_Fieldcap",
	"H_SPE_GER_ST_M40_cap",
	"H_SPE_GER_ST_M40_cap_hp",
	"H_SPE_GER_ST_M40_cap_Offz",
	"H_SPE_GER_ST_M40_cap_Offz_hp",
	"H_SPE_GER_ST_M40_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap",
	"H_SPE_GER_ST_M40_Pz_cap_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_headset",
	"H_SPE_GER_ST_M40_Pz_cap_Offz_2",
	"H_SPE_GER_ST_M40_Pz_cap_2",
	"H_SPE_GER_ST_M40_cap_2",
	"H_SPE_ST_Helmet2",
	"H_SPE_ST_Helmet2_OS",
	"H_SPE_ST_Helmet",
	"H_SPE_ST_Helmet_OS",
	"H_SPE_ST_Helmet6",
	"H_SPE_ST_Helmet6_OS",
	"H_SPE_ST_Helmet5",
	"H_SPE_ST_Helmet5_OS",
	"H_SPE_ST_Helmet4",
	"H_SPE_ST_Helmet4_OS",
	"H_SPE_ST_Helmet3",
	"H_SPE_ST_Helmet3_OS",
	"H_SPE_GER_Helmet_M40_burlap_band",
	"H_SPE_GER_Helmet_M40_burlap_band_ns",
	"H_SPE_GER_HelmetCamo3",
	"H_SPE_GER_HelmetCamo3_OS",
	"H_SPE_GER_HelmetCamo4",
	"H_SPE_GER_HelmetCamo",
	"H_SPE_GER_HelmetCamo2",
	"H_SPE_GER_Helmet_M35",
	"H_SPE_GER_Helmet_M35_Glasses",
	"H_SPE_GER_Helmet_M35_Glasses_ns",
	"H_SPE_GER_Helmet_M35_ns",
	"H_SPE_GER_Helmet_M40",
	"H_SPE_GER_Helmet_M40Utility",
	"H_SPE_GER_Helmet_M40Utility_OS",
	"H_SPE_GER_Helmet_M40_Glasses",
	"H_SPE_GER_Helmet_M40_Glasses_ns",
	"H_SPE_GER_Helmet_M40Utility_Grass",
	"H_SPE_GER_Helmet_M40Utility_Grass_OS",
	"H_SPE_GER_Helmet_M40_net",
	"H_SPE_GER_Helmet_M40_ns_net",
	"H_SPE_GER_Helmet_M40Utility_Oak",
	"H_SPE_GER_Helmet_M40Utility_Oak_OS",
	"H_SPE_GER_Helmet_M40_ns",
	"H_SPE_GER_Helmet_M40_ns_wire",
	"H_SPE_GER_Helmet_M40_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted",
	"H_SPE_GER_Helmet_M40_Glasses_painted_ns",
	"H_SPE_GER_Helmet_M40_net_painted",
	"H_SPE_GER_Helmet_M40_ns_net_painted",
	"H_SPE_GER_Helmet_M40_ns_painted",
	"H_SPE_GER_Helmet_M40_wire_painted",
	"H_SPE_GER_Helmet_M40_ns_wire_painted",
	"H_SPE_GER_Helmet_M40_wire",
	"H_SPE_GER_Helmet",
	"H_SPE_GER_HelmetUtility",
	"H_SPE_GER_HelmetUtility_OS",
	"H_SPE_GER_Helmet_Glasses",
	"H_SPE_GER_HelmetUtility_Grass",
	"H_SPE_GER_HelmetUtility_Grass_OS",
	"H_SPE_GER_Helmet_Medic",
	"H_SPE_GER_Helmet_net",
	"H_SPE_GER_Helmet_net_ns",
	"H_SPE_GER_HelmetUtility_Oak",
	"H_SPE_GER_HelmetUtility_Oak_OS",
	"H_SPE_GER_Helmet_ns",
	"H_SPE_GER_Helmet_painted",
	"H_SPE_GER_Helmet_Glasses_painted",
	"H_SPE_GER_Helmet_net_painted",
	"H_SPE_GER_Helmet_net_painted_ns",
	"H_SPE_GER_Helmet_ns_painted",
	"H_SPE_GER_Helmet_os_painted",
	"H_SPE_GER_Helmet_ns_wire_painted",
	"H_SPE_GER_Helmet_os",
	"H_SPE_GER_Helmet_ns_wire"
];

// Аксессуары
(_loadoutData get "glasses") append ["G_SPE_Cigarette_Belomorkanal","G_SPE_Cigarette_Grundstein","G_SPE_Cigarette_Strike_Outs","G_SPE_Dienst_Brille","G_SPE_Dust_Goggles_2","G_SPE_Dust_Goggles_2","G_SPE_Ful_Vue","G_SPE_Sunglasses_GER_Brown","G_SPE_Sunglasses_GER_Red","G_SPE_Sunglasses_US_Red","G_SPE_Sunglasses_US_Yellow"];
(_loadoutData get "goggles") append ["G_SPE_Binoculars","G_SPE_GER_GM30","G_SPE_Dust_Goggles","G_SPE_GER_Headset"];

// Дополнительные предметы для специализаций
_eeItems append ["ToolKit", "MineDetector"];