    class vehicles_base
    {
        prefix = "";
    };
    #include "vehicles\vehicles_rhs.hpp"
    #include "vehicles\vehicles_3cbf.hpp"
    #include "vehicles\vehicles_ifa3.hpp"
    #include "vehicles\vehicles_cup.hpp"
    #include "vehicles\vehicles_racs.hpp"
    #include "vehicles\vehicles_ffaa.hpp"
    #include "vehicles\vehicles_vanilla.hpp"
    #include "vehicles\vehicles_ws.hpp"
    #include "vehicles\vehicles_pla.hpp"
    #include "vehicles\vehicles_sfp.hpp"
    #include "vehicles\vehicles_cw.hpp"
    #include "vehicles\vehicles_optre.hpp"
    #include "vehicles\vehicles_sog.hpp"
    #include "vehicles\vehicles_scion.hpp"
    #include "vehicles\vehicles_tmt.hpp"
    #include "vehicles\vehicles_gm.hpp"
    #include "vehicles\vehicles_spe.hpp"
    #include "vehicles\vehicles_unsung.hpp"
    #include "vehicles\vehicles_amf.hpp"
    #include "vehicles\vehicles_3cbbaf.hpp"
    #include "vehicles\vehicles_bw.hpp"
    #include "vehicles\vehicles_pedagne.hpp"
    #include "vehicles\vehicles_aegis.hpp"
    #include "vehicles\vehicles_braf.hpp"
    #include "vehicles\vehicles_tfc.hpp"
    #include "vehicles\vehicles_fow.hpp"
    #include "vehicles\vehicles_csa38.hpp"