_basic append ["SPE_US_G503_MB_Open"];
_unarmedVehicles append ["SPE_US_G503_MB", "SPE_US_G503_MB_Armoured","SPE_FFI_R200_Unarmed","SPE_FFI_R200_Hood"];
_armedVehicles append ["SPE_US_G503_MB_M1919_Armoured", "SPE_US_G503_MB_M2_Armoured", "SPE_US_G503_MB_M2_PATROL", "SPE_US_G503_MB_M1919_PATROL","SPE_FFI_R200_MG34"];
_Trucks append ["SPE_US_M3_Halftrack_Unarmed", "SPE_CCKW_353_Open", "SPE_CCKW_353","SPE_FFI_OpelBlitz","SPE_FFI_OpelBlitz_Open","SPE_FR_M3_Halftrack_Unarmed"];
_cargoTrucks append ["SPE_CCKW_353_Open","SPE_FR_M3_Halftrack_Unarmed_Open","SPE_FFI_OpelBlitz","SPE_FFI_OpelBlitz_Open"];
_ammoTrucks append ["SPE_US_M3_Halftrack_Ammo", "SPE_CCKW_353_Ammo","SPE_FFI_OpelBlitz_Ammo","SPE_FR_M3_Halftrack_Ammo"];
_repairTrucks append ["SPE_US_M3_Halftrack_Repair", "SPE_CCKW_353_Repair","SPE_FFI_OpelBlitz_Repair","SPE_FR_M3_Halftrack_Repair"];
_fuelTrucks append ["SPE_US_M3_Halftrack_Fuel", "SPE_CCKW_353_Fuel","SPE_FFI_OpelBlitz_Fuel","SPE_FR_M3_Halftrack_Fuel"];
_medicalTrucks append ["SPE_US_M3_Halftrack_Ambulance", "SPE_US_G503_MB_Ambulance", "SPE_CCKW_353_Ambulance","SPE_FFI_OpelBlitz_Ambulance","SPE_FR_M3_Halftrack_Ambulance"];
_lightAPCs append ["SPE_CCKW_353_M2", "SPE_US_M3_Halftrack"];
_APCs append ["SPE_US_M3_Halftrack", "SPE_US_M16_Halftrack", "SPE_US_M3_Halftrack","SPE_FFI_SdKfz250_1","SPE_FR_M16_Halftrack"];
_IFVs append ["SPE_M8_LAC_ringMount", "SPE_M8_LAC","SPE_FR_M8_LAC","SPE_FR_M8_LAC_ringMount"];
_airborneVehicles append ["SPE_M20_AUC","SPE_FR_M20_AUC"];
_tanks append ["SPE_M4A0_75_Early", "SPE_M4A0_75", "SPE_M4A1_76", "SPE_M4A1_75", "SPE_M4A0_composite", "SPE_M4A0_105", "SPE_M4A1_75_erla", "SPE_M4A3_105",
 "SPE_M4A3_75", "SPE_M4A3_76","SPE_FR_M4A0_75_Early","SPE_FR_M4A0_75_mid","SPE_FR_M4A0_105","SPE_FR_M4A1_75","SPE_FR_M4A1_76","SPE_FR_M4A3_75",
 "SPE_FR_M4A3_76","SPE_M4A3_T34_Calliope_Direct","SPE_M4A1_T34_Calliope_Direct""SPE_FR_M4A0_75_Early_DLV",
"SPE_FR_M4A0_75_mid_DLV","SPE_FR_M4A0_105_DLV","SPE_FR_M4A1_75_DLV","SPE_FR_M4A1_76_DLV","SPE_FR_M4A3_75_DLV","SPE_FR_M4A3_76_DLV","SPE_M18_Hellcat_DLV"];
_lightTanks append ["SPE_M8_LAC_ringMount", "SPE_M8_LAC","SPE_FR_M8_LAC","SPE_FR_M8_LAC_ringMount","SPE_FR_M10", "SPE_M10","SPE_FR_M10_DLV","SPE_M10_DLV","SPE_M18_Hellcat",
"SPE_M4A0_75_Early_DLV","SPE_M4A0_composite_DLV","SPE_M4A0_75_DLV","SPE_M4A0_105_DLV","SPE_M4A1_75_erla_DLV","SPE_M4A0_composite_DLV","SPE_M4A0_75_DLV","SPE_M4A1_76_DLV",
"SPE_M4A1_T34_Calliope_Direct_DLV","SPE_M4A3_105_DLV","SPE_M4A3_75_DLV","SPE_M4A3_76_DLV","SPE_M4A3_T34_Calliope_Direct_DLV"];
_aa append ["SPE_US_M16_Halftrack","SPE_FR_M16_Halftrack"];

_planesCAS append ["SPE_P47"];
_planesAA append ["SPE_P47"];

_artillery append ["SPE_M4A1_T34_Calliope", "SPE_M4A3_T34_Calliope","SPE_M4A1_T34_Calliope_DLV","SPE_M4A3_T34_Calliope_DLV"];

_militiaLightArmed append ["SPE_US_G503_MB_M1919", "SPE_US_G503_MB_M2"];
_militiaTrucks append ["SPE_CCKW_353_Open"];
_militiaCars append ["SPE_US_G503_MB_Open"];
_militiaAPCs append ["SPE_M20_AUC","SPE_FR_M20_AUC"]; 

_policeVehs append ["SPE_CCKW_353_Open"];

_staticMG append ["SPE_M1919_M2_Trench_Deployed","SPE_FR_M1919_M2_Trench_Deployed"];
_staticAT append ["SPE_57mm_M1", "SPE_105mm_M3_Direct","SPE_FR_57mm_M1"];
_staticAA append ["SPE_FR_M45_Quadmount","SPE_FR_M45_Quadmount"];
_staticMortars append ["SPE_M1_81"];
_howitzers append ["SPE_105mm_M3"];

_radar append ["SPE_FlaK_36_AA"];
_SAM append ["SPE_FlaK_36_AA"];

_mortarMagazineHE append ["SPE_8Rnd_81mmHE_M1_M43A1"];
_mortarMagazineSmoke append ["SPE_8rnd_81mm_M1_M57_SmokeShell"];

_minefieldAT append ["SPE_US_M1A1_ATMINE"];
_minefieldAPERS append ["SPE_US_M3_Pressure_MINE", "SPE_US_M3_MINE"];

_howitzerMagazineHE append ["SPE_20x_Shell_105L28_Gr38_HE"];

if (isClass (configFile >> "CfgPatches" >> "WW2_SPEX_Assets_m_Vehicles_Planes_m")) then {
	_transportBoat append ["SPEX_LCVP"];
	_gunBoat append ["SPEX_LCVP"];
    _planesTransport append ["SPEX_C47_Skytrain"];
	_staticMortars append ["SPEX_M2_60"];
	_basic append ["SPEX_T3_Trailer","SPEX_T3_Trailer_Ammo","SPEX_T3_Trailer_Fuel","SPEX_T3_Trailer_Repair"];
};

_baseClassSquadLeaderArray append ["SPE_FR_Assist_SquadLead","SPE_FR_Captain","SPE_FR_SquadLead","SPE_US_Assist_SquadLead","SPE_US_Captain","SPE_US_First_Lieutenant",
"SPE_US_Second_Lieutenant","SPE_US_SquadLead","SPE_US_101AB_Assist_SquadLead","SPE_US_101AB_SquadLead","SPE_US_HBT44_Assist_SquadLead","SPE_US_HBT44_Second_Lieutenant",
"SPE_US_HBT44_SquadLead","SPE_US_Rangers_Assist_SquadLead","SPE_US_Rangers_captain","SPE_US_Rangers_first_lieutenant","SPE_US_Rangers_second_lieutenant","SPE_US_Rangers_SquadLead",
"SPE_US_82AB_Assist_SquadLead","SPE_US_82AB_SquadLead","SPE_US_Assist_SquadLead_late","SPE_US_Captain_late","SPE_US_First_Lieutenant_late","SPE_US_Second_Lieutenant_late","SPE_US_SquadLead_late"];
_baseClassRiflemanArray append ["SPE_FR_Assist_Autorifleman","SPE_FR_Flamethrower_Operator","SPE_FR_Rifleman","SPE_FR_Rifleman_Carbine","SPE_FR_Sentry_Carbine","SPE_FR_Sentry",
"SPE_US_Rifleman_AmmoBearer","SPE_US_Assist_Autorifleman","SPE_US_Driver","SPE_US_Driver_Lite","SPE_US_Flamethrower_Operator",
"SPE_US_Rifleman","SPE_US_Sentry_Carbine","SPE_US_Sentry","SPE_US_101AB_Rifleman_AmmoBearer","SPE_US_101AB_Assist_Autorifleman","SPE_US_101AB_Flamethrower_Operator",
"SPE_US_101AB_rifleman","SPE_US_101AB_rifleman_carbine","SPE_US_101AB_smgunner","SPE_US_HBT44_AHMGunner","SPE_US_HBT44_Flamethrower_Operator",
"SPE_US_HBT44_HalfTrack_Driver","SPE_US_HBT44_Rifleman","SPE_US_Rangers_Rifleman_AmmoBearer","SPE_US_Rangers_Assist_Autorifleman","SPE_US_Rangers_Flamethrower_Operator",
"SPE_US_Rangers_rifleman","SPE_US_82AB_Rifleman_AmmoBearer","SPE_US_82AB_Flamethrower_Operator","SPE_US_82AB_rifleman","SPE_US_82AB_rifleman_carbine","SPE_US_82AB_smgunner",
"SPE_US_Rifleman_AmmoBearer_late","SPE_US_Assist_Autorifleman_late","SPE_US_Driver_late","SPE_US_Driver_lite_late","SPE_US_Flamethrower_Operator_late","SPE_US_Rifleman_late","SPE_US_Sentry_Carbine_late"];
_baseClassRadiomanArray append ["SPE_FR_Radioman","SPE_US_Radioman","SPE_US_101AB_radioman","SPE_US_HBT44_Radioman","SPE_US_Rangers_radioman","SPE_US_82AB_radioman","SPE_US_Radioman_late","SPE_US_Sentry_late"];
_baseClassMedicArray append ["SPE_FR_Medic","SPE_US_Medic","SPE_US_101AB_medic","SPE_US_HBT44_Medic","SPE_US_Rangers_medic","SPE_US_82AB_medic","SPE_US_Medic_late"];
_baseClassEngineerArray append ["SPE_FR_Engineer","SPE_US_Engineer","SPE_US_101AB_Engineer","SPE_US_HBT44_Engineer","SPE_US_Rangers_engineer",
"SPE_US_Rangers_engineer_bangalore","SPE_US_82AB_Engineer","SPE_US_Engineer_late"];
_baseClassExplosivesArray append ["SPE_FR_Engineer","SPE_US_Engineer","SPE_US_101AB_Engineer","SPE_US_HBT44_Engineer","SPE_US_Rangers_engineer",
"SPE_US_Rangers_engineer_bangalore","SPE_US_82AB_Engineer","SPE_US_Engineer_late"];
_baseClassGrenadierArray append ["SPE_FR_Grenadier","SPE_US_Grenadier","SPE_US_101AB_grenadier","SPE_US_HBT44_Grenadier","SPE_US_Rangers_grenadier",
"SPE_US_82AB_grenadier","SPE_US_Grenadier_late"];
_baseClassLATArray append ["SPE_FR_AT_Soldier","SPE_US_AT_Soldier","SPE_US_101AB_AT_soldier","SPE_US_HBT44_AT_Soldier","SPE_US_Rangers_AT_soldier",
"SPE_US_82AB_AT_soldier","SPE_US_AT_Soldier_late"];
_baseClassATArray append ["SPE_FR_AT_Soldier","SPE_US_AT_Soldier","SPE_US_101AB_AT_soldier","SPE_US_HBT44_AT_Soldier","SPE_US_Rangers_AT_soldier",
"SPE_US_82AB_AT_soldier","SPE_US_AT_Soldier_late"];
_baseClassAAArray append ["SPE_US_Rangers_rifleman","SPE_US_82AB_Rifleman_AmmoBearer","SPE_US_82AB_Flamethrower_Operator"];
_baseClassMachineGunnerArray append ["SPE_FR_Autorifleman","SPE_FR_HMGunner","SPE_US_Autorifleman","SPE_US_HMGunner","SPE_US_101AB_Autorifleman","SPE_US_101AB_mgunner",
"SPE_US_HBT44_Autorifleman","SPE_US_HBT44_HMGunner","SPE_US_Rangers_Autorifleman","SPE_US_Rangers_HMGunner","SPE_US_82AB_Autorifleman","SPE_US_82AB_mgunner","SPE_US_Autorifleman_late"
,"SPE_US_HMGunner_late"];
_baseClassMarksmanArray append ["SPE_FR_Sniper","SPE_US_Sniper","SPE_US_101AB_Sniper","SPE_US_HBT44_Sniper","SPE_US_Rangers_sniper","SPE_US_82AB_Sniper","SPE_US_Sniper_late"];
_baseClassSniperArray append ["SPE_FR_Sniper","SPE_US_Sniper","SPE_US_101AB_Sniper","SPE_US_HBT44_Sniper","SPE_US_Rangers_sniper","SPE_US_82AB_Sniper","SPE_US_Sniper_late"];
_baseClassPatrolSniperArray append ["SPE_FR_Sniper","SPE_US_Sniper","SPE_US_101AB_Sniper","SPE_US_HBT44_Sniper","SPE_US_Rangers_sniper","SPE_US_82AB_Sniper","SPE_US_Sniper_late"];
_baseClassPatrolSpotterArray append ["SPE_FR_Sniper","SPE_US_Sniper","SPE_US_101AB_Sniper","SPE_US_HBT44_Sniper","SPE_US_Rangers_sniper","SPE_US_82AB_Sniper","SPE_US_Sniper_late"];
// ================== Специальные роли ==================
_baseClassPoliceArray append ["SPE_FR_Sentry_Carbine"];

_baseClassCrewArray append ["SPE_FR_Tank_Crew","SPE_FR_Tank_Second_Lieutenant","SPE_FR_Tank_Sergeant","SPE_US_HBT44_HalfTrack_Driver","SPE_US_Guncrew",
"SPE_US_Guncrew_Sergeant","SPE_US_Tank_Coverall","SPE_US_Tank_Crew","SPE_US_Tank_Second_Lieutenant","SPE_US_Tank_Sergeant","SPE_US_Tank_Late","SPE_US_Tank_Second_Lieutenant_late","SPE_US_Tank_HBT_Late"];
_baseClassPilotArray append ["SPE_US_Pilot_2","SPEX_US_Pilot_Cap","SPE_US_Pilot_Unequipped"];
_baseClassOfficialArray append ["SPE_US_101AB_CO","SPE_US_82AB_CO"];
_baseClassTraitorArray append ["SPE_FFI_CellLeader","SPE_FFI_Doctor","SPE_FFI_Fighter_G43","SPE_FFI_Fighter_Garand","SPE_FFI_MGunner","SPE_FFI_Sapper_Mle208"];
_baseClassUnarmedArray append ["SPE_US_Pilot_Unequipped"];


/////////////////////
///  Identities   ///
/////////////////////

_voices append ["Male01ENG", "Male02ENG", "Male03ENG", "Male04ENG", "Male05ENG", "Male06ENG", "Male07ENG", "Male08ENG", "Male09ENG", "Male10ENG", 
"Male11ENG", "Male12ENG","SPE_Male01FRE","SPE_Male02FRE"];
_faces append ["LivonianHead_6", "SPE_Arnold", "SPE_boyartsev", "SPE_bykov", "SPE_Connors", "SPE_DAgostino", "SPE_Davidson", "SPE_Elliot", "SPE_Grishka", "SPE_Hauptmann", "SPE_Ivanych", "SPE_Jeppson", "SPE_Klimakov", "SPE_Krueger", "SPE_Kuzmin", "SPE_Neumann", "SPE_Oberst", "SPE_OBrien", "SPE_Seppmeyer", "SPE_Vasiliev", "SPE_Walter", "SPE_Wolf", "Sturrock", "WhiteHead_01", "WhiteHead_02", "WhiteHead_03", "WhiteHead_04", "WhiteHead_05", "WhiteHead_06", "WhiteHead_07", "WhiteHead_08", "WhiteHead_09", "WhiteHead_10", "WhiteHead_11", "WhiteHead_12", "WhiteHead_13", "WhiteHead_14", "WhiteHead_15", "WhiteHead_16", "WhiteHead_17", "WhiteHead_18", "WhiteHead_19", "WhiteHead_20", "WhiteHead_21"];

_insignia append [
	"SPE_101stAB",
	"SPE_11thAD",
	"SPE_1stAD",
	"SPE_1stID",
	"SPE_26thID",
	"SPE_27thID",
	"SPE_29thID",
	"SPE_2ndAD",
	"SPE_2ndArmy",
	"SPE_2ndID",
	"SPE_2ndRanger",
	"SPE_30thID",
	"SPE_30thID_ST",
	"SPE_35thID",
	"SPE_3rdAD",
	"SPE_3rdID",
	"SPE_4thAD",
	"SPE_4thID",
	"SPE_4thID_sqr",
	"SPE_5thID",
	"SPE_6thAD",
	"SPE_7thAD",
	"SPE_7thID",
	"SPE_82dAB",
	"SPE_82dID",
	"SPE_8AF",
	"SPE_90thID",
	"SPE_9AF",
	"SPE_9thID",
	"SPE_AAF",
	"SPE_AAF_Stencil",
	"SPE_USFLAG",
	"SPE_USFLAG_stencil"
];

_M1carbineAttachments = ["","SPE_Carbine_pouch","SPE_Carbine_pouch_od7"];
_M1GarandAttachments = ["","SPE_ACC_M1_Bayo","SPE_ACC_M1905_Bayo","SPE_ACC_GL_M7"];
_SpringfieldAttachments = ["","SPE_ACC_M1_Bayo","SPE_ACC_M1905_Bayo","SPE_ACC_GL_M7"];
_BARAttachments = ["","SPE_M1918A2_BAR_Handle"];
_BARbipods = ["","SPE_M1918A2_BAR_Bipod"];
// Оружие
(_loadoutData get "slRifles") append [
	["SPE_M1903A3_Springfield", "", _SpringfieldAttachments, "",["SPE_5Rnd_762x63","SPE_5Rnd_762x63_M1","SPE_5Rnd_762x63_t","SPE_5Rnd_762x63_M2_AP"], [], ""],
	["SPE_MAS_36", "", "", "",["SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP","SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP"], [], ""],
	["SPE_No3_Mk1_Enfield", "SPE_ACC_M1917_Bayo", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""],
	["SPE_No3_Mk1_Enfield", "", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""],
	["SPE_M1918A0_BAR", "", "", "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], ""],
	["SPE_M1918A2_BAR", "", _BARAttachments, "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], _BARbipods],
	["SPE_M1918A2_erla_BAR", "", _BARAttachments, "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], _BARbipods],
	["SPE_M2_Flamethrower", "", "", "",["SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag"], [], ""],
	["SPE_M1_Garand", "SPE_ACC_GL_M7", "", "", ["SPE_8Rnd_762x63"], ["SPE_1Rnd_G_M9A1","SPE_1Rnd_G_Mk2"], ""]
];
(_loadoutData get "rifles") append [
	["SPE_M1903A3_Springfield", "", _SpringfieldAttachments, "",["SPE_5Rnd_762x63","SPE_5Rnd_762x63_M1","SPE_5Rnd_762x63_t","SPE_5Rnd_762x63_M2_AP"], [], ""],
	["SPE_MAS_36", "", "", "",["SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP","SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP"], [], ""],
	["SPE_No3_Mk1_Enfield", "SPE_ACC_M1917_Bayo", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""],
	["SPE_No3_Mk1_Enfield", "", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""],
	["SPE_M1918A0_BAR", "", "", "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], ""],
	["SPE_M1918A2_BAR", "", _BARAttachments, "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], _BARbipods],
	["SPE_M1918A2_erla_BAR", "", _BARAttachments, "",["SPE_20Rnd_762x63","SPE_20Rnd_762x63_M1","SPE_20Rnd_762x63_M2_AP","SPE_20Rnd_762x63_M2_AP"], [], _BARbipods],
	["SPE_M2_Flamethrower", "", "", "",["SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag","SPE_M2_Flamethrower_Mag"], [], ""]
];
(_loadoutData get "grenadeLaunchers") append [
	["SPE_M1_Garand", "SPE_ACC_GL_M7", "", "", ["SPE_8Rnd_762x63"], ["SPE_1Rnd_G_M9A1","SPE_1Rnd_G_Mk2"], ""]
];
(_loadoutData get "carbines") append [
	["SPE_Fusil_Mle_208_12", "", "", "",["SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug","SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug"], [], ""],
	["SPE_Fusil_Mle_208_12_Sawedoff", "", "", "",["SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug","SPE_2Rnd_12x65_No4_Buck","SPE_2Rnd_12x65_Pellets","SPE_2Rnd_12x65_Slug"], [], ""],
	["SPE_Model_37_Riotgun", "", "", "",["SPE_5Rnd_12x70_No4_Buck","SPE_5Rnd_12x70_Pellets","SPE_5Rnd_12x70_Slug"], [], ""],
	["SPE_Model_37_Riotgun", "SPE_ACC_M1917_Bayo", "", "",["SPE_5Rnd_12x70_No4_Buck","SPE_5Rnd_12x70_Pellets","SPE_5Rnd_12x70_Slug"], [], ""],
	["SPE_Model_37_Riotgun", "", "", "",["SPE_5Rnd_12x70_No4_Buck","SPE_5Rnd_12x70_Pellets","SPE_5Rnd_12x70_Slug"], [], ""],
	["SPE_M1_Carbine", "SPE_ACC_GL_M8", _M1carbineAttachments, "",["SPE_15Rnd_762x33","SPE_15Rnd_762x33_t","SPE_15Rnd_762x33_t"], [], ""],
	["SPE_M1_Carbine", "", _M1carbineAttachments, "",["SPE_15Rnd_762x33","SPE_15Rnd_762x33_t","SPE_15Rnd_762x33_t"], [], ""],
	["SPE_M1A1_Carbine", "", _M1carbineAttachments, "",["SPE_15Rnd_762x33","SPE_15Rnd_762x33_t","SPE_15Rnd_762x33_t"], [], ""]
];
(_loadoutData get "SMGs") append [
	["SPE_M1A1_Thompson", "", "", "",["SPE_30Rnd_Thompson_45ACP","SPE_30Rnd_Thompson_45ACP_t","SPE_20Rnd_Thompson_45ACP","SPE_20Rnd_Thompson_45ACP_t"], [], ""],
	["SPE_M3_GreaseGun", "", "", "",["SPE_30Rnd_M3_GreaseGun_45ACP","SPE_30Rnd_M3_GreaseGun_45ACP_t","SPE_30Rnd_M3_GreaseGun_45ACP","SPE_30Rnd_M3_GreaseGun_45ACP_t"], [], ""],
	["SPE_ACC_M3_Suppressor_45acp", "", "", "",["SPE_30Rnd_M3_GreaseGun_45ACP","SPE_30Rnd_M3_GreaseGun_45ACP_t","SPE_30Rnd_M3_GreaseGun_45ACP","SPE_30Rnd_M3_GreaseGun_45ACP_t"], [], ""],
	["SPE_Sten_Mk2", "", "", "",["SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten"], [], ""],
	["SPE_Sten_Mk2_Suppressed", "", "", "",["SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten","SPE_32Rnd_9x19_Sten"], [], ""]
];
(_loadoutData get "machineGuns") append [
	["SPE_LMG_303_Mk2", "", "", "",["SPE_30Rnd_770x56","SPE_30Rnd_770x56_AP_MKI","SPE_30Rnd_770x56_MKVIII"], [], ""],
	["SPE_FM_24_M29", "", "", "",["SPE_25Rnd_75x54","SPE_25Rnd_75x54_35P_AP","SPE_25Rnd_75x54","SPE_25Rnd_75x54_35P_AP"], [], ""],
	["SPE_M1919A4", "", "", "",["SPE_100Rnd_762x63","SPE_100Rnd_762x63_M1","SPE_100Rnd_762x63_M2_AP","SPE_50Rnd_762x63"], [], ""],
	["SPE_M1919A6", "", "", "",["SPE_100Rnd_762x63","SPE_50Rnd_762x63_M2_AP","SPE_50Rnd_762x63_M1","SPE_50Rnd_762x63"], [], ""]
];
(_loadoutData get "marksmanRifles") append [
	["SPE_M1903A3_Springfield", "", _SpringfieldAttachments, "",["SPE_5Rnd_762x63","SPE_5Rnd_762x63_M1","SPE_5Rnd_762x63_t","SPE_5Rnd_762x63_M2_AP"], [], ""],
	["SPE_MAS_36", "", "", "",["SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP","SPE_5Rnd_75x54","SPE_5Rnd_75x54_35P_AP"], [], ""],
	["SPE_No3_Mk1_Enfield", "SPE_ACC_M1917_Bayo", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""],
	["SPE_No3_Mk1_Enfield", "", "", "",["SPE_5Rnd_770x56","SPE_5Rnd_770x56_AP_MKI","SPE_5Rnd_770x56_MKVIII","SPE_5Rnd_770x56_MKVIII"], [], ""]
];
(_loadoutData get "sniperRifles") append [
	["SPE_M1903A4_Springfield", "", "", "",["SPE_5Rnd_762x63","SPE_5Rnd_762x63_M1","SPE_5Rnd_762x63_t","SPE_5Rnd_762x63_M2_AP"], [], ""]
];

// Пусковые установки
(_loadoutData get "lightATLaunchers") append [
["SPE_M1A1_Bazooka", "", "", "",["SPE_1Rnd_60mm_M6"], [], ""]
];
(_loadoutData get "ATLaunchers") append [
["SPE_M9_Bazooka", "", "", "",["SPE_1Rnd_60mm_M6A3"], [], ""],
["SPE_M9A1_Bazooka", "", "", "",["SPE_1Rnd_60mm_M6A3"], [], ""]
];
(_loadoutData get "sidearms") append [
	["SPE_M1911", "", "", "",["SPE_7Rnd_45ACP_1911","SPE_7Rnd_45ACP_1911"], [], ""]
];

// Взрывчатка
(_loadoutData get "ATMines") append ["SPE_US_M1A1_ATMINE_mag"];
(_loadoutData get "APMines") append ["SPE_US_M3_Pressure_MINE_mag"];
(_loadoutData get "lightExplosives") append ["SPE_US_TNT_half_pound_mag"];
(_loadoutData get "heavyExplosives") append ["SPE_US_TNT_4pound_mag"];

// Гранаты
(_loadoutData get "antiInfantryGrenades") append ["SPE_US_Mk_2","SPE_US_AN_M14"];
(_loadoutData get "smokeGrenades") append ["SmokeShell"];
(_loadoutData get "signalsmokeGrenades") append ["SmokeShellYellow", "SmokeShellRed", "SmokeShellPurple", "SmokeShellOrange", "SmokeShellGreen", "SmokeShellBlue"];

// Базовое снаряжение
(_loadoutData get "maps") append ["ItemMap"];
(_loadoutData get "watches") append ["SPE_US_ItemWatch"];
(_loadoutData get "compasses") append ["SPE_US_ItemCompass"];
(_loadoutData get "radios") append ["TFAR_SCR536"];
(_loadoutData get "NVGs") append ["SPE_US_FL_TL122"];
(_loadoutData get "binoculars") append ["SPE_Binocular_US"];
(_loadoutData get "rangefinders") append ["SPE_Binocular_US"];

// Предательская экипировка
(_loadoutData get "traitorUniforms") append [
	"U_SPE_FFI_Casual_1",
	"U_SPE_FFI_Casual_1_trop",
	"U_SPE_FFI_Casual_2",
	"U_SPE_FFI_Casual_2_trop",
	"U_SPE_FFI_Casual_3",
	"U_SPE_FFI_Casual_3_trop",
	"U_SPE_FFI_Casual_4",
	"U_SPE_FFI_Casual_4_trop",
	"U_SPE_FFI_Casual_5",
	"U_SPE_FFI_Casual_5_trop",
	"U_SPE_FFI_Casual_6",
	"U_SPE_FFI_Casual_6_trop",
	"U_SPE_FFI_Casual_7",
	"U_SPE_FFI_Casual_7_trop",
	"U_SPE_FFI_Jacket_zwart",
	"U_SPE_FFI_Jacket_zwart_Alt",
	"U_SPE_FFI_Jacket_zwart_swetr",
	"U_SPE_FFI_Jacket_bruin",
	"U_SPE_FFI_Jacket_bruin_swetr",
	"U_SPE_FFI_Jacket_grijs",
	"U_SPE_FFI_Jacket_grijs_swetr",
	"U_SPE_FFI_Worker_1",
	"U_SPE_FFI_Worker_1_trop",
	"U_SPE_FFI_Worker_2",
	"U_SPE_FFI_Worker_2_trop",
	"U_SPE_FFI_Worker_3",
	"U_SPE_FFI_Worker_3_trop",
	"U_SPE_FFI_Worker_4",
	"U_SPE_FFI_Worker_4_trop"
];
(_loadoutData get "traitorVests") append [
	"V_SPE_FFI_Vest_SMG_pouch",
	"V_SPE_FFI_Vest_SMG_frag",
	"V_SPE_FFI_Vest_SMG",
	"V_SPE_FFI_Vest_rifle_pouch",
	"V_SPE_FFI_Vest_rifle_frag",
	"V_SPE_FFI_Vest_rifle",
	"V_SPE_FFI_Vest_Pouch_frag",
	"V_SPE_FFI_Vest_Pouch"
];
(_loadoutData get "traitorHats") append [
	"H_SPE_CIV_Worker_Cap_1",
	"H_SPE_CIV_Worker_Cap_2",
	"H_SPE_CIV_Worker_Cap_3",
	"H_SPE_CIV_Fedora_Cap_3",
	"H_SPE_CIV_Fedora_Cap_4",
	"H_SPE_CIV_Fedora_Cap_2",
	"H_SPE_CIV_Fedora_Cap_1",
	"H_SPE_CIV_Fedora_Cap_6",
	"H_SPE_CIV_Fedora_Cap_5"
];

// Офицерская экипировка
(_loadoutData get "officerUniforms") append [
	"U_SPE_US_CC_CPT"
];
(_loadoutData get "officerVests") append [
	"V_SPE_US_Vest_OD7_45_off",
	"V_SPE_US_Vest_OD7_45_high_off",
	"V_SPE_US_Vest_OD7_Thompson_nco",
	"V_SPE_US_Vest_OD7_Thompson_nco_Radio",
	"V_SPE_US_Vest_Carbine_nco",
	"V_SPE_US_Vest_Carbine_nco_Radio",
	"V_SPE_US_Vest_Thompson_nco",
	"V_SPE_US_Vest_Thompson_nco_Radio",
	"V_SPE_US_Vest_OD7_Carbine_nco",
	"V_SPE_US_Vest_OD7_Carbine_nco_Radio",
	"V_SPE_US_Vest_Carbine_jfak_nco",
	"V_SPE_US_Vest_OD7_Carbine_jfak_nco",
	"V_SPE_US_Vest_AB_padded_nco",
	"V_SPE_US_Vest_AB_late_nco",
	"V_SPE_US_Vest_AB_padded_Garand_nco",
	"V_SPE_US_Vest_45_off",
	"V_SPE_US_Vest_45_high_off",
	"V_SPE_US_Vest_OD7_45_jfak_off_m43",
	"V_SPE_US_Vest_OD7_45_jfak_off",
	"V_SPE_US_Vest_45_jfak_off_m43",
	"V_SPE_US_Vest_45_jfak_off"
];
(_loadoutData get "officerHats") append [
	"H_SPE_US_Pilot_Cap",
	"H_SPE_US_Pilot_Cap_Khaki"
];

// Специальная экипировка
(_loadoutData get "cloakVests") append [
	"V_SPE_US_Vest_AB_Garand_eng",
	"V_SPE_US_Vest_AB_Garand_45",
	"V_SPE_US_Vest_AB_Grenadier",
	"V_SPE_US_Vest_AB_early_45",
	"V_SPE_US_Vest_AB_early_thompson_45_bag",
	"V_SPE_US_Vest_AB_late_45",
	"V_SPE_US_Vest_AB_late_thompson_45",
	"V_SPE_US_Vest_AB_late_45_map",
	"V_SPE_US_Vest_AB_late_thompson_45_map",
	"V_SPE_US_Vest_AB_early_45_map",
	"V_SPE_US_Vest_AB_early_thompson_45",
	"V_SPE_US_Vest_AB_padded_45",
	"V_SPE_US_Vest_AB_padded_thompson_45",
	"V_SPE_US_Vest_AB_padded_45_map",
	"V_SPE_US_Vest_AB_padded_thompson_45_map",
	"V_SPE_US_Vest_AB_padded_Garand",
	"V_SPE_US_Vest_AB_padded_Garand_nco",
	"V_SPE_US_Vest_AB_padded_Garand_eng",
	"V_SPE_US_Vest_AB_padded_Garand_45",
	"V_SPE_US_Vest_AB_padded_Grenadier",
	"V_SPE_US_Vest_AB_padded_2",
	"V_SPE_US_Vest_AB_padded_nco",
	"V_SPE_US_Vest_AB_padded_eng",
	"V_SPE_US_Vest_AB_padded_M1919",
	"V_SPE_US_Vest_AB_padded_mk2",
	"V_SPE_US_Vest_AB_padded_1",
	"V_SPE_US_Vest_AB_padded_thompson",
	"V_SPE_US_Vest_AB_early_2",
	"V_SPE_US_Vest_AB_early_eng",
	"V_SPE_US_Vest_AB_late_nco",
	"V_SPE_US_Vest_AB_late_M1919",
	"V_SPE_US_Vest_AB_late_mk2",
	"V_SPE_US_Vest_AB_late_1",
	"V_SPE_US_Vest_AB_late_thompson",
	"V_SPE_US_Vest_AB_early_mk2",
	"V_SPE_US_Vest_AB_early_1",
	"V_SPE_US_Vest_AB_early_thompson"
];

// Основная экипировка
(_loadoutData get "uniforms") append [
	"U_SPE_US_AB_Uniform_M43",
	"U_SPE_US_AB_Uniform_M43_knife",
	"U_SPE_US_AB_Uniform_M43_Medic",
	"U_SPE_US_AB_Uniform_M43_flag",
	"U_SPE_US_AB_Uniform_M43_flag_knife",
	"U_SPE_US_AB_Uniform_M43_flag_Medic",
	"U_SPE_US_AB_Uniform_M43_flag_arm",
	"U_SPE_US_AB_Uniform_M43_flag_arm_knife",
	"U_SPE_US_AB_Uniform_M43_flag_arm_Medic",
	"U_SPE_US_AB_Uniform_M42",
	"U_SPE_US_AB_Uniform_M42_glove",
	"U_SPE_US_AB_Uniform_M42_Medic",
	"U_SPE_US_AB_Uniform_M42_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_roll",
	"U_SPE_US_AB_Uniform_M42_camo",
	"U_SPE_US_AB_Uniform_M42_camo_glove",
	"U_SPE_US_AB_Uniform_M42_camo_Medic",
	"U_SPE_US_AB_Uniform_M42_camo_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_camo_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_camo_roll",
	"U_SPE_US_AB_Uniform_M42_camo_flag",
	"U_SPE_US_AB_Uniform_M42_camo_flag_glove",
	"U_SPE_US_AB_Uniform_M42_camo_flag_Medic",
	"U_SPE_US_AB_Uniform_M42_camo_flag_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_camo_flag_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_camo_flag_roll",
	"U_SPE_US_AB_Uniform_M42_padded_CC2",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_glove",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_Medic",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove_pfak",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_506_pfak",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_roll",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_roll_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_knife",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll",
	"U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll_knife",
	"U_SPE_US_AB_Uniform_M42_flag",
	"U_SPE_US_AB_Uniform_M42_flag_glove",
	"U_SPE_US_AB_Uniform_M42_flag_Medic",
	"U_SPE_US_AB_Uniform_M42_flag_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_flag_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_flag_roll",
	"U_SPE_US_AB_Uniform_M42_flag_arm",
	"U_SPE_US_AB_Uniform_M42_flag_arm_glove",
	"U_SPE_US_AB_Uniform_M42_flag_arm_Medic",
	"U_SPE_US_AB_Uniform_M42_flag_arm_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_flag_arm_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_flag_arm_roll",
	"U_SPE_US_AB_Uniform_M42_padded_gas",
	"U_SPE_US_AB_Uniform_M42_padded_gas_glove",
	"U_SPE_US_AB_Uniform_M42_padded_gas_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_gas_knife",
	"U_SPE_US_AB_Uniform_M42_padded_gas_Medic",
	"U_SPE_US_AB_Uniform_M42_padded_gas_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_padded_gas_506",
	"U_SPE_US_AB_Uniform_M42_padded_gas_506_glove",
	"U_SPE_US_AB_Uniform_M42_padded_gas_506_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_gas_506_knife",
	"U_SPE_US_AB_Uniform_M42_padded",
	"U_SPE_US_AB_Uniform_M42_padded_glove",
	"U_SPE_US_AB_Uniform_M42_padded_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_knife",
	"U_SPE_US_AB_Uniform_M42_padded_Medic",
	"U_SPE_US_AB_Uniform_M42_padded_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_padded_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_padded_506",
	"U_SPE_US_AB_Uniform_M42_padded_506_glove",
	"U_SPE_US_AB_Uniform_M42_padded_506_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_506_glove_pfak",
	"U_SPE_US_AB_Uniform_M42_padded_506_knife",
	"U_SPE_US_AB_Uniform_M42_padded_roll",
	"U_SPE_US_AB_Uniform_M42_padded_roll_knife",
	"U_SPE_US_AB_Uniform_M42_padded_flag",
	"U_SPE_US_AB_Uniform_M42_padded_flag_glove",
	"U_SPE_US_AB_Uniform_M42_padded_flag_glove_knife",
	"U_SPE_US_AB_Uniform_M42_padded_flag_knife",
	"U_SPE_US_AB_Uniform_M42_padded_flag_Medic",
	"U_SPE_US_AB_Uniform_M42_padded_flag_Medic_glove",
	"U_SPE_US_AB_Uniform_M42_padded_flag_Medic_roll",
	"U_SPE_US_AB_Uniform_M42_padded_flag_roll",
	"U_SPE_US_AB_Uniform_M42_padded_flag_roll_knife",
	"U_SPE_US_Rangers_Uniform",
	"U_SPE_US_Rangers_Corp",
	"U_SPE_US_Rangers_Med",
	"U_SPE_US_Rangers_Private_1st",
	"U_SPE_US_Rangers_Sergeant",
	"U_SPE_US_Rangers_Technician",
	"U_SPE_US_Rangers_late",
	"U_SPE_US_Private",
	"U_SPE_US_Corp",
	"U_SPE_US_Med",
	"U_SPE_US_Private_1st",
	"U_SPE_US_Sergeant",
	"U_SPE_US_Technician",
	"U_SPE_US_Private_late",
	"U_SPE_US_Med_late",
	"U_SPE_US_Private_trop",
	"U_SPE_US_HBT44_FrogSkin_Jungle",
	"U_SPE_US_HBT44_FrogSkin_Jungle_roll",
	"U_SPE_US_HBT44_tuck_FrogSkin_Jungle",
	"U_SPE_US_HBT44_tuck_FrogSkin_Jungle_roll",
	"U_SPE_US_HBT44_tuck_FrogSkin_Jungle_Half",
	"U_SPE_US_HBT44_FrogSkin_Jungle_trop",
	"U_SPE_US_HBT44_FrogSkin_Jungle_Half",
	"U_SPE_US_HBT44_Med",
	"U_SPE_US_HBT44",
	"U_SPE_US_HBT44_roll",
	"U_SPE_US_HBT44_tuck",
	"U_SPE_US_HBT44_tuck_Med",
	"U_SPE_US_HBT44_tuck_roll",
	"U_SPE_US_HBT44_tuck_Half",
	"U_SPE_US_HBT44_trop",
	"U_SPE_US_HBT44_Half",
	"U_SPE_US_HBT44_late",
	"U_SPE_US_HBT44_late_roll",
	"U_SPE_US_HBT44_tuck_late",
	"U_SPE_US_HBT44_tuck_late_roll",
	"U_SPE_US_HBT44_tuck_Half_late",
	"U_SPE_US_M43",
	"U_SPE_US_M43_legging",
	"U_SPE_US_M43_trop",
	"U_SPE_US_M43_hbt",
	"U_SPE_US_M43_hbt_legging",
	"U_SPE_US_M43_hbt_trop",
	"U_SPE_US_SC_EM",
	"U_SPE_US_SC_EM_tie",
	"U_SPE_US_SC_EM_roll",
	"U_SPE_US_CC_HBT_camo",
	"U_SPE_US_CC_HBT_camo_roll",
	"U_SPE_US_CC_HBT_camo_trop",
	"U_SPE_US_CC_HBT_camo_trop_roll",
	"U_SPE_US_CC_HBT_EM",
	"U_SPE_US_CC_HBT_EM_roll",
	"U_SPE_US_CC_HBT_EM_trop",
	"U_SPE_US_CC_HBT_EM_trop_roll",
	"U_SPE_US_CC_EM",
	"U_SPE_US_CC_EM_roll",
	"U_SPE_US_CC_EM_trop",
	"U_SPE_US_CC_EM_trop_roll",
	"U_SPE_US_CC_EM_late",
	"U_SPE_US_CC_EM_late_roll"
];
(_loadoutData get "slUniforms") append [
	"U_SPE_US_CC_1LT",
	"U_SPE_US_CC_2LT"
];
(_loadoutData get "vests") append [
	"V_SPE_US_Vest_AB_Garand",
	"V_SPE_US_Vest_AB_Garand_nco",
	"V_SPE_US_Vest_AB_Garand_eng",
	"V_SPE_US_Vest_AB_Garand_45",
	"V_SPE_US_Vest_AB_Grenadier",
	"V_SPE_US_Vest_AB_early_45",
	"V_SPE_US_Vest_AB_early_thompson_45_bag",
	"V_SPE_US_Vest_AB_late_45",
	"V_SPE_US_Vest_AB_late_thompson_45",
	"V_SPE_US_Vest_AB_late_45_map",
	"V_SPE_US_Vest_AB_late_thompson_45_map",
	"V_SPE_US_Vest_AB_early_45_map",
	"V_SPE_US_Vest_AB_early_thompson_45",
	"V_SPE_US_Vest_AB_padded_45",
	"V_SPE_US_Vest_AB_padded_thompson_45",
	"V_SPE_US_Vest_AB_padded_45_map",
	"V_SPE_US_Vest_AB_padded_thompson_45_map",
	"V_SPE_US_Vest_AB_padded_Garand",
	"V_SPE_US_Vest_AB_padded_Garand_eng",
	"V_SPE_US_Vest_AB_padded_Garand_45",
	"V_SPE_US_Vest_AB_padded_Grenadier",
	"V_SPE_US_Vest_AB_padded_2",
	"V_SPE_US_Vest_AB_padded_eng",
	"V_SPE_US_Vest_AB_padded_M1919",
	"V_SPE_US_Vest_AB_padded_mk2",
	"V_SPE_US_Vest_AB_padded_1",
	"V_SPE_US_Vest_AB_padded_thompson",
	"V_SPE_US_Vest_AB_early_2",
	"V_SPE_US_Vest_AB_early_eng",
	"V_SPE_US_Vest_AB_late_M1919",
	"V_SPE_US_Vest_AB_late_mk2",
	"V_SPE_US_Vest_AB_late_1",
	"V_SPE_US_Vest_AB_late_thompson",
	"V_SPE_US_Vest_AB_early_mk2",
	"V_SPE_US_Vest_AB_early_1",
	"V_SPE_US_Vest_AB_early_thompson",
	"V_SPE_US_LifeVest",
	"V_SPE_US_Vest_OD7_Bar_assist",
	"V_SPE_US_Vest_OD7_Bar",
	"V_SPE_US_Vest_OD7_Bar_M43",
	"V_SPE_US_Vest_Bar_assist",
	"V_SPE_US_Vest_Bar",
	"V_SPE_US_Vest_Bar_M43",
	"V_SPE_US_Vest_OD7_Garand",
	"V_SPE_US_Vest_OD7_Garand_eng",
	"V_SPE_US_Vest_OD7_Garand_M43",
	"V_SPE_US_Vest_OD7_Garand_map",
	"V_SPE_US_Vest_OD7_Garand_mk2",
	"V_SPE_US_Vest_OD7_Garand_45",
	"V_SPE_US_Vest_OD7_Grenadier",
	"V_SPE_US_Vest_Garand",
	"V_SPE_US_Vest_Garand_eng",
	"V_SPE_US_Vest_Garand_M43",
	"V_SPE_US_Vest_Garand_map",
	"V_SPE_US_Vest_Garand_mk2",
	"V_SPE_US_Vest_Garand_45",
	"V_SPE_US_Vest_Grenadier",
	"V_SPE_US_Vest_OD7_Bar_jfak_assist",
	"V_SPE_US_Vest_OD7_Bar_jfak",
	"V_SPE_US_Vest_Bar_jfak_assist",
	"V_SPE_US_Vest_Bar_jfak",
	"V_SPE_US_Vest_OD7_Garand_jfak",
	"V_SPE_US_Vest_OD7_Garand_jfak_knife",
	"V_SPE_US_Vest_OD7_Garand_jfak_eng",
	"V_SPE_US_Vest_OD7_Garand_jfak_M43",
	"V_SPE_US_Vest_OD7_Garand_jfak_45",
	"V_SPE_US_Vest_Garand_jfak",
	"V_SPE_US_Vest_Garand_jfak_knife",
	"V_SPE_US_Vest_Garand_jfak_eng",
	"V_SPE_US_Vest_Garand_jfak_M43",
	"V_SPE_US_Vest_Garand_jfak_45",
	"V_SPE_US_Vest_OD7_Carbine_jfak",
	"V_SPE_US_Vest_OD7_Carbine_jfak_mk2",
	"V_SPE_US_Vest_OD7_Carbine_jfak_eng",
	"V_SPE_US_Vest_OD7_M1919_jfak",
	"V_SPE_US_Vest_OD7_Carbine_jfak_m43",
	"V_SPE_US_Vest_OD7_45_jfak",
	"V_SPE_US_Vest_OD7_Thompson_jfak",
	"V_SPE_US_Vest_OD7_Thompson_jfak_M43",
	"V_SPE_US_Vest_Carbine_jfak",
	"V_SPE_US_Vest_Carbine_jfak_mk2",
	"V_SPE_US_Vest_Carbine_jfak_eng",
	"V_SPE_US_Vest_M1919_jfak",
	"V_SPE_US_Vest_Carbine_jfak_m43",
	"V_SPE_US_Vest_45_jfak",
	"V_SPE_US_Vest_Thompson_jfak",
	"V_SPE_US_Vest_Thompson_jfak_M43",
	"V_SPE_US_Vest_OD7_Carbine",
	"V_SPE_US_Vest_OD7_Carbine_mk2",
	"V_SPE_US_Vest_OD7_Carbine_eng",
	"V_SPE_US_Vest_OD7_M1919",
	"V_SPE_US_Vest_OD7_Carbine_m43",
	"V_SPE_US_Vest_OD7_Carbine_pick",
	"V_SPE_US_Vest_OD7_45",
	"V_SPE_US_Vest_OD7_45_high",
	"V_SPE_US_Vest_OD7_Thompson",
	"V_SPE_US_Vest_OD7_Thompson_M43",
	"V_SPE_US_Vest_Carbine",
	"V_SPE_US_Vest_Carbine_mk2",
	"V_SPE_US_Vest_Carbine_eng",
	"V_SPE_US_Vest_M1919",
	"V_SPE_US_Vest_Carbine_m43",
	"V_SPE_US_Vest_Carbine_pick",
	"V_SPE_US_Vest_45",
	"V_SPE_US_Vest_45_high",
	"V_SPE_US_Vest_Thompson",
	"V_SPE_US_Vest_Thompson_M43"
];
(_loadoutData get "Hvests") append [
	"V_SPE_US_Vest_AB_Garand_gp",
	"V_SPE_US_Vest_AB_Garand_medic",
	"V_SPE_US_Vest_AB_early_medic",
	"V_SPE_US_Vest_AB_late_medic",
	"V_SPE_US_Vest_AB_late_thompson_45_gp",
	"V_SPE_US_Vest_AB_padded_Garand_medic",
	"V_SPE_US_Vest_AB_padded_medic",
	"V_SPE_US_Vest_AB_padded_thompson_45_gp",
	"V_SPE_US_Vest_AB_padded_Garand_gp",
	"V_SPE_US_Vest_AB_late_2",
	"V_SPE_US_Assault_Vest",
	"V_SPE_US_Assault_Vest_Bag",
	"V_SPE_US_Assault_Vest_dday",
	"V_SPE_US_Assault_Vest_dday_Bag",
	"V_SPE_US_Assault_Vest_dday_eng",
	"V_SPE_US_Assault_Vest_dday_rifle_M43",
	"V_SPE_US_Assault_Vest_dday_rifle",
	"V_SPE_US_Assault_Vest_Light",
	"V_SPE_US_Assault_Vest_eng",
	"V_SPE_US_Assault_Vest_alt",
	"V_SPE_US_Assault_Vest_rifle",
	"V_SPE_US_Assault_Vest_rifle_M43",
	"V_SPE_US_Vest_OD7_Garand_gp",
	"V_SPE_US_Vest_OD7_Garand_M43_gp",
	"V_SPE_US_Vest_Garand_gp",
	"V_SPE_US_Vest_Garand_M43_gp",
	"V_SPE_US_Vest_OD7_Garand_jfak_gp",
	"V_SPE_US_Vest_Garand_jfak_gp",
	"V_SPE_US_Vest_Medic_jfak",
	"V_SPE_US_Vest_OD7_Asst_MG_jfak",
	"V_SPE_US_Vest_Asst_MG_jfak",
	"V_SPE_US_Vest_Medic3",
	"V_SPE_US_Vest_Medic",
	"V_SPE_US_Vest_Medic2",
	"V_SPE_US_Vest_OD7_Asst_MG",
	"V_SPE_US_Vest_Asst_MG"
];
(_loadoutData get "sniVests") append [
	"V_SPE_US_Vest_AB_Garand_eng",
	"V_SPE_US_Vest_AB_Garand_45",
	"V_SPE_US_Vest_AB_Grenadier",
	"V_SPE_US_Vest_AB_early_45",
	"V_SPE_US_Vest_AB_early_thompson_45_bag",
	"V_SPE_US_Vest_AB_late_45",
	"V_SPE_US_Vest_AB_late_thompson_45",
	"V_SPE_US_Vest_AB_late_45_map",
	"V_SPE_US_Vest_AB_late_thompson_45_map",
	"V_SPE_US_Vest_AB_early_45_map",
	"V_SPE_US_Vest_AB_early_thompson_45",
	"V_SPE_US_Vest_AB_padded_45",
	"V_SPE_US_Vest_AB_padded_thompson_45",
	"V_SPE_US_Vest_AB_padded_45_map",
	"V_SPE_US_Vest_AB_padded_thompson_45_map",
	"V_SPE_US_Vest_AB_padded_Garand",
	"V_SPE_US_Vest_AB_padded_Garand_nco",
	"V_SPE_US_Vest_AB_padded_Garand_eng",
	"V_SPE_US_Vest_AB_padded_Garand_45",
	"V_SPE_US_Vest_AB_padded_Grenadier",
	"V_SPE_US_Vest_AB_padded_2",
	"V_SPE_US_Vest_AB_padded_nco",
	"V_SPE_US_Vest_AB_padded_eng",
	"V_SPE_US_Vest_AB_padded_M1919",
	"V_SPE_US_Vest_AB_padded_mk2",
	"V_SPE_US_Vest_AB_padded_1",
	"V_SPE_US_Vest_AB_padded_thompson",
	"V_SPE_US_Vest_AB_early_2",
	"V_SPE_US_Vest_AB_early_eng",
	"V_SPE_US_Vest_AB_late_nco",
	"V_SPE_US_Vest_AB_late_M1919",
	"V_SPE_US_Vest_AB_late_mk2",
	"V_SPE_US_Vest_AB_late_1",
	"V_SPE_US_Vest_AB_late_thompson",
	"V_SPE_US_Vest_AB_early_mk2",
	"V_SPE_US_Vest_AB_early_1",
	"V_SPE_US_Vest_AB_early_thompson"
];
(_loadoutData get "backpacks") append [
	"B_SPE_US_GP_Bag",
	"B_SPE_US_Bandoleer_2",
	"B_SPE_US_Bandoleer",
	"B_SPE_US_Bandoleer_3",
	"B_SPE_US_M2Flamethrower",
	"B_SPE_US_Backpack",
	"B_SPE_US_Backpack_Bandoleer",
	"B_SPE_US_Backpack_roll",
	"B_SPE_US_Backpack_M7_side",
	"B_SPE_US_Backpack_M7_side_bandoleer",
	"B_SPE_US_Backpack_M7_rear",
	"B_SPE_US_Backpack_M7_rear_bandoleer",
	"B_SPE_US_Backpack_dday",
	"B_SPE_US_Backpack_dday_4ID",
	"B_SPE_US_Backpack_dday_side",
	"B_SPE_US_Backpack_dday_m43",
	"B_SPE_US_Backpack_dday_eng",
	"B_SPE_US_Backpack_M43",
	"B_SPE_US_Backpack_M6",
	"B_SPE_US_Backpack_M6_M43",
	"B_SPE_US_Backpack_pick",
	"B_SPE_US_Backpack_Mk2",
	"B_SPE_US_MGbag",
	"B_SPE_US_Suspender",
	"B_SPE_US_Suspender_RocketBag",
	"B_SPE_US_Suspender_band",
	"B_SPE_US_Suspender_band_left",
	"B_SPE_US_Suspender_m43",
	"B_SPE_US_Suspender_m43_open",
	"B_SPE_US_Suspender_band_right"
];
(_loadoutData get "longRangeRadios") append [
	"B_SPE_US_Radio_packboard",
	"B_SPE_US_Radio_packboard_light",
	"B_SPE_US_Radio",
	"B_SPE_US_Radio_alt"
];
(_loadoutData get "atBackpacks") append [
	"B_SPE_US_RocketBag_Empty",
	"B_SPE_US_M36",
	"B_SPE_US_M36_Bandoleer_duplet",
	"B_SPE_US_M36_Bandoleer",
	"B_SPE_US_M36_Bandoleer_mk2",
	"B_SPE_US_M36_roll",
	"B_SPE_US_M36_roll_2",
	"B_SPE_US_M36_m7",
	"B_SPE_US_M36_m7_Bandoleer",
	"B_SPE_US_M36_m6",
	"B_SPE_US_M36_m6_Bandoleer",
	"B_SPE_US_M36_landing_m7",
	"B_SPE_US_M36_landing_m6",
	"B_SPE_US_M36_Rocketbag",
	"B_SPE_US_M36_Rope",
	"B_SPE_US_M2Flamethrower",
	"B_SPE_US_Backpack_roll_gp",
	"B_SPE_US_Backpack_M43_Bandoleer",
	"B_SPE_US_Backpack_M43_GP",
	"B_SPE_US_Backpack_RocketBag_Empty",
	"B_SPE_US_packboard_ammo",
	"B_SPE_US_packboard_eng",
	"B_SPE_US_packboard_mortar"
];
(_loadoutData get "helmets") append [
	"H_SPE_US_AB_Helmet",
	"H_SPE_US_AB_Helmet_CO",
	"H_SPE_US_AB_Helmet_CO_ns",
	"H_SPE_US_AB_Helmet_ns",
	"H_SPE_US_AB_Helmet_NCO",
	"H_SPE_US_AB_Helmet_NCO_ns",
	"H_SPE_US_AB_Helmet_Net",
	"H_SPE_US_AB_Helmet_CO_Net",
	"H_SPE_US_AB_Helmet_CO_Net_ns",
	"H_SPE_US_AB_Helmet_Net_ns",
	"H_SPE_US_AB_Helmet_Net_up",
	"H_SPE_US_AB_Helmet_NCO_Net",
	"H_SPE_US_AB_Helmet_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_Net_os",
	"H_SPE_US_AB_Helmet_polar",
	"H_SPE_US_AB_Helmet_polar_ns",
	"H_SPE_US_AB_Helmet_polar_net",
	"H_SPE_US_AB_Helmet_polar_net_ns",
	"H_SPE_US_AB_Helmet_polar_net_os",
	"H_SPE_US_AB_Helmet_polar_os",
	"H_SPE_US_AB_Helmet_polar_Scrim",
	"H_SPE_US_AB_Helmet_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_os",
	"H_SPE_US_AB_Helmet_Scrim",
	"H_SPE_US_AB_Helmet_CO_Scrim",
	"H_SPE_US_AB_Helmet_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_up",
	"H_SPE_US_AB_Helmet_NCO_Scrim",
	"H_SPE_US_AB_Helmet_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_os",
	"H_SPE_US_AB_Helmet_501",
	"H_SPE_US_AB_Helmet_501_CO",
	"H_SPE_US_AB_Helmet_501_CO_ns",
	"H_SPE_US_AB_Helmet_501_ns",
	"H_SPE_US_AB_Helmet_501_NCO",
	"H_SPE_US_AB_Helmet_501_NCO_ns",
	"H_SPE_US_AB_Helmet_501_Net",
	"H_SPE_US_AB_Helmet_501_CO_Net",
	"H_SPE_US_AB_Helmet_501_CO_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_up",
	"H_SPE_US_AB_Helmet_501_NCO_Net",
	"H_SPE_US_AB_Helmet_501_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_os",
	"H_SPE_US_AB_Helmet_501_polar",
	"H_SPE_US_AB_Helmet_501_polar_ns",
	"H_SPE_US_AB_Helmet_501_polar_net",
	"H_SPE_US_AB_Helmet_501_polar_net_ns",
	"H_SPE_US_AB_Helmet_501_polar_net_os",
	"H_SPE_US_AB_Helmet_501_polar_os",
	"H_SPE_US_AB_Helmet_501_polar_Scrim",
	"H_SPE_US_AB_Helmet_501_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_501_os",
	"H_SPE_US_AB_Helmet_501_Scrim",
	"H_SPE_US_AB_Helmet_501_CO_Scrim",
	"H_SPE_US_AB_Helmet_501_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_up",
	"H_SPE_US_AB_Helmet_501_NCO_Scrim",
	"H_SPE_US_AB_Helmet_501_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_os",
	"H_SPE_US_AB_Helmet_502",
	"H_SPE_US_AB_Helmet_502_CO",
	"H_SPE_US_AB_Helmet_502_CO_ns",
	"H_SPE_US_AB_Helmet_502_ns",
	"H_SPE_US_AB_Helmet_502_NCO",
	"H_SPE_US_AB_Helmet_502_NCO_ns",
	"H_SPE_US_AB_Helmet_502_Net",
	"H_SPE_US_AB_Helmet_502_CO_Net",
	"H_SPE_US_AB_Helmet_502_CO_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_up",
	"H_SPE_US_AB_Helmet_502_NCO_Net",
	"H_SPE_US_AB_Helmet_502_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_os",
	"H_SPE_US_AB_Helmet_502_polar",
	"H_SPE_US_AB_Helmet_502_polar_ns",
	"H_SPE_US_AB_Helmet_502_polar_net",
	"H_SPE_US_AB_Helmet_502_polar_net_ns",
	"H_SPE_US_AB_Helmet_502_polar_net_os",
	"H_SPE_US_AB_Helmet_502_polar_os",
	"H_SPE_US_AB_Helmet_502_polar_Scrim",
	"H_SPE_US_AB_Helmet_502_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_502_os",
	"H_SPE_US_AB_Helmet_502_Scrim",
	"H_SPE_US_AB_Helmet_502_CO_Scrim",
	"H_SPE_US_AB_Helmet_502_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_up",
	"H_SPE_US_AB_Helmet_502_NCO_Scrim",
	"H_SPE_US_AB_Helmet_502_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_os",
	"H_SPE_US_HBT_cap",
	"H_SPE_US_HBT_cap_up",
	"H_SPE_US_HBT_cap_polar",
	"H_SPE_US_HBT_cap_rear",
	"H_SPE_US_jeep_cap",
	"H_SPE_US_jeep_cap_polar",
	"H_SPE_US_jeep_cap_rear",
	"H_SPE_US_Helmet",
	"H_SPE_US_Helmet_29ID",
	"H_SPE_US_Helmet_29ID_CO",
	"H_SPE_US_Helmet_29ID_ns",
	"H_SPE_US_Helmet_29ID_NCO",
	"H_SPE_US_Helmet_29ID_Net",
	"H_SPE_US_Helmet_29ID_Net_ns",
	"H_SPE_US_Helmet_29ID_Net_os",
	"H_SPE_US_Helmet_29ID_os",
	"H_SPE_US_Helmet_29ID_Scrim",
	"H_SPE_US_Helmet_29ID_Scrim_ns",
	"H_SPE_US_Helmet_29ID_Scrim_os",
	"H_SPE_US_Rangers_Helmet",
	"H_SPE_US_Rangers_Helmet_Cap",
	"H_SPE_US_Rangers_Helmet_ns",
	"H_SPE_US_Rangers_Helmet_NCO",
	"H_SPE_US_Rangers_Helmet_os",
	"H_SPE_US_Helmet_band",
	"H_SPE_US_Helmet_band_ns",
	"H_SPE_US_Helmet_band_up",
	"H_SPE_US_Helmet_band_os",
	"H_SPE_US_Helmet_Cap",
	"H_SPE_US_Helmet_CO",
	"H_SPE_US_Helmet_cover",
	"H_SPE_US_Helmet_cover_ns",
	"H_SPE_US_Helmet_cover_os",
	"H_SPE_US_Helmet_ns",
	"H_SPE_US_Helmet_Med",
	"H_SPE_US_Helmet_Med_ns",
	"H_SPE_US_Helmet_Med_os",
	"H_SPE_US_Helmet_NCO",
	"H_SPE_US_Helmet_band_net",
	"H_SPE_US_Helmet_band_net_ns",
	"H_SPE_US_Helmet_band_net_up",
	"H_SPE_US_Helmet_band_net_os",
	"H_SPE_US_Helmet_Net",
	"H_SPE_US_Helmet_CO_Net",
	"H_SPE_US_Helmet_Net_ns",
	"H_SPE_US_Helmet_Net_up",
	"H_SPE_US_Helmet_NCO_net",
	"H_SPE_US_Helmet_Net_os",
	"H_SPE_US_Helmet_polar",
	"H_SPE_US_Helmet_polar_ns",
	"H_SPE_US_Helmet_polar_net",
	"H_SPE_US_Helmet_polar_net_ns",
	"H_SPE_US_Helmet_polar_net_os",
	"H_SPE_US_Helmet_polar_os",
	"H_SPE_US_Helmet_polar_Scrim",
	"H_SPE_US_Helmet_polar_Scrim_ns",
	"H_SPE_US_Helmet_polar_Scrim_os",
	"H_SPE_US_Helmet_os",
	"H_SPE_US_Helmet_Scrim",
	"H_SPE_US_Helmet_Scrim_ns",
	"H_SPE_US_Helmet_Scrim_up",
	"H_SPE_US_Helmet_NCO_scrim",
	"H_SPE_US_Helmet_Scrim_os"
	
];
(_loadoutData get "slHat") append [
	"H_SPE_US_Helmet_First_lieutenant",
	"H_SPE_US_Rangers_Helmet_First_lieutenant",
	"H_SPE_US_Rangers_Helmet_Second_lieutenant",
	"H_SPE_US_Helmet_Second_lieutenant"
];
(_loadoutData get "sniHats") append [
	"H_SPE_US_AB_Helmet",
	"H_SPE_US_AB_Helmet_CO",
	"H_SPE_US_AB_Helmet_CO_ns",
	"H_SPE_US_AB_Helmet_ns",
	"H_SPE_US_AB_Helmet_NCO",
	"H_SPE_US_AB_Helmet_NCO_ns",
	"H_SPE_US_AB_Helmet_Net",
	"H_SPE_US_AB_Helmet_CO_Net",
	"H_SPE_US_AB_Helmet_CO_Net_ns",
	"H_SPE_US_AB_Helmet_Net_ns",
	"H_SPE_US_AB_Helmet_Net_up",
	"H_SPE_US_AB_Helmet_NCO_Net",
	"H_SPE_US_AB_Helmet_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_Net_os",
	"H_SPE_US_AB_Helmet_polar",
	"H_SPE_US_AB_Helmet_polar_ns",
	"H_SPE_US_AB_Helmet_polar_net",
	"H_SPE_US_AB_Helmet_polar_net_ns",
	"H_SPE_US_AB_Helmet_polar_net_os",
	"H_SPE_US_AB_Helmet_polar_os",
	"H_SPE_US_AB_Helmet_polar_Scrim",
	"H_SPE_US_AB_Helmet_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_os",
	"H_SPE_US_AB_Helmet_Scrim",
	"H_SPE_US_AB_Helmet_CO_Scrim",
	"H_SPE_US_AB_Helmet_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_up",
	"H_SPE_US_AB_Helmet_NCO_Scrim",
	"H_SPE_US_AB_Helmet_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_Scrim_os",
	"H_SPE_US_AB_Helmet_501",
	"H_SPE_US_AB_Helmet_501_CO",
	"H_SPE_US_AB_Helmet_501_CO_ns",
	"H_SPE_US_AB_Helmet_501_ns",
	"H_SPE_US_AB_Helmet_501_NCO",
	"H_SPE_US_AB_Helmet_501_NCO_ns",
	"H_SPE_US_AB_Helmet_501_Net",
	"H_SPE_US_AB_Helmet_501_CO_Net",
	"H_SPE_US_AB_Helmet_501_CO_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_up",
	"H_SPE_US_AB_Helmet_501_NCO_Net",
	"H_SPE_US_AB_Helmet_501_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_501_Net_os",
	"H_SPE_US_AB_Helmet_501_polar",
	"H_SPE_US_AB_Helmet_501_polar_ns",
	"H_SPE_US_AB_Helmet_501_polar_net",
	"H_SPE_US_AB_Helmet_501_polar_net_ns",
	"H_SPE_US_AB_Helmet_501_polar_net_os",
	"H_SPE_US_AB_Helmet_501_polar_os",
	"H_SPE_US_AB_Helmet_501_polar_Scrim",
	"H_SPE_US_AB_Helmet_501_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_501_os",
	"H_SPE_US_AB_Helmet_501_Scrim",
	"H_SPE_US_AB_Helmet_501_CO_Scrim",
	"H_SPE_US_AB_Helmet_501_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_up",
	"H_SPE_US_AB_Helmet_501_NCO_Scrim",
	"H_SPE_US_AB_Helmet_501_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_501_Scrim_os",
	"H_SPE_US_AB_Helmet_502",
	"H_SPE_US_AB_Helmet_502_CO",
	"H_SPE_US_AB_Helmet_502_CO_ns",
	"H_SPE_US_AB_Helmet_502_ns",
	"H_SPE_US_AB_Helmet_502_NCO",
	"H_SPE_US_AB_Helmet_502_NCO_ns",
	"H_SPE_US_AB_Helmet_502_Net",
	"H_SPE_US_AB_Helmet_502_CO_Net",
	"H_SPE_US_AB_Helmet_502_CO_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_up",
	"H_SPE_US_AB_Helmet_502_NCO_Net",
	"H_SPE_US_AB_Helmet_502_NCO_Net_ns",
	"H_SPE_US_AB_Helmet_502_Net_os",
	"H_SPE_US_AB_Helmet_502_polar",
	"H_SPE_US_AB_Helmet_502_polar_ns",
	"H_SPE_US_AB_Helmet_502_polar_net",
	"H_SPE_US_AB_Helmet_502_polar_net_ns",
	"H_SPE_US_AB_Helmet_502_polar_net_os",
	"H_SPE_US_AB_Helmet_502_polar_os",
	"H_SPE_US_AB_Helmet_502_polar_Scrim",
	"H_SPE_US_AB_Helmet_502_polar_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_polar_Scrim_os",
	"H_SPE_US_AB_Helmet_502_os",
	"H_SPE_US_AB_Helmet_502_Scrim",
	"H_SPE_US_AB_Helmet_502_CO_Scrim",
	"H_SPE_US_AB_Helmet_502_CO_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_up",
	"H_SPE_US_AB_Helmet_502_NCO_Scrim",
	"H_SPE_US_AB_Helmet_502_NCO_Scrim_ns",
	"H_SPE_US_AB_Helmet_502_Scrim_os",
	"H_SPE_US_HBT_cap",
	"H_SPE_US_HBT_cap_up",
	"H_SPE_US_HBT_cap_polar",
	"H_SPE_US_HBT_cap_rear",
	"H_SPE_US_jeep_cap",
	"H_SPE_US_jeep_cap_polar",
	"H_SPE_US_jeep_cap_rear",
	"H_SPE_US_Helmet",
	"H_SPE_US_Helmet_29ID",
	"H_SPE_US_Helmet_29ID_CO",
	"H_SPE_US_Helmet_29ID_ns",
	"H_SPE_US_Helmet_29ID_NCO",
	"H_SPE_US_Helmet_29ID_Net",
	"H_SPE_US_Helmet_29ID_Net_ns",
	"H_SPE_US_Helmet_29ID_Net_os",
	"H_SPE_US_Helmet_29ID_os",
	"H_SPE_US_Helmet_29ID_Scrim",
	"H_SPE_US_Helmet_29ID_Scrim_ns",
	"H_SPE_US_Helmet_29ID_Scrim_os",
	"H_SPE_US_Rangers_Helmet",
	"H_SPE_US_Rangers_Helmet_Cap",
	"H_SPE_US_Rangers_Helmet_ns",
	"H_SPE_US_Rangers_Helmet_NCO",
	"H_SPE_US_Rangers_Helmet_os",
	"H_SPE_US_Helmet_band",
	"H_SPE_US_Helmet_band_ns",
	"H_SPE_US_Helmet_band_up",
	"H_SPE_US_Helmet_band_os",
	"H_SPE_US_Helmet_Cap",
	"H_SPE_US_Helmet_CO",
	"H_SPE_US_Helmet_cover",
	"H_SPE_US_Helmet_cover_ns",
	"H_SPE_US_Helmet_cover_os",
	"H_SPE_US_Helmet_ns",
	"H_SPE_US_Helmet_Med",
	"H_SPE_US_Helmet_Med_ns",
	"H_SPE_US_Helmet_Med_os",
	"H_SPE_US_Helmet_NCO",
	"H_SPE_US_Helmet_band_net",
	"H_SPE_US_Helmet_band_net_ns",
	"H_SPE_US_Helmet_band_net_up",
	"H_SPE_US_Helmet_band_net_os",
	"H_SPE_US_Helmet_Net",
	"H_SPE_US_Helmet_CO_Net",
	"H_SPE_US_Helmet_Net_ns",
	"H_SPE_US_Helmet_Net_up",
	"H_SPE_US_Helmet_NCO_net",
	"H_SPE_US_Helmet_Net_os",
	"H_SPE_US_Helmet_polar",
	"H_SPE_US_Helmet_polar_ns",
	"H_SPE_US_Helmet_polar_net",
	"H_SPE_US_Helmet_polar_net_ns",
	"H_SPE_US_Helmet_polar_net_os",
	"H_SPE_US_Helmet_polar_os",
	"H_SPE_US_Helmet_polar_Scrim",
	"H_SPE_US_Helmet_polar_Scrim_ns",
	"H_SPE_US_Helmet_polar_Scrim_os",
	"H_SPE_US_Helmet_os",
	"H_SPE_US_Helmet_Scrim",
	"H_SPE_US_Helmet_Scrim_ns",
	"H_SPE_US_Helmet_Scrim_up",
	"H_SPE_US_Helmet_NCO_scrim",
	"H_SPE_US_Helmet_Scrim_os"
];

if (isClass (configFile >> "CfgPatches" >> "WW2_SPEX_Assets_m_Vehicles_Planes_m")) then {
	(_loadoutData get "helmets") append [
		"H_SPE_US_AB_Helmet_327",
		"H_SPE_US_AB_Helmet_327_CO",
		"H_SPE_US_AB_Helmet_327_CO_ns",
		"H_SPE_US_AB_Helmet_327_ns",
		"H_SPE_US_AB_Helmet_327_NCO",
		"H_SPE_US_AB_Helmet_327_NCO_ns",
		"H_SPE_US_AB_Helmet_327_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_up",
		"H_SPE_US_AB_Helmet_327_NCO_Net",
		"H_SPE_US_AB_Helmet_327_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_os",
		"H_SPE_US_AB_Helmet_327_polar",
		"H_SPE_US_AB_Helmet_327_polar_ns",
		"H_SPE_US_AB_Helmet_327_polar_net",
		"H_SPE_US_AB_Helmet_327_polar_net_ns",
		"H_SPE_US_AB_Helmet_327_polar_net_os",
		"H_SPE_US_AB_Helmet_327_polar_os",
		"H_SPE_US_AB_Helmet_327_polar_Scrim",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_327_os",
		"H_SPE_US_AB_Helmet_327_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_up",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_os",
		"H_SPE_US_AB_Helmet_506",
		"H_SPE_US_AB_Helmet_506_CO",
		"H_SPE_US_AB_Helmet_506_CO_ns",
		"H_SPE_US_AB_Helmet_506_ns",
		"H_SPE_US_AB_Helmet_506_NCO",
		"H_SPE_US_AB_Helmet_506_NCO_ns",
		"H_SPE_US_AB_Helmet_506_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_up",
		"H_SPE_US_AB_Helmet_506_NCO_Net",
		"H_SPE_US_AB_Helmet_506_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_os",
		"H_SPE_US_AB_Helmet_506_polar",
		"H_SPE_US_AB_Helmet_506_polar_ns",
		"H_SPE_US_AB_Helmet_506_polar_net",
		"H_SPE_US_AB_Helmet_506_polar_net_ns",
		"H_SPE_US_AB_Helmet_506_polar_net_os",
		"H_SPE_US_AB_Helmet_506_polar_os",
		"H_SPE_US_AB_Helmet_506_polar_Scrim",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_506_os",
		"H_SPE_US_AB_Helmet_506_Scrim",
		"H_SPE_US_AB_Helmet_506_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_up",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_os"
	];

	(_loadoutData get "slHat") append [
		"H_SPE_US_AB_Helmet_327",
		"H_SPE_US_AB_Helmet_327_CO",
		"H_SPE_US_AB_Helmet_327_CO_ns",
		"H_SPE_US_AB_Helmet_327_ns",
		"H_SPE_US_AB_Helmet_327_NCO",
		"H_SPE_US_AB_Helmet_327_NCO_ns",
		"H_SPE_US_AB_Helmet_327_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_up",
		"H_SPE_US_AB_Helmet_327_NCO_Net",
		"H_SPE_US_AB_Helmet_327_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_os",
		"H_SPE_US_AB_Helmet_327_polar",
		"H_SPE_US_AB_Helmet_327_polar_ns",
		"H_SPE_US_AB_Helmet_327_polar_net",
		"H_SPE_US_AB_Helmet_327_polar_net_ns",
		"H_SPE_US_AB_Helmet_327_polar_net_os",
		"H_SPE_US_AB_Helmet_327_polar_os",
		"H_SPE_US_AB_Helmet_327_polar_Scrim",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_327_os",
		"H_SPE_US_AB_Helmet_327_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_up",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_os",
		"H_SPE_US_AB_Helmet_506",
		"H_SPE_US_AB_Helmet_506_CO",
		"H_SPE_US_AB_Helmet_506_CO_ns",
		"H_SPE_US_AB_Helmet_506_ns",
		"H_SPE_US_AB_Helmet_506_NCO",
		"H_SPE_US_AB_Helmet_506_NCO_ns",
		"H_SPE_US_AB_Helmet_506_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_up",
		"H_SPE_US_AB_Helmet_506_NCO_Net",
		"H_SPE_US_AB_Helmet_506_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_os",
		"H_SPE_US_AB_Helmet_506_polar",
		"H_SPE_US_AB_Helmet_506_polar_ns",
		"H_SPE_US_AB_Helmet_506_polar_net",
		"H_SPE_US_AB_Helmet_506_polar_net_ns",
		"H_SPE_US_AB_Helmet_506_polar_net_os",
		"H_SPE_US_AB_Helmet_506_polar_os",
		"H_SPE_US_AB_Helmet_506_polar_Scrim",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_506_os",
		"H_SPE_US_AB_Helmet_506_Scrim",
		"H_SPE_US_AB_Helmet_506_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_up",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_os"
	];

	(_loadoutData get "sniHats") append [
		"H_SPE_US_AB_Helmet_327",
		"H_SPE_US_AB_Helmet_327_CO",
		"H_SPE_US_AB_Helmet_327_CO_ns",
		"H_SPE_US_AB_Helmet_327_ns",
		"H_SPE_US_AB_Helmet_327_NCO",
		"H_SPE_US_AB_Helmet_327_NCO_ns",
		"H_SPE_US_AB_Helmet_327_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net",
		"H_SPE_US_AB_Helmet_327_CO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_up",
		"H_SPE_US_AB_Helmet_327_NCO_Net",
		"H_SPE_US_AB_Helmet_327_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_327_Net_os",
		"H_SPE_US_AB_Helmet_327_polar",
		"H_SPE_US_AB_Helmet_327_polar_ns",
		"H_SPE_US_AB_Helmet_327_polar_net",
		"H_SPE_US_AB_Helmet_327_polar_net_ns",
		"H_SPE_US_AB_Helmet_327_polar_net_os",
		"H_SPE_US_AB_Helmet_327_polar_os",
		"H_SPE_US_AB_Helmet_327_polar_Scrim",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_327_os",
		"H_SPE_US_AB_Helmet_327_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim",
		"H_SPE_US_AB_Helmet_327_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_up",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim",
		"H_SPE_US_AB_Helmet_327_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_327_Scrim_os",
		"H_SPE_US_AB_Helmet_506",
		"H_SPE_US_AB_Helmet_506_CO",
		"H_SPE_US_AB_Helmet_506_CO_ns",
		"H_SPE_US_AB_Helmet_506_ns",
		"H_SPE_US_AB_Helmet_506_NCO",
		"H_SPE_US_AB_Helmet_506_NCO_ns",
		"H_SPE_US_AB_Helmet_506_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net",
		"H_SPE_US_AB_Helmet_506_CO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_up",
		"H_SPE_US_AB_Helmet_506_NCO_Net",
		"H_SPE_US_AB_Helmet_506_NCO_Net_ns",
		"H_SPE_US_AB_Helmet_506_Net_os",
		"H_SPE_US_AB_Helmet_506_polar",
		"H_SPE_US_AB_Helmet_506_polar_ns",
		"H_SPE_US_AB_Helmet_506_polar_net",
		"H_SPE_US_AB_Helmet_506_polar_net_ns",
		"H_SPE_US_AB_Helmet_506_polar_net_os",
		"H_SPE_US_AB_Helmet_506_polar_os",
		"H_SPE_US_AB_Helmet_506_polar_Scrim",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_polar_Scrim_os",
		"H_SPE_US_AB_Helmet_506_os",
		"H_SPE_US_AB_Helmet_506_Scrim",
		"H_SPE_US_AB_Helmet_506_CO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_up",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim",
		"H_SPE_US_AB_Helmet_506_NCO_Scrim_ns",
		"H_SPE_US_AB_Helmet_506_Scrim_os"
	];
};

// Аксессуары
(_loadoutData get "glasses") append ["G_SPE_Cigar_Moza","G_SPE_Cigarette_Belomorkanal","G_SPE_Cigarette_Grundstein","G_SPE_Cigarette_Strike_Outs"];
(_loadoutData get "goggles") append ["G_SPE_Binoculars","G_SPE_SWDG_Goggles","G_SPE_Polar_Goggles","G_SPE_Pipe_Sir_Winston"];

// Дополнительные предметы для специализаций
_eeItems append ["ToolKit", "MineDetector"];