//SPE_IFA3

		class handgunsspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_handguns"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
			
			ITEM(SPE_P08, 110, PISTOL_STOCK); //AMMO: SPE_8Rnd_9x19_P08
			ITEM(SPE_M1911, 110, PISTOL_STOCK); //AMMO: SPE_7Rnd_45ACP_1911
			
		};

		class smgspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_smgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";
		
			ITEM(SPE_Sten_Mk2, 165, RIFLE_STOCK); // SPE_32Rnd_9x19_Sten
			ITEM(SPE_Sten_Mk2_Suppressed, 185, RIFLE_STOCK); // LIB_32Rnd_9x19_Sten
			ITEM(SPE_MP40, 200, RIFLE_STOCK); // SPE_32Rnd_9x19 SPE_32Rnd_9x19_t
			ITEM(SPE_MP35, 300, RIFLE_STOCK); // SPE_32Rnd_MP35_9x19 SPE_32rnd_MP35_9x19_t SPE_24Rnd_MP35_9x19 SPE_24rnd_MP35_9x19_t
			ITEM(SPE_M3_GreaseGun, 185, RIFLE_STOCK); // SPE_30Rnd_M3_GreaseGun_45ACP SPE_30Rnd_M3_GreaseGun_45ACP_t
			ITEM(SPE_STG44, 400, RIFLE_STOCK); // 30rnd mag: SPE_30Rnd_792x33  SPE_30Rnd_792x33_t
			ITEM(SPE_FG42_E, 450, RIFLE_STOCK); // 30rnd mag: SPE_20Rnd_792x57  SPE_20Rnd_792x57_t2 SPE_20Rnd_792x57_SMK SPE_20Rnd_792x57_sS SPE_20Rnd_792x57_t
			ITEM(SPE_M1A1_Thompson, 300, RIFLE_STOCK); // 30rnd mag: SPE_30Rnd_792x33  SPE_30Rnd_792x33_t
			
		};
		
		class mgspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_mgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";	

			ITEM(SPE_M1919A4, 550, RIFLE_STOCK); //NORMAL: SPE_50Rnd_762x63 SPE_50Rnd_762x63_M1 SPE_50Rnd_762x63_M2_AP
			ITEM(SPE_M1919A6, 650, RIFLE_STOCK); //NORMAL: SPE_50Rnd_762x63 SPE_50Rnd_762x63_M1 SPE_50Rnd_762x63_M2_AP
			ITEM(SPE_FM_24_M29, 500, RIFLE_STOCK); // SPE_25Rnd_75x54 SPE_25Rnd_75x54_35P_AP
			ITEM(SPE_M1918A0_BAR, 450, RIFLE_STOCK); // SPE_20Rnd_762x63 SPE_20Rnd_762x63_M1 SPE_20Rnd_762x63_M2_AP
			ITEM(SPE_M1918A2_erla_BAR, 460, RIFLE_STOCK); // SPE_20Rnd_762x63 SPE_20Rnd_762x63_M1 SPE_20Rnd_762x63_M2_AP
			ITEM(SPE_M1918A2_BAR, 410, RIFLE_STOCK); // SPE_20Rnd_762x63 SPE_20Rnd_762x63_M1 SPE_20Rnd_762x63_M2_AP
			ITEM(SPE_LMG_303_Mk2, 400, RIFLE_STOCK); // SPE_30Rnd_770x56 SPE_30Rnd_770x56_AP_MKI SPE_30Rnd_770x56_MKVIII
			ITEM(SPE_MG34, 850, RIFLE_STOCK); //NORMAL: SPE_50Rnd_792x57 	SPE_50Rnd_792x57_SMK	SPE_50Rnd_792x57_sS
			ITEM(SPE_MG42, 1000, RIFLE_STOCK); //NORMAL: SPE_50Rnd_792x57 	SPE_50Rnd_792x57_SMK	SPE_50Rnd_792x57_sS
			
		};

		class riflesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_rifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(SPE_M1_Carbine, 250, RIFLE_STOCK); //NORMAL: SPE_15Rnd_762x33 TRACER: SPE_15Rnd_762x33_t
			ITEM(SPE_M1_Garand, 300, RIFLE_STOCK); //NORMAL: SPE_8Rnd_762x63  SPE_8Rnd_762x63_M1  SPE_8Rnd_762x63_t SPE_8Rnd_762x63_M2_AP
			ITEM(SPE_M1903A3_Springfield, 200, RIFLE_STOCK); //NORMAL: SPE_5Rnd_762x63  SPE_5Rnd_762x63_M1  SPE_5Rnd_762x63_t  SPE_5Rnd_762x63_M2_AP
			ITEM(SPE_No3_Mk1_Enfield, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII 
			ITEM(SPE_MAS_36, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_75x54 SPE_5Rnd_75x54_35P_AP 
			ITEM(SPE_K98, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_792x57 SPE_5Rnd_792x57_t SPE_5Rnd_792x57_SMK SPE_5Rnd_792x57_sS
			ITEM(SPE_K98_Late, 190, RIFLE_STOCK); //NORMAL: ^^
			ITEM(SPE_G43, 280, RIFLE_STOCK); //NORMAL: SPE_10Rnd_792x57 SPE_10Rnd_792x57_T2 SPE_10Rnd_792x57_SMK SPE_10Rnd_792x57_sS SPE_10Rnd_792x57_T
			ITEM(SPE_M1A1_Carbine, 200, RIFLE_STOCK);
		};

		class sniperriflesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_sniperRifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";
		
			ITEM(SPE_M1903A4_Springfield, 570, RIFLE_STOCK); // SAME AS SPE_M1903A3_Springfield
			ITEM(SPE_K98ZF39, 570, RIFLE_STOCK); // SAME AS SPE_K98
			
		};

		class launchersspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_launchers"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\secondaryWeapon_ca.paa";

			ITEM(SPE_Faustpatrone, 100, 15);
			ITEM(SPE_PzFaust_30m, 100, 15);
			ITEM(SPE_PzFaust_60m, 100, 15);
			ITEM(SPE_M1A1_Bazooka, 350, 25); 
			
		}; 

		class launchermagazinesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_launcherAmmo"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";

			ITEM(SPE_1Rnd_60mm_M6, 100, 15);
			ITEM(SPE_1Rnd_Faustpatrone, 100, 15);
			ITEM(SPE_1Rnd_PzFaust_30m, 100, 15);
			ITEM(SPE_1Rnd_PzFaust_60m, 100, 15);
			
		};

		class riflegrenadesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_glGrenades"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";
			
			ITEM(SPE_1Rnd_G_NBGR_42, 50, 25);
			ITEM(SPE_1Rnd_G_M2_ANM8, 50, 25);
			ITEM(SPE_1Rnd_G_PZGR_30, 90, 25);
			ITEM(SPE_1Rnd_G_SPRGR_30, 80, 25);
			ITEM(SPE_1Rnd_G_PZGR_40, 90, 25);
			ITEM(SPE_1Rnd_G_M9A1, 80, 25);
			ITEM(SPE_1Rnd_G_Mk2, 90, 25);
			ITEM(SPE_1Rnd_G_M2_AN_M14, 100, 25);
			ITEM(SPE_1Rnd_G_M17A1, 50, 25);
			ITEM(SPE_1Rnd_G_FLGR, 50, 25);

			ITEM(SPE_1Rnd_G_M2_M18_Yellow, 50, 25);
			ITEM(SPE_1Rnd_G_M2_M18_Violet, 50, 25);
			ITEM(SPE_1Rnd_G_M2_M18_Red, 50, 25);
			ITEM(SPE_1Rnd_G_M2_M18_Green, 50, 25);
			ITEM(SPE_1Rnd_G_M51A1, 50, 25);
			ITEM(SPE_1Rnd_G_M21A1, 50, 25);
			ITEM(SPE_1Rnd_G_M19A1, 50, 25);
			ITEM(SPE_1Rnd_81mmWP_M1_M57, 200, 25);
			ITEM(SPE_81mm_M1_M57_SmokeShell, 200, 25);
			ITEM(SPE_1Rnd_81mmHE_M1_M43A1, 200, 25);
			ITEM(SPE_81mm_FA_Mle_1932_Smoke, 100, 25);
			ITEM(SPE_81mm_FA_Mle_1932_Illu, 100, 25);
			ITEM(SPE_1Rnd_81mm_FA_Mle_1932_HE, 200, 25);
			
		};

		class muzzlesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_muzzles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemMuzzle_ca.paa";
			
			ITEM(spe_acc_m3_suppressor_45acp, 75, MZ_STOCK);
			ITEM(spe_acc_m1_bayo, 75, MZ_STOCK);
			ITEM(spe_acc_m1905_bayo, 75, MZ_STOCK);
			ITEM(spe_acc_k98_bayo, 75, MZ_STOCK);
			ITEM(spe_acc_gl_m8, 80, MZ_STOCK);
			ITEM(spe_acc_gl_m7, 80, MZ_STOCK);
			ITEM(spe_acc_gw_sb_empty, 80, MZ_STOCK);
			
		};

		class magazinesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_magazines"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";		
			
			ITEM(SPE_8Rnd_9x19_P08, 15, MZ_STOCK);
			ITEM(SPE_7Rnd_45ACP_1911, 15, MZ_STOCK);
			ITEM(SPE_32Rnd_9x19_Sten, 20, MZ_STOCK);
			ITEM(SPE_32Rnd_9x19, 20, MZ_STOCK);
			ITEM(SPE_32Rnd_9x19_t, 20, MZ_STOCK);
			ITEM(SPE_30Rnd_M3_GreaseGun_45ACP, 20, MZ_STOCK);
			ITEM(SPE_30Rnd_M3_GreaseGun_45ACP_t, 20, MZ_STOCK);
			ITEM(SPE_32Rnd_MP35_9x19, 25, MZ_STOCK);
			ITEM(SPE_32rnd_MP35_9x19_t, 25, MZ_STOCK);
			ITEM(SPE_24Rnd_MP35_9x19, 20, MZ_STOCK);
			ITEM(SPE_24rnd_MP35_9x19_t, 20, MZ_STOCK);
			ITEM(SPE_30Rnd_792x33, 30, MZ_STOCK);
			ITEM(SPE_30Rnd_792x33_t, 30, MZ_STOCK);
			ITEM(SPE_50Rnd_762x63, 50, MZ_STOCK);
			ITEM(SPE_50Rnd_762x63_M1, 50, MZ_STOCK);
			ITEM(SPE_50Rnd_762x63_M2_AP, 70, MZ_STOCK);
			ITEM(SPE_25Rnd_75x54, 40, MZ_STOCK);
			ITEM(SPE_25Rnd_75x54_35P_AP, 50, MZ_STOCK);
			ITEM(SPE_20Rnd_762x63, 35, MZ_STOCK);
			ITEM(SPE_20Rnd_762x63_M1, 35, MZ_STOCK);
			ITEM(SPE_20Rnd_762x63_M2_AP, 45, MZ_STOCK);
			ITEM(SPE_50Rnd_792x57, 50, MZ_STOCK);
			ITEM(SPE_50Rnd_792x57_SMK, 50, MZ_STOCK);
			ITEM(SPE_50Rnd_792x57_sS, 50, MZ_STOCK);
			ITEM(SPE_15Rnd_762x33, 25, MZ_STOCK);
			ITEM(SPE_15Rnd_762x33_t, 25, MZ_STOCK);
			ITEM(SPE_8Rnd_762x63, 25, MZ_STOCK);
			ITEM(SPE_8Rnd_762x63_M1, 25, MZ_STOCK);
			ITEM(SPE_8Rnd_762x63_t, 26, MZ_STOCK);
			ITEM(SPE_8Rnd_762x63_M2_AP, 30, MZ_STOCK);
			ITEM(SPE_5Rnd_762x63, 20, MZ_STOCK);
			ITEM(SPE_5Rnd_762x63_M1, 22, MZ_STOCK);
			ITEM(SPE_5Rnd_762x63_t, 22, MZ_STOCK);
			ITEM(SPE_5Rnd_762x63_M2_AP, 25, MZ_STOCK);
			ITEM(SPE_5Rnd_792x57, 20, MZ_STOCK);
			ITEM(SPE_5Rnd_792x57_t, 25, MZ_STOCK);
			ITEM(SPE_5Rnd_792x57_SMK, 30, MZ_STOCK);
			ITEM(SPE_5Rnd_792x57_sS, 30, MZ_STOCK);
			ITEM(SPE_10Rnd_792x57, 35, MZ_STOCK);
			ITEM(SPE_10Rnd_792x57_T2, 35, MZ_STOCK);
			ITEM(SPE_10Rnd_792x57_SMK, 45, MZ_STOCK);
			ITEM(SPE_10Rnd_792x57_sS, 45, MZ_STOCK);
			ITEM(SPE_10Rnd_792x57_T, 35, MZ_STOCK);
			ITEM(SPE_5Rnd_770x56, 25, MZ_STOCK);
			ITEM(SPE_5Rnd_770x56_AP_MKI, 30, MZ_STOCK);
			ITEM(SPE_5Rnd_770x56_MKVIII, 30, MZ_STOCK);
			ITEM(SPE_5Rnd_75x54, 25, MZ_STOCK);
			ITEM(SPE_5Rnd_75x54_35P_AP, 30, MZ_STOCK);
			ITEM(SPE_2Rnd_12x65_Slug, 45, MZ_STOCK);
			ITEM(SPE_2Rnd_12x65_Pellets, 45, MZ_STOCK);
			ITEM(SPE_2Rnd_12x65_No4_Buck, 45, MZ_STOCK);
			ITEM(SPE_5Rnd_12x70_Slug, 75, MZ_STOCK);
			ITEM(SPE_5Rnd_12x70_Pellets, 75, MZ_STOCK);
			ITEM(SPE_5Rnd_12x70_No4_Buck, 75, MZ_STOCK);
			ITEM(SPE_30Rnd_Thompson_45ACP_t, 45, MZ_STOCK);
			ITEM(SPE_30Rnd_Thompson_45ACP, 45, MZ_STOCK);
			ITEM(SPE_20Rnd_Thompson_45ACP_t, 45, MZ_STOCK);
			ITEM(SPE_20Rnd_Thompson_45ACP, 45, MZ_STOCK);
			ITEM(SPE_100Rnd_762x63_M2_AP, 45, MZ_STOCK);
			ITEM(SPE_100Rnd_762x63_M1 45, MZ_STOCK);
			ITEM(SPE_100Rnd_762x63, 45, MZ_STOCK);
			ITEM(SPE_100Rnd_792x57, 45, MZ_STOCK);
			ITEM(SPE_100Rnd_792x57_SMK, 45, MZ_STOCK);
			ITEM(SPE_100Rnd_792x57_sS, 45, MZ_STOCK);
			ITEM(SPE_30Rnd_770x56, 45, MZ_STOCK);
			ITEM(SPE_30Rnd_770x56_AP_MKI, 45, MZ_STOCK);
			ITEM(SPE_30Rnd_770x56_MKVIII, 45, MZ_STOCK);
			ITEM(SPE_20Rnd_792x57, 75, MZ_STOCK);
			ITEM(SPE_20Rnd_792x57_t2, 75, MZ_STOCK);
			ITEM(SPE_20Rnd_792x57_SMK, 75, MZ_STOCK);
			ITEM(SPE_20Rnd_792x57_sS, 75, MZ_STOCK);
			ITEM(SPE_20Rnd_792x57_t, 75, MZ_STOCK);
			ITEM(SPE_M2_Flamethrower_Mag, 250, MZ_STOCK);
			ITEM(SPE_Flammenwerfer41_Mag, 250, MZ_STOCK);
			
		};

		class miscspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_misc"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			
			ITEM(SPE_US_TNT_4pound_mag, 450, MISC_STOCK);
			ITEM(SPE_US_TNT_half_pound_mag, 400, MISC_STOCK);
			ITEM(SPE_US_Bangalore_mag, 450, MISC_STOCK);

			ITEM(SPE_TMI_42_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_STMI_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_SMI_35_1_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_SMI_35_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_SMI_35_Pressure_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_Shg24x7_Improvised_Mine_mag, 400, MISC_STOCK);
			ITEM(SPE_shumine_42_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_US_M3_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_US_M3_Pressure_MINE_mag, 400, MISC_STOCK);
			ITEM(SPE_US_M1A1_ATMINE_mag, 400, MISC_STOCK);
			ITEM(SPE_Ladung_Big_MINE_mag, 600, MISC_STOCK);
			ITEM(SPE_Ladung_Small_MINE_mag, 400, MISC_STOCK);

			ITEM(SPE_ToolKit_NoMass, 1000, MISC_STOCK);
			ITEM(SPE_ToolKit, 200, MISC_STOCK);

			ITEM(SPE_GER_Headset, 20, MISC_STOCK);

			ITEM(SPE_Rauchsichtzeichen_Orange, 50, MISC_STOCK);
			ITEM(SPE_NBK39b, 50, MISC_STOCK);
			ITEM(SPE_NB39, 20, MISC_STOCK);
			ITEM(SPE_US_M18_Yellow, 20, MISC_STOCK);
			ITEM(SPE_US_M18_Violet, 20, MISC_STOCK);
			ITEM(SPE_US_M18_Red, 20, MISC_STOCK);
			ITEM(SPE_US_M18_Green, 20, MISC_STOCK);
			ITEM(SPE_US_M15, 20, MISC_STOCK);
			ITEM(SPE_Handrauchzeichen_Yellow, 20, MISC_STOCK);
			ITEM(SPE_Handrauchzeichen_Violet, 20, MISC_STOCK);
			ITEM(SPE_Handrauchzeichen_Red, 20, MISC_STOCK);
			ITEM(SPE_US_M18, 20, MISC_STOCK);
			ITEM(SPE_US_AN_M14, 50, MISC_STOCK);
			ITEM(SPE_US_Mk_1, 50, MISC_STOCK);
			ITEM(SPE_US_Mk_2_Yellow, 50, MISC_STOCK);
			ITEM(SPE_US_Mk_2, 50, MISC_STOCK);
			ITEM(SPE_Shg24_Frag, 50, MISC_STOCK);
			ITEM(SPE_US_Mk_3, 50, MISC_STOCK);
			ITEM(SPE_M39, 50, MISC_STOCK);
			ITEM(SPE_Shg24, 50, MISC_STOCK);
			ITEM(SPE_Shg24x7, 100, MISC_STOCK);

			ITEM(SPE_US_Medkit, 200, MISC_STOCK);
			ITEM(SPE_GER_Medkit, 200, MISC_STOCK);
			ITEM(SPE_US_FirstAidKit, 20, MISC_STOCK);
			ITEM(SPE_GER_FirstAidKit, 20, MISC_STOCK);
			
		};

		class navigationspe
		{
			displayName = __EVAL(formatText ["%1 %2, %3 %4 %5", localize "STR_A3AU_spearhead", localize "STR_A3AU_gps", localize "STR_A3AU_binoculars", localize "STR_A3AU_and", localize "STR_A3AU_nvgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\compass_ca.paa";

			ITEM(SPE_Binocular_US, 100, NN_STOCK);
			ITEM(SPE_Binocular_GER, 100, NN_STOCK);

			ITEM(SPE_US_FL_TL122, 50, NN_STOCK);
			ITEM(SPE_GER_FL_Signal_Flashlight, 50, NN_STOCK);

			ITEM(SPE_US_ItemCompass, 20, NN_STOCK);
			ITEM(SPE_GER_ItemCompass, 20, NN_STOCK);
			ITEM(SPE_GER_ItemCompass_deg, 20, NN_STOCK);
			ITEM(SPE_US_ItemWatch, 20, NN_STOCK);
			ITEM(SPE_GER_ItemWatch, 20, NN_STOCK);

		};

		class specialweaponsspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_specialWeapons"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(SPE_Fusil_Mle_208_12, 150, MISC_STOCK);
			ITEM(SPE_Fusil_Mle_208_12_Sawedoff, 150, MISC_STOCK);
			ITEM(SPE_Model_37_Riotgun, 250, MISC_STOCK);
			ITEM(SPE_Model_37_Trenchgun, 250, MISC_STOCK);
			ITEM(SPE_Flammenwerfer41, 300, MISC_STOCK);
			ITEM(B_SPE_GER_Flammenwerfer_41, 800, MISC_STOCK);
			ITEM(SPE_M2_Flamethrower, 300, MISC_STOCK);
			ITEM(B_SPE_US_M2Flamethrower, 800, MISC_STOCK);

			ITEM(SPE_GrW278_1_Barrel, 2000, MISC_STOCK);
			ITEM(SPE_GrW278_1_Stand, 200, MISC_STOCK);
			ITEM(SPE_MLE_27_31_Barrel, 2000, MISC_STOCK);
			ITEM(SPE_MLE_27_31_Stand, 200, MISC_STOCK);
			ITEM(SPE_M1_81_Barrel, 2000, MISC_STOCK);
			ITEM(SPE_M1_81_Stand, 200, MISC_STOCK);
			ITEM(SPE_M2_Tripod, 200, MISC_STOCK);
			ITEM(SPE_M2_50, 1000, MISC_STOCK);
			ITEM(SPE_Lafette_Tripod, 400, MISC_STOCK);
		};

		class underbarrelspe{
	     	displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_bagsStatics"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemBipod_ca.paa";

			
			ITEM(SPE_Optic_ZFG42, 170, PN_STOCK);
			ITEM(SPE_M1918A2_BAR_Bipod, 100, MISC_STOCK);
			ITEM(SPE_M1918A2_BAR_Handle, 100, MISC_STOCK);
			ITEM(SPE_ACC_GW_SB_Empty, 100, MISC_STOCK);
			ITEM(SPE_ACC_K98_Bayo, 100, MISC_STOCK);
			ITEM(SPE_ACC_GL_M8, 100, MISC_STOCK);
			ITEM(SPE_ACC_GL_M7, 100, MISC_STOCK);
			ITEM(SPE_ACC_M3_Suppressor_45acp, 100, MISC_STOCK);
			ITEM(SPE_ACC_M1905_Bayo, 100, MISC_STOCK);
			ITEM(SPE_ACC_GL_M1, 100, MISC_STOCK);
			ITEM(SPE_ACC_M1_Bayo, 100, MISC_STOCK);
			ITEM(SPE_ACC_M1917_Bayo, 100, MISC_STOCK);
			
		};

		class pointersspe{
			displayName = __EVAL(formatText ["%1 %2 %3 %4 %5", localize "STR_A3AU_spearhead", localize "STR_A3AU_barret", localize "STR_A3AU_handles", localize "STR_A3AU_and", localize "STR_A3AU_bipods"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemAcc_ca.paa";

			ITEM(SPE_Carbine_pouch, 70, PN_STOCK);
			ITEM(SPE_Carbine_pouch_od7, 70, PN_STOCK);
		};

		class helmetsspe 
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_helmets"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			/////helmets
			ITEM(H_SPE_US_Helmet_Tank_tapes, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_polar_tapes, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_polar_low, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_M1_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_M1_OS, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_M1_NS, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_Nun, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Tank_NG, 100, MISC_STOCK);
			ITEM(H_SPE_US_Pilot_Cap_Khaki, 100, MISC_STOCK);
			ITEM(H_SPE_US_Pilot_Cap, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_NCO_scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_NCO_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_MP_Helmet_White_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_MP_Helmet_White_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_MP_Helmet_White, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Med_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Med_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Med, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Cap, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet_NCO, 100, MISC_STOCK);

			ITEM(H_SPE_US_Rangers_Helmet_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet_Cap, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet_Second_lieutenant, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet_First_lieutenant, 100, MISC_STOCK);
			ITEM(H_SPE_US_Rangers_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Second_lieutenant, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_29ID, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_First_lieutenant, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_Op, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_SWDG_low_O2, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_SWDG_O2, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_B7_low_O2, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_B7_O2, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_O2, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_SWDG_low, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15_SWDG, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_H15, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Op, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_SWDG_low_Respirator, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_SWDG_Respirator, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Respirator_Glasses_Down, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Respirator_Glasses_Up, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Respirator, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Glasses_Down, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot_Glasses_Up, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Pilot, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_os, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetCamo2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetCamo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetCamo4, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_ns_wire_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_os_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_ns_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_net_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_Glasses_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_ns_wire, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility_Oak_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility_Oak, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_Medic, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility_Grass_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility_Grass, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_Glasses, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetCamo3_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetCamo3, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_HelmetUtility, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet4, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Fieldcap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_Tanker_Cap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_Tanker_Cap2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Fieldcap2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankOfficerCap2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankOfficerCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_PzgrenOfficerCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_OfficerCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ArtOfficerCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_LW_PilotHelmet_Mask, 100, MISC_STOCK);
			ITEM(H_SPE_GER_LW_PilotHelmet, 100, MISC_STOCK);
			ITEM(H_SPE_GER_LW_PilotHelmet_S_Mask, 100, MISC_STOCK);
			ITEM(H_SPE_GER_LW_S_PilotHelmet, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankOffzCap3, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankOffzCap2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankPrivateCap2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankOffzCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankPrivateCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_TankPrivateCap3, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Cap_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_SPGPrivateCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_SPGPrivateCap2, 100, MISC_STOCK);
			ITEM(H_SPE_FR_US_Helmet_os, 100, MISC_STOCK);
			ITEM(H_SPE_FR_US_Helmet_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FR_US_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_Medic_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_Medic, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Worker_Cap_1, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Worker_Cap_2, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Worker_Cap_3, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_3, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_4, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_2, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_1, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_6, 100, MISC_STOCK);
			ITEM(H_SPE_CIV_Fedora_Cap_5, 100, MISC_STOCK);
			/////helmets

			//1.1
			ITEM(H_SPE_Milice_beret_2, 100, MISC_STOCK);
			ITEM(H_SPE_Milice_beret_1, 100, MISC_STOCK);

			ITEM(H_SPE_Milice_Adrian_ns, 100, MISC_STOCK);
			ITEM(H_SPE_Milice_Adrian, 100, MISC_STOCK);
			ITEM(H_SPE_US_jeep_cap_rear, 100, MISC_STOCK);
			ITEM(H_SPE_US_jeep_cap_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_jeep_cap, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_Net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_cover_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_cover_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_cover, 100, MISC_STOCK);
			ITEM(H_SPE_US_Helmet_band_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_HBT_cap_rear, 100, MISC_STOCK);
			ITEM(H_SPE_US_HBT_cap_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_HBT_cap_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_HBT_cap, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_502, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_501, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_NCO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_NCO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_NCO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_NCO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_Net, 100, MISC_STOCK);

			ITEM(H_SPE_US_AB_Helmet_NCO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_wire, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_wire_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_wire_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_net_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_net_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_Glasses_painted_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_Glasses_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_painted, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_wire, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility_Oak_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility_Oak, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility_Grass_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility_Grass, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_Glasses_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_Glasses, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40Utility, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35_Glasses_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35_Glasses, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_burlap_band_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_burlap_band, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet3_OS, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet3, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet4_OS, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet5_OS, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet5, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet6_OS, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet6, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet_OS, 100, MISC_STOCK);
			ITEM(H_SPE_ST_Helmet2_OS, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap_Offz_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_Pz_cap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap_Offz_hp, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap_hp, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ST_M40_cap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_pzgren, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_pzgren_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_PzGren_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_PzGren_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz_Offz_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Pz_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_inf, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_inf_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_inf_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_inf_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_art, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_art_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Art_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Art_Offz_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_Art_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38_art_headset, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M38, 100, MISC_STOCK);
			ITEM(H_SPE_GER_PzNCOCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_PzgrenNCOCap, 100, MISC_STOCK);

			ITEM(H_SPE_GER_NCOCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_ArtNCOCap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Cuba, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_lw_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_lw_net_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_lw_net_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_lw_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_lw, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_ns_lw_net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_lw_net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M40_lw, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35_LW_ns, 100, MISC_STOCK);
			ITEM(H_SPE_GER_Helmet_M35_LW, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M40_LW_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M40_LW_Offz_2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M40_LW_Offz, 100, MISC_STOCK);
			ITEM(H_SPE_GER_M40_LW, 100, MISC_STOCK);
			ITEM(H_SPE_GER_LW_Cap, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Wire_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Wire, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_BB_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_BB_erla, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_BB, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Cover_split1, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Cover_split2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_sutra, 100, MISC_STOCK);

			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo5, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo4, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo3, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo2, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_camo1, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Net_camo, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Net_erla, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Net, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_medic, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_medic_alt, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_erla, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Cover_fade, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_Cover, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet_kentang, 100, MISC_STOCK);
			ITEM(H_SPE_GER_FSJ_M38_Helmet, 100, MISC_STOCK);

			ITEM(H_SPE_FR_Adrian_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_net, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_cover_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FR_Adrian_cover, 100, MISC_STOCK);
			ITEM(H_SPE_FFI_Adrian_ns, 100, MISC_STOCK);
			ITEM(H_SPE_FFI_Adrian, 100, MISC_STOCK);
		};

		class uniformsspe 
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_uniforms"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			////uniforms
			ITEM(U_SPE_US_CC_EM_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_EM_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_CPT, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_EM_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_2LT, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_1LT, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_EM, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_EM_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_EM_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_EM_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_EM, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_camo_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_camo_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_camo_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_HBT_camo, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew3, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew4, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew2, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew_camo2, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew_medic_camo, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew_camo, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew_medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Crew, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_late_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_Half, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_Med, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_FrogSkin_Jungle_Half, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_FrogSkin_Jungle_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_FrogSkin_Jungle_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_FrogSkin_Jungle, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Coverall_Trop_Legging, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Coverall_Trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Coverall, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31A_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31A_boot, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31A, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31_erla_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31_erla_boot, 50, MISC_STOCK);
			ITEM(U_SPE_US_S31_erla, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot_boot, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot_lthr_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot_lthr_boot, 50, MISC_STOCK);
			ITEM(U_SPE_US_Pilot_lthr, 50, MISC_STOCK);
			ITEM(U_SPE_US_Med_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_Private_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_Technician, 50, MISC_STOCK);
			ITEM(U_SPE_US_Sergeant, 50, MISC_STOCK);
			ITEM(U_SPE_US_Private_1st, 50, MISC_STOCK);
			ITEM(U_SPE_US_Med, 50, MISC_STOCK);
			ITEM(U_SPE_US_Corp, 50, MISC_STOCK);
			ITEM(U_SPE_US_Private, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Technician, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Sergeant, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Private_1st, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Med, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Corp, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_Uniform, 50, MISC_STOCK);
			ITEM(U_SPE_GER_tank_hbt_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_tank_hbt_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_tank_hbt_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Tank_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Tank_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Tank_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo, 50, MISC_STOCK);
			ITEM(U_SPE_ST_MGunner_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Medic_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo2, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Untersturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Standartenfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Obersturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Hauptsturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Unterofficier_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Mix_E44_roll, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Mix_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Sniper, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Sniper2, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo2, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_spring, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_spring_open, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_autumn_open, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_autumn, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_hbt_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_hbt_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_hbt_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Spg_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_GER_lehr_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_lehr_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_lehr_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_GER_lehr_private, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo_lieutenant_2, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo_lieutenant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Art_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Oberst, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Oberleutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Hauptmann, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot_weiss_alt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot_weiss, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot_alt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot_trop_alt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot_trop, 50, MISC_STOCK);
			ITEM(U_SPE_GER_LW_pilot, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Art_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Art_schutze, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_Unbloused, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_GER_MG_schutze, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Oberschutze, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Gefreiter_Gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_Gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo3, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo5, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo4, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo2, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo, 50, MISC_STOCK);
			ITEM(U_SPE_FR_Tank_Crew2, 50, MISC_STOCK);
			ITEM(U_SPE_FR_HBT_Uniform_Trop, 50, MISC_STOCK);
			ITEM(U_SPE_FR_HBT_Uniform, 50, MISC_STOCK);
			ITEM(U_SPE_FR_Tank_Crew3, 50, MISC_STOCK);
			ITEM(U_SPE_FR_Tank_Crew, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_4_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_4, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_3_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_3, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_2_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_2, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_1_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Worker_1, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_grijs_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_grijs, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_bruin_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_bruin, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_zwart_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_zwart_Alt, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Jacket_zwart, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_7_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_7, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_6_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_6, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_5_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_5, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_4_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_4, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_3_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_3, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_2_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_2, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_1_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FFI_Casual_1, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_4_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_4_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_4, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_3_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_3_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_3, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_2_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_2_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_2, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_1_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_1_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_1, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_3_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_3, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_2_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_2, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_1_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Worker_Coverall_1, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_5_vest, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_5, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_4_vest, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_4, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_3_vest, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_3, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_2_vest, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_2, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_1_vest, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Swetr_1, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_grijs_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_grijs_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_grijs, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_bruin_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_bruin_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_bruin, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_zwart_swetr, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_zwart_alt, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_zwart_tie_alt, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_zwart_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_pak2_zwart, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_7_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_7_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_7, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_6_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_6_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_6, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_5_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_5_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_5, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_4_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_4_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_4, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_3_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_3_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_3, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_2_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_2_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_2, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_1_trop, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_1_tie, 50, MISC_STOCK);
			ITEM(U_SPE_CIV_Citizen_1, 50, MISC_STOCK);

			ITEM(U_SPE_milice_1_CT, 50, MISC_STOCK);
			ITEM(U_SPE_milice_1_CR, 50, MISC_STOCK);
			ITEM(U_SPE_milice_1_CDA, 50, MISC_STOCK);
			ITEM(U_SPE_milice_1_CD, 50, MISC_STOCK);
			ITEM(U_SPE_milice_1, 50, MISC_STOCK);
			ITEM(U_SPE_milice_2, 50, MISC_STOCK);
			ITEM(U_SPE_milice_2_CR, 50, MISC_STOCK);
			ITEM(U_SPE_milice_2_CDA, 50, MISC_STOCK);
			ITEM(U_SPE_milice_2_CD, 50, MISC_STOCK);
			ITEM(U_SPE_milice_3_CT, 50, MISC_STOCK);
			ITEM(U_SPE_milice_3_CR, 50, MISC_STOCK);
			ITEM(U_SPE_milice_3_CDA, 50, MISC_STOCK);
			ITEM(U_SPE_milice_3_CD, 50, MISC_STOCK);
			ITEM(U_SPE_milice_3, 50, MISC_STOCK);
			ITEM(U_SPE_US_CC_EM_late_roll, 50, MISC_STOCK);

			ITEM(U_SPE_US_SC_EM_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_SC_EM_tie, 50, MISC_STOCK);
			ITEM(U_SPE_US_SC_EM, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43_hbt_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43_hbt_legging, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43_hbt, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43_legging, 50, MISC_STOCK);
			ITEM(U_SPE_US_M43, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_Half_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_late_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_Half, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_Med, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_FrogSkin_Jungle_Half, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_FrogSkin_Jungle_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_HBT44_tuck_FrogSkin_Jungle, 50, MISC_STOCK);
			ITEM(U_SPE_US_Tank_Coverall_Legging, 50, MISC_STOCK);
			ITEM(U_SPE_US_Private_trop, 50, MISC_STOCK);
			ITEM(U_SPE_US_Rangers_late, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_roll_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_flag, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_roll_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_506_knife, 50, MISC_STOCK);

			ITEM(U_SPE_US_AB_Uniform_M42_padded_506_glove_pfak, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_506_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_506_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_506, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_506_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_506_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_506, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_gas, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm_Medic_roll, 50, MISC_STOCK);

			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_arm, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_flag, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_flag, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_roll_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506_pfak, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506_knife, 50, MISC_STOCK);

			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove_pfak, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_506, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_glove_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_padded_CC2, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_flag, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_camo, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_Medic_roll, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_Medic_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42_glove, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M42, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag_arm_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag_arm_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag_arm, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag_knife, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_flag, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_Medic, 50, MISC_STOCK);
			ITEM(U_SPE_US_AB_Uniform_M43_knife, 50, MISC_STOCK);

			ITEM(U_SPE_US_AB_Uniform_M43, 50, MISC_STOCK);
			ITEM(U_SPE_ST_tank_E44_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_ST_tank_E44_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_tank_E44_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Tank_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Spg_crew_leutnant, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Spg_crew_unterofficer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Spg_crew_private, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Unbloused, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo3, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo5, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Boots_rolled, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo4, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_E44_Camo6, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Untersturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Untersturmfuhrer_flip, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Obersturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Obersturmfuhrer_flip, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Hauptsturmfuhrer, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo_Hauptsturmfuhrer_flip, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Sturmmann_E44, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Unbloused, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Boots_rolled, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_rolled, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Gaiters_closed, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_uscharf_gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_uscharf, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Unbloused, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Sturmmann_gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Sturmmann, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Boots_rolled, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_rolled, 50, MISC_STOCK);

			ITEM(U_SPE_ST_Soldier_M40_Gaiters_closed, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M40_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_m36_uscharf, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_m36_Sturmmann, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M36_Boots_rolled, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M36_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_M36_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo3_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo3, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo5_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo5, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo4_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo4, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo6_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo6, 50, MISC_STOCK);
			ITEM(U_SPE_ST_Soldier_Camo2_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_OST_2_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_OST_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_OST_roll, 50, MISC_STOCK);
			ITEM(U_SPE_OST_op, 50, MISC_STOCK);
			ITEM(U_SPE_OST_offz, 50, MISC_STOCK);
			ITEM(U_SPE_OST_2_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_OST_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_OST_2_roll, 50, MISC_STOCK);
			ITEM(U_SPE_OST_2_op, 50, MISC_STOCK);
			ITEM(U_SPE_OST_2, 50, MISC_STOCK);
			ITEM(U_SPE_OST_base, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_2_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_roll, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_op, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_offz, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_2_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_2_roll, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_2_op, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_2, 50, MISC_STOCK);
			ITEM(U_SPE_CSK_base, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2_Uffz, 50, MISC_STOCK);
			ITEM(U_SPE_LW_Uffz, 50, MISC_STOCK);
			ITEM(U_SPE_LW_roll, 50, MISC_STOCK);
			ITEM(U_SPE_LW_op, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_LW_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2_roll, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2_op, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2, 50, MISC_STOCK);
			ITEM(U_SPE_LW_2_Feldwebel, 50, MISC_STOCK);
			ITEM(U_SPE_LW_Feldwebel, 50, MISC_STOCK);
			ITEM(U_SPE_LW_base, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_mk3_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_mk3_roll, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_mk3_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_mk3, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_roll, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_LW_FSJ_base, 50, MISC_STOCK);

			ITEM(U_SPE_FSJ_mk3_sumpf_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_offz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_offz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_offz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_offz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_offz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_trop_roll, 50, MISC_STOCK);

			ITEM(U_SPE_FSJ_mk3_sumpf_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_sumpf, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_trop, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk3_split_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_uffz, 50, MISC_STOCK);

			ITEM(U_SPE_FSJ_mk2_split_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_split, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk2, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_gloves, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1_gefr, 50, MISC_STOCK);
			ITEM(U_SPE_FSJ_mk1, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Unterofficer_hbt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_MG_schutze_hbt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Schutze_hbt, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_Boots_Rolled, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Unbloused, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_uffz_gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Boots_Rolled, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Gefreiter_gaiters, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Gaiters_Rolled, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Gaiters_closed, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M40_Gaiters, 50, MISC_STOCK);

			ITEM(U_SPE_GER_Soldier_M40_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_m36_uffz, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M36_Boots_Rolled, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M36_Boots_open, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_m36_Gefreiter, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_M36_Boots, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo5_gaiter, 50, MISC_STOCK);
			ITEM(U_SPE_GER_Soldier_camo5_boot, 50, MISC_STOCK);
			////uniforms
		};

		class vestsspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_vests"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///vests
			ITEM(V_SPE_US_Vest_Thompson_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Thompson, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_pick, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_M1919, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Asst_MG, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Thompson_nco_Radio, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Thompson_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_off, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_nco_Radio, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Medic2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Medic3, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Grenadier, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Bar, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Bar_assist, 50, MISC_STOCK);
			ITEM(V_SPE_US_LifeVest, 50, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_rifle_M43, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_rifle, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_alt, 75, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_eng, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_Light, 75, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_dday_rifle, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_dday_rifle_M43, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_dday_eng, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_dday_Bag, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_dday, 75, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest_Bag, 100, MISC_STOCK);
			ITEM(V_SPE_US_Assault_Vest, 75, MISC_STOCK);
			ITEM(V_SPE_GER_TankPrivateBelt, 50, MISC_STOCK);
			ITEM(V_SPE_GER_PistolBelt, 50, MISC_STOCK);
			ITEM(V_SPE_GER_LW_Schwimm, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestUnterofficer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestSTG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_SniperBelt, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestMP40, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FWOVest, 50, MISC_STOCK);
			ITEM(V_SPE_GER_SaniVest, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_GER_PioneerVest, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FieldOfficer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestMG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_SaniVest2, 50, MISC_STOCK);
			ITEM(V_SPE_GER_VestG43, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_PioneerVest, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_SaniVest2, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestUnterofficer, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestSTG, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestMP40, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_FWOVest, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestMG, 50, MISC_STOCK);
			ITEM(V_SPE_DAK_VestG43, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_SMG_pouch, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_SMG_frag, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_SMG, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_rifle_pouch, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_rifle_frag, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_rifle, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_Pouch_frag, 50, MISC_STOCK);
			ITEM(V_SPE_FFI_Vest_Pouch, 50, MISC_STOCK);

			ITEM(V_SPE_milice_Vest_smg, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_rifle_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_Milice_Vest_rifle, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_MG_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_MG, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_zwart_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_zwart_rifle_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_zwart_rifle, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_zwart_MG_sidearm, 50, MISC_STOCK);
			ITEM(V_SPE_milice_Vest_zwart_MG, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_high, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_high, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_pick, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_M1919, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Asst_MG, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_high_off, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson_nco_Radio, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_high_off, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_off, 50, MISC_STOCK);

			ITEM(V_SPE_US_Vest_OD7_Carbine_nco_Radio, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Thompson_jfak_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Thompson_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_jfak_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_M1919_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_jfak_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_jfak_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Asst_MG_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson_jfak_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Thompson_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_jfak_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_M1919_jfak, 50, MISC_STOCK);

			ITEM(V_SPE_US_Vest_OD7_Carbine_jfak_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_jfak_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Asst_MG_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_jfak_off, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_45_jfak_off_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Carbine_jfak_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_jfak_off, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_45_jfak_off_m43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Carbine_jfak_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Medic_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak_knife, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak_knife, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Bar_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Bar_jfak_assist, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Bar_jfak, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Bar_jfak_assist, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_M43_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Garand_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Grenadier, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_M43_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Garand, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_Bar_M43, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Bar, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_OD7_Bar_assist, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_thompson, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_1, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_mk2, 50, MISC_STOCK);

			ITEM(V_SPE_US_Vest_AB_late_thompson, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_1, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_M1919, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_thompson, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_1, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_mk2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_M1919, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_2, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Grenadier, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_thompson_45_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_thompson_45_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_45_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_thompson_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_padded_Garand_medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_thompson_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_45_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_thompson_45_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_thompson_45_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_45_map, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_thompson_45, 50, MISC_STOCK);

			ITEM(V_SPE_US_Vest_AB_late_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_thompson_45_bag, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_late_medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_early_medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand_medic, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Grenadier, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand_45, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand_eng, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand_nco, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand_gp, 50, MISC_STOCK);
			ITEM(V_SPE_US_Vest_AB_Garand, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_Pio, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_NCO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_STG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_SMG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_FWO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_MG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_G43, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_pistol_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestFG42_Bandoleer_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_pistol_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_camo_VestKar98_Bandoleer_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_Sani2, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_NCO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_STG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_SMG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_FWO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_MG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_G43, 50, MISC_STOCK);

			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_pistol_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestFG42_Bandoleer_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_sumpf, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_split, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_pistol_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_VestKar98_Bandoleer_gelb, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_NCO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_STG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_SMG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_FWO, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_MG, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_G43, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_VestFG42_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_VestFG42_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_VestKar98_Bandoleer_pistol, 50, MISC_STOCK);
			ITEM(V_SPE_GER_FSJ_blau_VestKar98_Bandoleer, 50, MISC_STOCK);
			ITEM(V_SPE_erla_PioneerVest, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestUnterofficer, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestSTG, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestMP40, 50, MISC_STOCK);
			ITEM(V_SPE_erla_FWOVest, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestKar98, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestMG, 50, MISC_STOCK);
			ITEM(V_SPE_erla_SaniVest2, 50, MISC_STOCK);
			ITEM(V_SPE_erla_VestG43, 50, MISC_STOCK);
			ITEM(V_SPE_OST_sword, 50, MISC_STOCK);
			ITEM(V_SPE_OST_officer, 50, MISC_STOCK);
			///vests
		};
		
		class backpacksspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_backpacks"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///backpacks
			ITEM(B_SPE_US_Suspender_band_right, 50, MISC_STOCK);
			ITEM(B_SPE_US_Suspender_m43_open, 50, MISC_STOCK);
			ITEM(B_SPE_US_Suspender_m43, 50, MISC_STOCK);
			ITEM(B_SPE_US_Suspender_band_left, 50, MISC_STOCK);
			ITEM(B_SPE_US_Suspender_band, 50, MISC_STOCK);
			ITEM(B_SPE_US_Suspender_RocketBag, 100, MISC_STOCK);
			ITEM(B_SPE_US_Suspender, 5, MISC_STOCK);
			ITEM(B_SPE_US_MGbag, 50, MISC_STOCK);
			ITEM(B_SPE_US_Radio_alt, 500, MISC_STOCK);
			ITEM(B_SPE_US_Radio, 500, MISC_STOCK);
			ITEM(B_SPE_US_Radio_packboard_light, 500, MISC_STOCK);
			ITEM(B_SPE_US_Radio_packboard, 600, MISC_STOCK);
			ITEM(B_SPE_US_packboard_mortar, 600, MISC_STOCK);
			ITEM(B_SPE_US_packboard_eng, 600, MISC_STOCK);
			ITEM(B_SPE_US_packboard_ammo, 600, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_Mk2, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_pick, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_RocketBag_Empty, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M43_GP, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M43, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_dday, 200, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_roll_gp, 200, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_roll, 100, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_Bandoleer, 200, MISC_STOCK);
			ITEM(B_SPE_US_Backpack, 50, MISC_STOCK);
			ITEM(B_SPE_US_M36_Bandoleer, 75, MISC_STOCK);
			ITEM(B_SPE_US_M36, 100, MISC_STOCK);
			ITEM(B_SPE_US_RocketBag_Empty, 200, MISC_STOCK);
			ITEM(B_SPE_US_Bandoleer_3, 200, MISC_STOCK);
			ITEM(B_SPE_US_Bandoleer, 10, MISC_STOCK);
			ITEM(B_SPE_US_QAC, 300, MISC_STOCK);
			ITEM(B_SPE_US_TypeA3, 300, MISC_STOCK);
			ITEM(B_SPE_US_GP_Bag, 50, MISC_STOCK);
			ITEM(B_SPE_GER_Tonister41_Frame_Full, 100, MISC_STOCK);
			ITEM(B_SPE_GER_Tonister41_Frame, 75, MISC_STOCK);
			ITEM(B_SPE_GER_Tonister34_canvas, 50, MISC_STOCK);
			ITEM(B_SPE_GER_MedicBackpack_Empty, 50, MISC_STOCK);
			ITEM(B_SPE_GER_Tonister41_Frame_Full_ST, 75, MISC_STOCK);
			ITEM(B_SPE_GER_Tonister41_Frame_ST, 75, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_ST_zelt_trop, 25, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_ST_zelt, 25, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST_Full, 25, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST_zeltbahn_licht, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST_MGCan_zelt, 50, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST_MGCan, 50, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_ST_zeltbahn, 20, MISC_STOCK);
			ITEM(B_SPE_GER_Radio, 500, MISC_STOCK);
			ITEM(B_SPE_GER_Radio_battery, 500, MISC_STOCK);
			ITEM(B_SPE_GER_LW_Paradrop, 300, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag, 20, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_zelt_trop, 20, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_zelt, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_Full, 25, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_zeltbahn_licht, 25, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_sturm_licht, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_MGCan, 50, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_zeltbahn, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_sturm, 20, MISC_STOCK);
			ITEM(B_SPE_GER_A_frame_kit, 20, MISC_STOCK);
			ITEM(B_SPE_FFI_Gasbag, 40, MISC_STOCK);
			ITEM(B_SPE_CIV_musette, 45, MISC_STOCK);
			ITEM(B_SPE_CIV_satchel, 35, MISC_STOCK);
			ITEM(B_SPE_Milice_Radio, 35, MISC_STOCK);
			ITEM(B_SPE_Milice_Radio_battery, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M6_M43, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M6, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M43_Bandoleer, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_dday_eng, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_dday_m43, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_dday_side, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_dday_4ID, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M7_rear_bandoleer, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M7_rear, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M7_side_bandoleer, 35, MISC_STOCK);
			ITEM(B_SPE_US_Backpack_M7_side, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_Rope, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_Rocketbag, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_landing_m6, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_landing_m7, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_m6_Bandoleer, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_m6, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_m7_Bandoleer, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_m7, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_roll_2, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_roll, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_Bandoleer_mk2, 35, MISC_STOCK);
			ITEM(B_SPE_US_M36_Bandoleer_duplet, 35, MISC_STOCK);
			ITEM(B_SPE_US_T5_M6, 200, MISC_STOCK);//
			ITEM(B_SPE_US_T5_M7, 200, MISC_STOCK);
			ITEM(B_SPE_US_T5_erla, 200, MISC_STOCK);
			ITEM(B_SPE_ST_ammo_Belt_bag_zelt_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_ST_zelt_camo, 35, MISC_STOCK);
			ITEM(B_SPE_ST_RPzB_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_ST_Pzf_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_erla_bag_ST_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_ST_ammo_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag_zelt_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_Belt_bag_zelt_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Paradrop_gas, 200, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Paradrop, 200, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_ammo_Belt_bag_zelt_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_ammo_Belt_bag_camo, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_RPzB_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_RPzB_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Pzf_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Pzf_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Belt_bag_zelt_trop, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_ammo_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_ammo_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_FSJ_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_RPzB_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_RPzB_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_Pzf_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_Pzf_Belt_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag_medic, 35, MISC_STOCK);
			ITEM(B_SPE_GER_erla_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_erla_bag, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag_zelt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag_alt, 35, MISC_STOCK);
			ITEM(B_SPE_GER_ammo_Belt_bag, 35, MISC_STOCK);
			///backpacks
		};

		class facewearspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_facewear"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///facewear
			ITEM(G_SPE_GER_Headset, 50, MISC_STOCK);
			ITEM(G_SPE_Sunglasses_US_Yellow, 50, MISC_STOCK);
			ITEM(G_SPE_Sunglasses_US_Red, 50, MISC_STOCK);
			ITEM(G_SPE_Sunglasses_GER_Red, 50, MISC_STOCK);
			ITEM(G_SPE_Sunglasses_GER_Brown, 50, MISC_STOCK);
			ITEM(G_SPE_Pipe_Sir_Winston, 100, MISC_STOCK);
			ITEM(G_SPE_Polar_Goggles, 50, MISC_STOCK);
			ITEM(G_SPE_SWDG_Goggles, 50, MISC_STOCK);
			ITEM(G_SPE_Dust_Goggles, 50, MISC_STOCK);
			ITEM(G_SPE_Ful_Vue, 50, MISC_STOCK);
			ITEM(G_SPE_Ful_Vue_Reinforced, 50, MISC_STOCK);
			ITEM(G_SPE_Dust_Goggles_2, 50, MISC_STOCK);
			ITEM(G_SPE_Dienst_Brille, 50, MISC_STOCK);
			ITEM(G_SPE_Cigarette_Strike_Outs, 100, MISC_STOCK);
			ITEM(G_SPE_Cigarette_Grundstein, 100, MISC_STOCK);
			ITEM(G_SPE_Cigarette_Belomorkanal, 100, MISC_STOCK);
			ITEM(G_SPE_Cigar_Moza, 100, MISC_STOCK);
			ITEM(G_SPE_Binoculars, 50, MISC_STOCK);
			ITEM(G_SPE_GER_GM30, 50, MISC_STOCK);
			
			///facewear
		};