//below is used in vanilla aaf, rest should be added someday, starting with bluefor thar opfor etc.
["CUP_O_Tigr_233011_SLA",["hide_tow_rope",0.3,"hide_antenna_group",0.3,"hide_antenna_large",0.3,"hide_tools",0.3,"hide_Hoist",0.3,"hide_roof_rung",0.3,"hide_fueltanks",0.3,"hide_reseve_wheel_mount",0.3,"hide_ReserveWheel",0.3,"hide_Front_Bumper",0.3]],
["CUP_O_Tigr_M_233114_RU",["hide_tow_rope",0.3,"hide_antenna_group",0.3,"hide_antenna_large",0.3,"hide_tools",0.3,"hide_Hoist",0.3,"hide_roof_rung",0.3,"hide_fueltanks",0.3,"hide_reseve_wheel_mount",0.3,"hide_ReserveWheel",0.3,"hide_Front_Bumper",0.3,"hide_RoofCarrier",0.3,"hide_Gear_1",0.3,"hide_Gear_2",0.3,"hide_Gear_3",0.3,"hide_turret_shield",0.3]],
["CUP_I_LR_SF_GMG_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_wheels",0.3,"selection_bar",0.3,"selection_cut",0.3,"selection_doors",0.3]],
["CUP_I_LR_SF_HMG_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_wheels",0.3,"selection_bar",0.3,"selection_cut",0.3,"selection_doors",0.3]],
["CUP_O_Tigr_233014_PK_RU",["hide_turret_shield",0.3,"hide_pkm_shield",0.3,"hide_RoofCarrier",0.3,"hide_Gear_1",0.3,"hide_Gear_2",0.3,"hide_Gear_3",0.3,"hide_tow_rope",0.3,"hide_antenna_group",0.3,"hide_antenna_large",0.3,"hide_tools",0.3,"hide_Hoist",0.3,"hide_roof_rung",0.3,"hide_fueltanks",0.3,"hide_reseve_wheel_mount",0.3,"hide_ReserveWheel",0.3,"hide_Front_Bumper",0.3]],
["CUP_O_Tigr_M_233114_KORD_RU",["hide_turret_shield",0.3,"hide_kord_shield",0.3,"hide_RoofCarrier",0.3,"hide_Gear_1",0.3,"hide_Gear_2",0.3,"hide_Gear_3",0.3,"hide_tow_rope",0.3,"hide_antenna_group",0.3,"hide_antenna_large",0.3,"hide_tools",0.3,"hide_Hoist",0.3,"hide_roof_rung",0.3,"hide_fueltanks",0.3,"hide_reseve_wheel_mount",0.3,"hide_ReserveWheel",0.3,"hide_Front_Bumper",0.3]],
["CUP_O_Tigr_M_233114_PK_RU",["hide_turret_shield",0.3,"hide_pkm_shield",0.3,"hide_RoofCarrier",0.3,"hide_Gear_1",0.3,"hide_Gear_2",0.3,"hide_Gear_3",0.3,"hide_tow_rope",0.3,"hide_antenna_group",0.3,"hide_antenna_large",0.3,"hide_tools",0.3,"hide_Hoist",0.3,"hide_roof_rung",0.3,"hide_fueltanks",0.3,"hide_reseve_wheel_mount",0.3,"hide_ReserveWheel",0.3,"hide_Front_Bumper",0.3]],
["CUP_I_LR_MG_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_wheels",0.3,"selection_bar",0.3,"selection_tarp",0.3,"selection_doors",0.3,"selection_rear",0.3,"selection_wind",0.3]],
["CUP_O_LR_SPG9_TKA",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_bar",0.3,"selection_doors",0.3,"selection_rear",0.3,"selection_wind",0.3]],
["CUP_B_LR_Special_CZ_W",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_wheels",0.3,"selection_bar",0.3,"selection_cut",0.3,"selection_doors",0.3]],
["CUP_I_LR_Transport_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_bar",0.3,"selection_tarp",0.3,"selection_doors",0.3,"selection_rear",0.3,"selection_roll",0.3,"selection_wind",0.3]],
["CUP_I_M113A3_AAF",["hide_CIP_panels",0.3,"hide_Platoon_Markers",0.3,"hide_Deployment",0.3]],
["CUP_I_LR_AA_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_antenna_rear",0.3,"selection_box",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_bar",0.3,"selection_doors",0.3,"selection_rear",0.3,"selection_wind",0.3]],
["CUP_O_UAZ_Unarmed_SLA",["hide_spare_wheel",0.3,"hide_lower_tarp",0.3,"hide_upper_tarp",0.3,"hide_light_covers",0.3]],
["CUP_O_UAZ_AA_SLA",["hide_spare_wheel",0.5,"hide_light_covers",0.5]],
["CUP_O_UAZ_AGS30_SLA",["hide_spare_wheel",0.5,"hide_light_covers",0.5]],
["CUP_O_UAZ_METIS_SLA",["hide_spare_wheel",0.5,"hide_light_covers",0.5]],
["CUP_O_UAZ_Open_SLA",["hide_spare_wheel",0.5,"hide_light_covers",0.5]],
["CUP_O_UAZ_SPG9_SLA",["hide_spare_wheel",0.5,"hide_light_covers",0.5]],
["CUP_I_Wildcat_Unarmed_Digital_AAF",["hide_radar",0.3,"hide_struts",0.3,"mainRotor_folded",1,"mainRotor_unfolded",0]],
["CUP_I_Wildcat_Unarmed_Green_AAF",["hide_radar",0.3,"hide_struts",0.3,"mainRotor_folded",1,"mainRotor_unfolded",0]],
["CUP_I_M113A3_Reammo_AAF",["hide_CIP_panels",0.3,"hide_Platoon_Markers",0.3,"hide_Deployment",0.3]],
["CUP_I_M113A3_Repair_AAF",["hide_CIP_panels",0.3,"hide_Platoon_Markers",0.3,"hide_Deployment",0.3]],
["CUP_I_M113A3_Med_AAF",["hide_CIP_panels",0.3,"hide_Platoon_Markers",0.3,"hide_Deployment",0.3]],
["CUP_I_LR_Ambulance_AAF",["selection_tool",0.3,"selection_jerry",0.3,"selection_antenna",0.3,"selection_steps",0.3,"selection_wheelfront",0.3,"selection_bar",0.3,"selection_doors",0.3,"door_back_left",0.3,"door_back_right",0.3]]
//

