["gm_dk_army_typ1200_cargo", ["gm_drapolive",1]],
["gm_dk_army_typ253_cargo", ["gm_drapolive",1]],
["gm_ge_pol_w123", ["gm_darklblue",1]],
["gm_ge_pol_typ1200",["gm_saphireblue",1]],
["gm_gc_pol_p601", ["gm_kosmosblau",1]],
["gm_ge_pol_typ253",["gm_navyblue_damusowhite",1]],
["gm_ge_army_iltis_milan", ["gm_drapolive",1]],
["gm_ge_army_iltis_mg3", ["gm_drapolive",1]],
["gm_dk_army_typ247_cargo", ["gm_drapolive",1]],
["gm_ge_army_iltis_cargo", ["gm_drapolive",1]],
["gm_ge_army_u1300l_medic", ["gm_drapolive",1]],
["gm_ge_army_kat1_451_refuel", ["gm_drapolive",1]],
["gm_ge_army_u1300l_repair", ["gm_drapolive",1]],
["gm_ge_army_kat1_451_reammo", ["gm_drapolive",1]],
["gm_ge_army_kat1_454_reammo", ["gm_drapolive",1]],
["gm_dk_army_u1300l_container", ["gm_drapolive",1]],
["gm_ge_army_kat1_454_cargo", ["gm_drapolive",1]],
["gm_ge_army_kat1_451_container", ["gm_drapolive",1]],
["gm_ge_army_kat1_452_container", ["gm_drapolive",1]],
["gm_ge_army_u1300l_cargo", ["gm_drapolive",1]],
["gm_ge_army_kat1_451_cargo", ["gm_drapolive",1]],
["gm_dk_army_bpz2a0_noinsignia", ["gm_drapolive",1]],
["gm_dk_army_Leopard1a3_noinsignia", ["gm_drapolive",1]],
["gm_dk_army_m113a2dk_noinsignia", ["gm_drapolive",1]],
["gm_ge_army_bo105p1m_vbh_swooper_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2]],
["gm_ge_army_bo105p1m_vbh_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2]],
["gm_ge_army_bo105m_vbh_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2]],
["gm_ge_army_ch53gs_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_olo",0.2 ,"gm_ge_olu",0.2]],
["gm_ge_army_ch53g_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_olo",0.2 ,"gm_ge_olu",0.2]],
["gm_ge_army_fuchsa0_reconnaissance_noinsignia",["gm_drapolive",1]],
["gm_ge_army_fuchsa0_engineer_noinsignia",["gm_drapolive",1]],
["gm_ge_army_fuchsa0_command_noinsignia",["gm_drapolive",1]],
["gm_ge_army_marder1a2_noinsignia",["gm_drapolive",1]],
["gm_ge_army_marder1a1a_noinsignia",["gm_drapolive",1]],
["gm_ge_army_marder1a1plus_noinsignia",["gm_drapolive",1]],
["gm_ge_army_luchsa2_noinsignia",["gm_drapolive",1]],
["gm_ge_army_luchsa1_noinsignia",["gm_drapolive",1]],
["gm_ge_army_m113a1g_medic_noinsignia",["gm_drapolive",1]],
["gm_ge_army_m113a1g_command_noinsignia",["gm_drapolive",1]],
["gm_ge_army_m113a1g_apc_milan_noinsignia",["gm_drapolive",1]],
["gm_ge_army_m113a1g_apc_noinsignia",["gm_drapolive",1]],
["gm_ge_army_gepard1a1_noinsignia",["gm_drapolive",1]],
["gm_dk_army_bibera0_noinsignia",["gm_drapolive",1]],
["gm_dk_army_bpz2a0_noinsignia",["gm_drapolive",1]],
["gm_dk_army_m109_noinsignia",["gm_drapolive",1]],
["gm_dk_army_m113a1dk_engineer_noinsignia",["gm_drapolive",1]],
["gm_dk_army_m113a1dk_command_noinsignia",["gm_drapolive",1]],
["gm_dk_army_m113a1dk_apc_noinsignia",["gm_drapolive",1]],
["gm_dk_army_m113a2dk_noinsignia",["gm_drapolive",1]],
["gm_ge_army_Leopard1a1_noinsignia",["gm_drapolive",1]],
["gm_ge_army_Leopard1a1a2_noinsignia",["gm_drapolive",1]],
["gm_ge_army_Leopard1a3a1_noinsignia",["gm_drapolive",1]],
["gm_ge_army_Leopard1a5_noinsignia",["gm_drapolive",1]]