_initialRebelEquipment append [
    "gm_pm_blk",
    "gm_8Rnd_9x18mm_B_pst_pm_blk",
    "gm_photocamera_01_blk",
    "gm_df7x40_blk",
    "gm_ge_army_conat2",
    "gm_gc_compass_f73",
    "gm_watch_kosei_80",
    "gm_handgrenade_conc_dm51","gm_handgrenade_conc_dm51a1","gm_handgrenade_frag_dm41","gm_handgrenade_frag_dm41a1","gm_handgrenade_frag_dm51","gm_handgrenade_frag_dm51a1","gm_handgrenade_frag_m26",
    "gm_handgrenade_frag_m26a1", "gm_handgrenade_frag_rgd5",
    "gm_smokeshell_blk_gc","gm_smokeshell_blu_gc","gm_smokeshell_grn_gc","gm_smokeshell_org_gc","gm_smokeshell_red_gc","gm_smokeshell_wht_gc","gm_smokeshell_yel_gc","gm_smokeshell_grn_dm21",
    "gm_smokeshell_red_dm23","gm_smokeshell_wht_dm25","gm_smokeshell_yel_dm26","gm_smokeshell_org_dm32",
    ["gm_explosive_petn_charge", 10], ["gm_explosive_plnp_charge", 10],
    "gm_boltcutter",
    ["gm_rpg7_wud", 3], 
    ["gm_1Rnd_40mm_heat_pg7v_rpg7", 9],
    ["gm_1Rnd_40mm_heat_pg7vl_rpg7", 9]
];

_initialRebelEquipment append [
    "gm_ge_army_backpack_medic_80_oli",
    "gm_ge_backpack_satchel_80_blk",
    "gm_ge_backpack_satchel_80_san"
];

_dlcUniforms append [
    "gm_gc_civ_uniform_man_04_80_gry",
    "gm_gc_civ_uniform_man_04_80_blu",
    "gm_ge_dbp_uniform_suit_80_blu",
    "gm_gc_civ_uniform_man_03_80_gry",
    "gm_gc_civ_uniform_man_03_80_grn",
    "gm_gc_civ_uniform_man_03_80_blu",
    "gm_pl_airforce_uniform_pilot_80_gry",
    "gm_gc_airforce_uniform_pilot_80_blu",
    "gm_gc_civ_uniform_pilot_80_blk",
    "gm_xx_army_uniform_fighter_04_wdl",
    "gm_xx_army_uniform_fighter_01_oli",
    "gm_xx_army_uniform_fighter_01_alp",
    "gm_xx_army_uniform_fighter_01_m84",
    "gm_xx_army_uniform_fighter_02_wdl",
    "gm_xx_army_uniform_fighter_02_oli",
    "gm_xx_army_uniform_fighter_03_blk",
    "gm_xx_army_uniform_fighter_03_brn",
    "gm_xx_army_uniform_fighter_04_grn",
    "gm_ge_uniform_pilot_commando_rolled_oli",
    "gm_ge_uniform_pilot_commando_rolled_gry",
    "gm_ge_uniform_pilot_commando_rolled_blk",
    "gm_ge_uniform_pilot_commando_oli",
    "gm_ge_uniform_pilot_commando_gry",
    "gm_ge_uniform_pilot_commando_blk",
    "gm_ge_ff_uniform_man_80_orn",
    "gm_ge_army_uniform_soldier_parka_80_win",
    "gm_dk_army_uniform_soldier_84_win",
    "gm_ge_civ_uniform_blouse_80_gry",
    "gm_gc_civ_uniform_man_02_80_brn",
    "gm_gc_civ_uniform_man_01_80_blu",
    "gm_gc_civ_uniform_man_01_80_blk"
];

_dlcheadgear append [
    "gm_ge_headgear_beret_blk",
    "gm_ge_headgear_beret_un",
    "gm_ge_headgear_beret_mrb",
    "gm_ge_headgear_hat_boonie_trp",
    "gm_ge_headgear_hat_boonie_flk",
    "gm_dk_headgear_hat_boonie_m84",
    "gm_ge_headgear_hat_boonie_oli",
    "gm_ge_headgear_hat_boonie_wdl",
    "gm_ge_headgear_crewhat_80_blk",
    "gm_gc_army_headgear_crewhat_80_blk",
    "gm_ge_headgear_headset_crew_oli",
    "gm_ge_headgear_beret_crew_blk",
    "gm_gc_headgear_fjh_model4_oli",
    "gm_gc_headgear_fjh_model4_wht",
    "gm_xx_headgear_headwrap_01_trp",
    "gm_xx_headgear_headwrap_01_flk",
    "gm_xx_headgear_headwrap_01_blk",
    "gm_xx_headgear_headwrap_01_blu",
    "gm_xx_headgear_headwrap_01_smp",
    "gm_xx_headgear_headwrap_crew_01_trp",
    "gm_xx_headgear_headwrap_crew_01_flk",
    "gm_xx_headgear_headwrap_crew_01_blk",
    "gm_xx_headgear_headwrap_crew_01_smp",
    "gm_xx_headgear_headwrap_crew_01_grn",
    "gm_xx_headgear_headwrap_crew_01_m84",
    "gm_xx_headgear_headwrap_crew_01_oli",
    "gm_xx_headgear_headwrap_01_frog",
    "gm_xx_headgear_headwrap_01_grn",
    "gm_xx_headgear_headwrap_01_m84",
    "gm_xx_headgear_headwrap_01_moro",
    "gm_xx_headgear_headwrap_01_oli",
    "gm_xx_headgear_headwrap_01_str",
    "gm_xx_headgear_headwrap_01_wht",
    "gm_xx_headgear_headwrap_01_dino",
    "gm_ge_headgear_winterhat_80_oli",
    "gm_ge_headgear_hat_beanie_blk",
    "gm_ge_headgear_hat_beanie_crew_blk"
];

_loadoutData set ["facewearGM", [
    "gm_ge_facewear_acidgoggles",
    "gm_ge_facewear_dustglasses",
    "gm_gc_army_facewear_dustglasses",
    "gm_ge_facewear_m65",
    "gm_gc_army_facewear_schm41m",
    "gm_ge_facewear_glacierglasses",
    "gm_xx_facewear_scarf_01_trp",
    "gm_xx_facewear_scarf_01_flk",
    "gm_xx_facewear_scarf_01_blk",
    "gm_xx_facewear_scarf_01_blu",
    "gm_xx_facewear_scarf_01_pt1",
    "gm_xx_facewear_scarf_01_pt3",
    "gm_xx_facewear_scarf_01_frog",
    "gm_xx_facewear_scarf_01_grn",
    "gm_xx_facewear_scarf_01_gry",
    "gm_xx_facewear_scarf_01_m84",
    "gm_xx_facewear_scarf_02_blk",
    "gm_xx_facewear_scarf_01_grn",
    "gm_xx_facewear_scarf_01_oli",
    "gm_xx_facewear_scarf_01_wht",
    "gm_xx_facewear_scarf_01_moro",
    "gm_xx_facewear_scarf_01_oli",
    "gm_xx_facewear_scarf_01_red",
    "gm_xx_facewear_scarf_01_pt2",
    "gm_xx_facewear_scarf_01_str",
    "gm_xx_facewear_scarf_01_wht",
    "gm_ge_facewear_stormhood_blk",
    "gm_ge_facewear_stormhood_dustglasses_blk",
    "gm_ge_facewear_stormhood_brd",
    "gm_ge_facewear_sunglasses"
    ]
];