/// EXAMPLE ["US85_UH60", ["addESSS",0.5,"addWinch",0.5]],
["vn_b_armor_m113_01_aus_army", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m125_01_aus_army", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m577_02_aus_army", ["hide_fuel_cans",0.5,"hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m577_01_aus_army", ["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_b_wheeled_lr2a_mg_02_aus_army",["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_mg_03_aus_army", ["hide_sparewheel",0.3,"hide_axe",0.3,"hide_shovel",0.3]],
["vn_b_wheeled_lr2a_mg_01_aus_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_03_aus_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_02_aus_army", ["hide_sparewheel",0.3,"hide_axe",0.3,"hide_shovel",0.3]],
["vn_b_wheeled_lr2a_01_aus_army", ["hide_sparewheel",0.3,"hide_axe",0.3,"hide_shovel",0.3]],
["vn_b_wheeled_m54_03_aus_army", ["user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m151_mg_02_aus_army", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_06_aus_army", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_03_aus_army", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01_aus_army", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02_aus_army", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m54_repair_aus_army", ["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_fuel_aus_army", ["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_ammo_aus_army", ["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_aus_army", ["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02_aus_army", ["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_toolbox_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_armor_m113_acav_04", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_02", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_01", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_06", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_03", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_05", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_01", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m125_01", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m132_01", ["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m577_02", ["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_b_armor_m577_01", ["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_b_boat_12_02", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_12_04", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_12_01", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_12_03", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_13_02", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_13_04", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_13_01", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_13_03", ["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_b_boat_10_01", ["hide_clutter",0.3,"hide_d_engine_left",0.3,"hide_d_engine_right",0.3]],
["vn_b_boat_09_01", ["hide_clutter",0.3,"hide_d_engine_left",0.3,"hide_d_engine_right",0.3]],
["vn_b_boat_11_01", ["hide_clutter",0.3,"hide_d_engine_left",0.3,"hide_d_engine_right",0.3]],
["vn_b_wheeled_m54_03", ["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m151_mg_04", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_04_mp", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_02", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_02_mp",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_05", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02_mp", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01_mp",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m54_repair", ["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_repair_airport", ["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_fuel", ["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_fuel_airport", ["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_ammo", ["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_ammo_airport",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_mg_01",["user_sparewheel_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3]],
["vn_b_wheeled_m54_mg_03", ["user_sparewheel_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3]],
["vn_b_wheeled_m54_01",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_airport",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_sog",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02_sog", ["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_toolbox_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_toolbox_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_mg_02",["user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_03_usmc",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m151_mg_04_usmc", ["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_02_usmc",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_03_usmc",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01_usmc", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02_usmc", ["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m54_repair_usmc",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_fuel_usmc", ["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_ammo_usmc",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",0.3,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_usmc",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02_usmc",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_toolbox_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_armor_m48_01_01", ["hide_mainturret_ammobox",0.3,"hide_mainturret_backpacks",0.3,"hide_cable",0.3,"hide_mainturret_camp",0.3,"hide_mainturret_jerrycan",0.3,"hide_mainturret_tarpaulin",0.3,"hide_mainturret_tools",0.3,"hide_mainturret_tracks",0.3]],
["vn_b_armor_m67_01_01", ["hide_mainturret_ammobox",0.3,"hide_mainturret_backpacks",0.3,"hide_cable",0.3,"hide_mainturret_camp",0.3,"hide_mainturret_jerrycan",0.3,"hide_mainturret_tarpaulin",0.3,"hide_mainturret_tools",0.3,"hide_mainturret_tracks",0.3]],
["vn_b_armor_m48_01_02",["hide_mainturret_ammobox",0.3,"hide_mainturret_backpacks",0.3,"hide_cable",0.3,"hide_mainturret_camp",0.3,"hide_mainturret_jerrycan",0.3,"hide_mainturret_tarpaulin",0.3,"hide_mainturret_tools",0.3,"hide_mainturret_tracks",0.3]],
["vn_b_wheeled_lr2a_mg_02_nz_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_mg_03_nz_army",["hide_sparewheel",0.3,"hide_axe",0.3,"hide_shovel",0.3]],
["vn_b_wheeled_lr2a_mg_01_nz_army",["hide_sparewheel",0.3,"hide_axe",0.3,"hide_shovel",0.3]],
["vn_b_wheeled_lr2a_03_nz_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_02_nz_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_lr2a_01_nz_army", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_b_wheeled_m54_03_nz_army",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_armor_m113_acav_01_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_02_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_03_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_04_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_05_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_acav_06_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m113_01_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m125_01_rok_army",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_b_armor_m577_02_rok_army",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_b_armor_m577_01_rok_army",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_b_wheeled_m54_03_rok_army",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m151_mg_01_rok_army",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_02_rok_army",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_03_rok_army",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01_rok_army",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02_rok_army",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m54_repair_rok_army",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_fuel_rok_army",["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_ammo_rok_army",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",1,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_rok_army",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02_rok_army",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_03_rok_marines",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m151_mg_01_rok_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_02_rok_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_mg_03_rok_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_01_rok_marines",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m151_02_rok_marines",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_b_wheeled_m54_repair_rok_marines",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_b_wheeled_m54_fuel_rok_marines",["user_sparewheel_hide",0.5,"user_canopy_front_hide",0.5]],
["vn_b_wheeled_m54_ammo_rok_marines",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",1,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_01_rok_marines",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_b_wheeled_m54_02_rok_marines",["user_toolbox_hide",0.3,"user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
//
["vn_o_armor_m113_acav_01_kr",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_acav_02_kr",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_acav_03_kr",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_acav_06_kr",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_01_kr",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_wheeled_btr40_mg_02_kr",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01_kr",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04_kr",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02_kr",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01_kr",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_car_04_01_kr",["canopy_hide",0.3,"clutter_c_hide",0.7]],
["vn_o_car_04_mg_01_kr",["clutter_o_hide",0.5]],
["vn_o_wheeled_z157_ammo_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_kr",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_btr40_mg_02_pl",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01_pl",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04_pl",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_06_pl",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_05_pl",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_03_pl",["refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02_pl",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01_pl",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_z157_ammo_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_02_pl",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_armor_pt76a_01_pl",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tarpaulin",0.3,"hide_tracks",0.3]],
["vn_o_pl_static_type56rr",["hide_bushes1",0.3,"hide_bushes2",0.3,"hide_shells",0.3]],
["vn_o_armor_btr50pk_03_nva65",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_02_nva65",["hide_barrels",0.3,"hide_axe",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_01_nva65",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_03",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_02",["hide_barrels",0.3,"hide_axe",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_01",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_m113_acav_01",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_acav_03",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m113_01",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m125_01",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_o_armor_m577_02",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_o_armor_m577_01",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_o_armor_btr50pk_03_nvam",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_02_nvam",["hide_barrels",0.3,"hide_axe",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_armor_btr50pk_01_nvam",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tracks",0.3]],
["vn_o_wheeled_btr40_mg_02_nva65",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01_nva65",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04_nva65",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_06_nva65",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_05_nva65",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_03_nva65",["refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02_nva65",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01_nva65",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_z157_04_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_ammo_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_02_nva65",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_btr40_mg_02",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_06",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_05",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_03",["refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_z157_04",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_ammo",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_02",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_btr40_mg_02_nvam",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01_nvam",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04_nvam",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_06_nvam",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_05_nvam",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_03_nvam",["refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02_nvam",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01_nvam",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_z157_04_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_ammo_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_02_nvam",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_armor_ot54_01_nva65",["hide_mainturret_dshkm_boxes",0.3,"hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3]],
["vn_o_armor_pt76a_01_nva65",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tarpaulin",0.3,"hide_tracks",0.3]],
["vn_o_armor_pt76b_01_nva65",["hide_dshkm_boxes",0.3,"hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tarpaulin",0.3,"hide_tracks",0.3]],
["vn_o_armor_t54b_01_nva65",["hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3,"hide_mainturret_dshkm_boxes",0.3]],
["vn_o_armor_type63_01_nva65",["hide_axe",0.3,"hide_barrels",0.3,"hide_dshkm_boxes",0.3,"hide_shovel",0.3,"hide_tracks",0.3,"hide_cable",0.3,"hide_tarpaulin",0.3]],
["vn_o_armor_ot54_01",["hide_mainturret_dshkm_boxes",0.3,"hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3]],
["vn_o_armor_pt76a_01",["hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tarpaulin",0.3,"hide_tracks",0.3]],
["vn_o_armor_pt76b_01",["hide_dshkm_boxes",0.3,"hide_axe",0.3,"hide_barrels",0.3,"hide_cable",0.3,"hide_shovel",0.3,"hide_tarpaulin",0.3,"hide_tracks",0.3]],
["vn_o_armor_t54b_01",["hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3,"hide_mainturret_dshkm_boxes",0.3]],
["vn_o_armor_type63_01",["hide_axe",0.3,"hide_barrels",0.3,"hide_dshkm_boxes",0.3,"hide_shovel",0.3,"hide_tracks",0.3,"hide_cable",0.3,"hide_tarpaulin",0.3]],
["vn_o_wheeled_btr40_mg_02_vcmf",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_01_vcmf",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_04_vcmf",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_06_vcmf",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_05_vcmf",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_mg_03_vcmf",["refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_02_vcmf",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_btr40_01_vcmf",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_o_wheeled_z157_04_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_ammo_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_02_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_03_vcmf",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_car_04_mg_01",["clutter_o_hide",0.3]],
["vn_o_armor_ot54_01_vcmf",["hide_mainturret_dshkm_boxes",0.3,"hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3]],
["vn_o_armor_t54b_01_vcmf",["hide_log",0.3,"hide_tracks",0.3,"hide_mainturret_backpacks",0.3,"hide_mainturret_dshkm_boxes",0.3]],
//
["vn_i_armor_m113_acav_01",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_acav_02",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_acav_03",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_acav_04",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_acav_05",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_acav_06",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m113_01",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m125_01",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m132_01",["hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m577_02",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_armor_m577_01",["hide_fuel_cans",0.3,"hide_shovel",0.3,"hide_skirts",0.3]],
["vn_i_wheeled_m54_03",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_i_wheeled_m151_mg_01",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_01_mp",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_06",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_01",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_02",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_02_mp",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_01_mp",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m54_repair",["user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_fuel",["user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_ammo",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",1,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_01",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_02",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_03_marines",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_i_wheeled_m151_mg_01_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_02_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_06_marines",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_01_marines",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_02_marines",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m54_repair_marines",["user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_fuel_marines",["user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_ammo_marines",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",0,"user_bench_hide",1,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_01_marines",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_02_marines",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",0.3,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_armor_m48_01_01",["hide_mainturret_ammobox",0.3,"hide_mainturret_backpacks",0.3,"hide_cable",0.3,"hide_mainturret_camp",0.3,"hide_mainturret_jerrycan",0.3,"hide_mainturret_tarpaulin",0.3,"hide_mainturret_tools",0.3,"hide_mainturret_tracks",0.3]],
["vn_i_armor_m67_01_01",["hide_mainturret_ammobox",0.3,"hide_mainturret_backpacks",0.3,"hide_cable",0.3,"hide_mainturret_camp",0.3,"hide_mainturret_jerrycan",0.3,"hide_mainturret_tarpaulin",0.3,"hide_mainturret_tools",0.3,"hide_mainturret_tracks",0.3]],
["vn_i_armor_type63_01",["hide_axe",0.3,"hide_barrels",0.3,"hide_dshkm_boxes",0.3,"hide_shovel",0.3,"hide_tracks",0.3,"hide_cable",0.3,"hide_tarpaulin",0.3]],
["vn_i_armor_m113_acav_02_fank_71",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_i_armor_m113_acav_01_fank_71",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_i_armor_m113_acav_06_fank_71",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_i_armor_m113_acav_03_fank_71",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_i_armor_m113_01_fank_71",["hide_shovel",0.5,"hide_skirts",0.5]],
["vn_i_boat_12_02_fank_71",["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_i_boat_12_04_fank_71",["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_i_boat_12_01_fank_71",["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_i_boat_12_03_fank_71",["hide_fenders",0.3,"hide_canvas",0.3,"hide_clutter",0.3]],
["vn_i_wheeled_btr40_mg_02_fank_70",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_i_wheeled_btr40_mg_01_fank_70",["chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_i_wheeled_btr40_02_fank_70",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_i_wheeled_btr40_01_fank_70",["canopy_hide",0.3,"chairs_hide",0.3,"refuel_can_hide",0.3,"saw_hide",0.3,"sparewheel_hide",0.3,"shovel_hide",0.3,"toolbox_hide",0.3]],
["vn_i_wheeled_lr2a_mg_01_fank_71", ["hide_axe",0.3,"hide_shovel",0.3,"hide_sparewheel",0.3]],
["vn_i_wheeled_m151_mg_04_fank_71",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_01_fank_71",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_01_fank_71",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_02_fank_71",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_o_wheeled_z157_ammo_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_mg_01_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_fuel_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_repair_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_01_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_o_wheeled_z157_02_fank_70",["user_canopy_front_hide",0.3,"user_door_cover_left_hide",0.3,"user_door_cover_right_hide",0.3]],
["vn_i_wheeled_m54_03_rla",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_i_wheeled_m151_mg_01_rla",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_02_rla",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_mg_06_rla",["user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_01_rla",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m151_02_rla",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_i_wheeled_m54_repair_rla",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_i_wheeled_m54_fuel_rla",["user_canopy_front_hide",0.5,"user_sparewheel_hide",0.5]],
["vn_i_wheeled_m54_ammo_rla",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",1,"user_ammoboxes_hide",0,"user_bench_hide",1,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_01_rla",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",1,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
["vn_i_wheeled_m54_02_rla",["user_canopy_rear_hide",0.3,"user_canopy_rear_frame_hide",0.3,"user_canopy_rear_frame_02_hide",1,"user_ammoboxes_hide",1,"user_bench_hide",0,"user_toolbox_hide",0.3,"user_canopy_front_hide",0.3,"user_sparewheel_hide",0.3]],
//
["vn_c_wheeled_m151_01",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_c_wheeled_m151_02",["user_canopy_hide",0.3,"user_sparewheel_hide",0.3,"user_axe_hide",0.3,"user_shovel_hide",0.3,"user_refuel_can_hide",0.3]],
["vn_c_car_04_01",["canopy_hide",0.3,"clutter_c_hide",0.7]]