CONDITION_DEBUG = False

CONDITION_COMMON_TRUE = "true"
CONDITION_COMMON_FALSE = "false"

CONDITION_COMMON_OR_START = "("
CONDITION_COMMON_OR_END = ")"
CONDITION_COMMON_START = "{"
CONDITION_COMMON_END = "}"
CONDITION_COMMON_OR = "||"
CONDITION_COMMON_AND = "&&"
CONDITION_COMMON_ZONES = f"call A3U_fnc_sidesX"

CONDITION_TIER_LIGHT = "tierWar >= 3"
CONDITION_TIER_MEDIUM = "tierWar >= 6"
CONDITION_TIER_HEAVY = "tierWar >= 9"

CONDITION_RESOURCE_LIGHT = f"{CONDITION_COMMON_ZONES} count resourcesX >= 1"
CONDITION_RESOURCE_MEDIUM = f"{CONDITION_COMMON_ZONES} count resourcesX >= 3"
CONDITION_RESOURCE_HEAVY = f"{CONDITION_COMMON_ZONES} count resourcesX >= 5"

CONDITION_FACTORY_LIGHT = f"{CONDITION_COMMON_ZONES} count factories >= 1"
CONDITION_FACTORY_MEDIUM = f"{CONDITION_COMMON_ZONES} count factories >= 3"
CONDITION_FACTORY_HEAVY = f"{CONDITION_COMMON_ZONES} count factories >= 5"

CONDITION_MILBASE_LIGHT = f"{CONDITION_COMMON_ZONES} count milbases >= 1"
CONDITION_MILBASE_MEDIUM = f"{CONDITION_COMMON_ZONES} count milbases >= 2"
CONDITION_MILBASE_HEAVY = f"{CONDITION_COMMON_ZONES} count milbases >= 3"

CONDITION_AIRPORT_LIGHT = f"{CONDITION_COMMON_ZONES} count airportsX >= 1"
CONDITION_AIRPORT_MEDIUM = f"{CONDITION_COMMON_ZONES} count airportsX >= 2"
CONDITION_AIRPORT_HEAVY = f"{CONDITION_COMMON_ZONES} count airportsX >= 3"

CONDITION_SEAPORT_LIGHT = f"{CONDITION_COMMON_ZONES} count seaports >= 1"
CONDITION_SEAPORT_MEDIUM = f"{CONDITION_COMMON_ZONES} count seaports >= 2"
CONDITION_SEAPORT_HEAVY = f"{CONDITION_COMMON_ZONES} count seaports >= 3"

CONDITION_OUTPOST_LIGHT = f"{CONDITION_COMMON_ZONES} count outposts >= 1"
CONDITION_OUTPOST_MEDIUM = f"{CONDITION_COMMON_ZONES} count outposts >= 3"
CONDITION_OUTPOST_HEAVY = f"{CONDITION_COMMON_ZONES} count outposts >= 5"
CONDITION_OUTPOST_GIGANTIC = f"{CONDITION_COMMON_ZONES} count outposts >= 10"

# USAGE:
# print(f"{CONDITION_COMMON_OR_START}{CONDITION_SEAPORT_LIGHT} {CONDITION_COMMON_OR} {CONDITION_RESOURCE_MEDIUM}{CONDITION_COMMON_OR_END} {CONDITION_COMMON_AND} {CONDITION_FACTORY_MEDIUM}")
# RETURN:
# ({sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count seaports >= 1 || {sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count resourcesX >= 3) && {sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count factories >= 3