_civUniforms = [
  "U_lxWS_C_Djella_01",
  "U_lxWS_C_Djella_02",
  "U_lxWS_C_Djella_02a",
  "U_lxWS_C_Djella_03",
  "U_lxWS_C_Djella_04",
  "U_lxWS_C_Djella_05",
  "U_lxWS_C_Djella_06",
  "U_lxWS_C_Djella_07",
  "U_lxWS_Tak_01_A",
  "U_lxWS_Tak_01_B",
  "U_lxWS_Tak_01_C",
  "U_lxWS_Tak_02_A",
  "U_lxWS_Tak_02_B",
  "U_lxWS_Tak_02_C",
  "U_lxWS_Tak_03_A",
  "U_lxWS_Tak_03_B",
  "U_lxWS_Tak_03_C"
];
