class vehicles_vanilla : vehicles_base
{
    ITEM(B_APC_Tracked_01_AA_F, 43000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_APC_Tracked_02_AA_F, 43000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_LT_01_AA_F, 21000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_LT_01_scout_F, 3000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_APC_Wheeled_01_cannon_F, 20890, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_APC_Tracked_01_CRV_F, 12500, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_APC_Tracked_01_rcws_F, 22300, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_APC_Tracked_02_cannon_F, 31600, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_APC_Wheeled_02_rcws_v2_F, 21640, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_APC_Wheeled_03_cannon_F, 25970, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_APC_tracked_03_cannon_F, 23900, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_LT_01_cannon_F, 18500, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_LT_01_AT_F, 23750, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MRAP_01_gmg_F, 16300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MRAP_01_hmg_F, 11800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_LSV_01_AT_F, 21200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_LSV_01_armed_F, 8400, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_MRAP_02_gmg_F, 16450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_MRAP_02_hmg_F, 11950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_LSV_02_AT_F, 13000, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_LSV_02_armed_F, 6000, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_MRAP_03_gmg_F, 16300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_MRAP_03_hmg_F, 11800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_C_Offroad_02_AT_F, 6100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_C_Offroad_02_LMG_F, 2100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_G_Offroad_01_armed_F, 6100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_G_Offroad_01_AT_F, 4100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MBT_01_arty_F, 34100, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MBT_01_mlrs_F, 75900, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Ship_Gun_01_F, 66000, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Ship_MRLS_01_F, 309375, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MBT_02_arty_F, 34100, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_E_Truck_02_MRL_F, 69000, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_Boat_Armed_01_minigun_F, 17950, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(I_SDV_01_F, 1900, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(I_C_Boat_Transport_02_F, 2200, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(I_G_Boat_Transport_01_F, 1900, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(C_Scooter_Transport_01_F, 1100, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(C_Boat_Civil_01_F, 1200, "BOAT", "call A3U_fnc_sidesX count seaports >= 1");
    ITEM(B_Heli_Transport_03_unarmed_F, 12600, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Heli_Transport_03_F, 14100, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Heli_Attack_01_dynamicLoadout_F, 41160, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Heli_Light_01_dynamicLoadout_F, 26400, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Heli_Light_01_F, 9000, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Heli_Transport_01_F, 11700, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Attack_02_dynamicLoadout_F, 42475, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Light_02_unarmed_F, 9600, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Light_02_dynamicLoadout_F, 28800, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_F, 9000, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_ammo_F, 9000, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_fuel_F, 9000, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_repair_F, 9000, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_medevac_F, 10200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_bench_F, 11400, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_Heli_Transport_04_covered_F, 13800, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_Heli_light_03_unarmed_F, 10500, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_Heli_light_03_dynamicLoadout_F, 29340, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_Plane_CAS_01_dynamicLoadout_F, 100300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_Plane_Fighter_01_F, 97800, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_Plane_Fighter_01_Stealth_F, 85050, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_Plane_CAS_02_dynamicLoadout_F, 100300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_Plane_Fighter_02_F, 97000, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_Plane_Fighter_02_Stealth_F, 97000, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(I_C_Plane_Civil_01_F, 11600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(I_Plane_Fighter_04_F, 57300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(I_Plane_Fighter_03_dynamicLoadout_F, 44850, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_T_VTOL_01_armed_F, 84000, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_T_VTOL_01_iinfantry_F, 75700, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_T_VTOL_01_vehicle_F, 65500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_T_VTOL_02_infantry_dynamicLoadout_F, 93500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_T_VTOL_02_vehicle_dynamicLoadout_F, 89300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(I_static_AA_F, 7500, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_AAA_System_01_F, 40000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_SAM_System_01_F, 50000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_SAM_System_02_F, 60000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_SAM_System_03_F, 30000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Radar_System_01_F, 30000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_SAM_System_04_F, 30000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Radar_System_02_F, 30000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_static_AT_F, 7500, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_G_HMG_02_F, 3240, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_G_HMG_02_high_F, 3240, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Static_Designator_01_F, 7200, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_HMG_02_F, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_HMG_02_high_F, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_HMG_01_F, 4320, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_HMG_01_high_F, 4320, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_HMG_01_A_F, 8640, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_GMG_01_F, 7200, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_GMG_01_high_F, 7200, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_GMG_01_A_F, 14400, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Mortar_01_F, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_MBT_01_cannon_F, 51820, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_MBT_01_TUSK_F, 67780, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_MBT_02_cannon_F, 67180, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_MBT_02_railgun_F, 106780, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_MBT_04_cannon_F, 67180, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(O_MBT_04_command_F, 72460, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AFV_Wheeled_01_cannon_F, 45220, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AFV_Wheeled_01_up_cannon_F, 61180, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(I_MBT_03_cannon_F, 62200, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_UAV_05_F, 19400, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_UAV_02_dynamicLoadout_F, 28700, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_UGV_01_rcws_F, 17550, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(I_UGV_01_F, 12600, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_T_UAV_03_dynamicLoadout_F, 23350, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(O_T_UAV_04_CAS_F, 18100, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_MRAP_01_F, 1140, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_LSV_01_unarmed_F, 1250, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_transport_F, 2760, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_covered_F, 2700, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_Repair_F, 10100, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_medical_F, 7600, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_ammo_F, 7600, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_flatbed_F, 1800, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_cargo_F, 1800, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_mover_F, 650, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_Truck_01_fuel_F, 5100, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_MRAP_02_F, 1260, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_LSV_02_unarmed_F, 1250, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_transport_F, 2260, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_covered_F, 2200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_repair_F, 10100, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_medical_F, 7200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_fuel_F, 5100, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(O_Truck_03_ammo_F, 7600, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_MRAP_03_F, 1140, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Truck_02_transport_F, 2560, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Truck_02_covered_F, 2500, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Truck_02_fuel_F, 5200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Truck_02_medical_F, 7600, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Truck_02_box_F, 10200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Offroad_01_repair_F, 13500, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Offroad_01_F, 1280, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(C_Offroad_01_covered_F, 1120, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_C_Offroad_02_unarmed_F, 960, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Van_01_transport_F, 2325, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Van_01_fuel_F, 700, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Van_02_transport_F, 1880, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_G_Van_02_vehicle_F, 1910, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(C_Tractor_01_F, 550, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(I_Quadbike_01_F, 650, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
