class vehicles_scion : vehicles_base
{
    ITEM(SC_Ferret_AA_AR, 16500, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_AR_IFV, 23900, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SCEXT_Gator_APC_AR, 21368, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SSV_Vehicle_Android_APC, 20890, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SSV_Vehicle_Android_APC_Ruined, 21640, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_SE_IFV, 31600, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_SaurusAPC_SE, 19870, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_SaurusAPC_Unarmed_SE, 8700, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_Ferret_AR, 14500, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_Ferret_Autocannon_AR, 13000, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SCEXT_Dingo_A_AR, 7000, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SCEXT_Gator_TC_A_AR, 8800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_AR_Mrap, 11800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_SE_Mrap, 11950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SCEXT_Gator_ArtyGun_AR, 51150, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_EXT_Wyvern_AR, 10, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_ProwerClassCorvette_Helo, 204500, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_EXT_Comanche_AR, 12, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_VTOL_X41A_AR, 21750, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_VTOL_X42S_AR, 22950, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_Fixed_Bomber_01, 88500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SC_ProwlerClassCorvette_VTOL, 234500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SCR_TF3LInterceptor_AR, 84100, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SC_VTOL_X42_AR, 83500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SC_EXT_Vampire_AR, 94200, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SSV_Vehicle_Android_VTOL_Infantry, 93500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SSV_Vehicle_Android_VTOL_VIV, 89300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SCEXT_Grizzly_AR, 24600, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SC_AR_MBT, 62200, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SC_EXT_Rhino_AR, 37800, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SSV_Vehicle_Android_Tank, 62200, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(SSV_Drone_Cargo, 3000, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SC_ScoutAcolyte_base_F, 0, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(SCEXT_Dingo_AR, 1080, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SCEXT_Gator_Crate_AR, 7300, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SC_Gator_FB_AR, 1050, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SCEXT_Gator_Flatbed_Trans_AR, 2050, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SCEXT_Gator_Logistics_AR, 1050, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SC_Gator_TO_AR, 1200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(SSV_Vehicle_Android_Ifrit, 1260, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
