class vehicles_racs : vehicles_base
{
    ITEM(PRACS_SLA_BTR40_AAM, 16200, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_MTLB_ZU23, 8000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_MTLB_S60, 9000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_SA13, 17400, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_2S6M_Tunguska, 44800, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_SA9, 16200, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Type63_ADA, 8000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Ural_S60, 7200, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Ural_ZPU4, 5200, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_SA8, 49800, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_SA17, 55200, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M163_VADS, 17750, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M163_PIVADS, 18750, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M163_MACHBET, 31750, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M727_IHAWK, 23400, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M727_SEM_IHAWK, 25800, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_m48_chapparal, 33800, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M577, 3800, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Type63_AT, 13140, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Type63, 5800, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_Type63_AGS, 10000, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_Pizarro, 22200, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_Pizarro_SLE, 33450, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UK3CB_KDF_I_BTR40_MG, 5950, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_BTR40_AGS, 7800, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_BTR40_AT, 12450, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_HQ, 3100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_M2, 9700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_A3_M2, 12200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_A3_Mk19, 16700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_A3_M3_SFOD, 12050, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_A3_GA1, 16700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_ATGM, 41050, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_BMR_ATGM_TOW, 24175, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_BTR40_mortar, 18040, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_P3C, 48400, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_Mohawk, 53925, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_AN12B, 21000, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_F16CJ, 96600, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_A4M, 62100, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_MiG27, 62375, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_SU22, 103375, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M101, 10000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M102, 10000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M114, 13000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M1, 15000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M115, 18000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M198, 15000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_M46, 13000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_FV107, 26040, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_FV101, 22400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_VEC_M242, 24440, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_VEC_MGS, 37200, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M60A3, 42080, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_M60S, 47360, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_m548_open, 1640, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(PRACS_SLA_BTR40, 1320, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
};
