class vehicles_rhs : vehicles_base
{
    ITEM(rhs_gaz66_zu23_msv, 6000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Ural_Zu23_MSV_01, 6200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_zsu234_aa, 22000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_btr60_msv, 10412, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_btr70_msv, 10412, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_btr80_msv, 12012, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_btr80a_msv, 16448, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd1, 27045, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd1p, 28170, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd1pk, 15920, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd1r, 33420, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd2, 28670, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd4_vdv, 42338, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd4m_vdv, 42650, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmd4ma_vdv, 43130, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp1_tv, 26425, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp1p_tv, 27550, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp2_tv, 28950, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_brm1k_tv, 14800, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_Ob_681_2, 33450, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp3_late_msv, 43150, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp3m_msv, 44650, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_bmp3mera_msv, 45330, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_t15_tv, 2914179, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m113_usarmy_unarmed, 3600, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m113_usarmy_M240, 4500, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m113_usarmy_M2_90, 6500, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m113_usarmy, 6800, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m113_usarmy_MK19, 9500, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_stryker_m1126_m2_wd, 10676, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_stryker_m1126_mk19_wd, 15176, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_stryker_m1127_m2_wd, 9112, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_stryker_m1132_m2_np_wd, 11676, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_stryker_m1134_wd, 23859, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M2A2_wd, 34535, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M2A2_BUSKI_WD, 37883, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M2A3_wd, 36595, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M2A3_BUSKI_wd, 39571, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M2A3_BUSKIII_wd, 40315, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_M6_wd, 36223, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_nat_uaz_dshkm, 4100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_nat_uaz_spg9, 6100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_nat_uaz_ags, 7100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_tla_g_offroad_at, 6100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_tla_g_offroad_armed, 4100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhssaf_m1151_olive_pkm, 3050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhssaf_m1025_olive_m2, 4950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_tigr_sts_msv, 9100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1025_w_mk19, 10950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1045_w, 13450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m2crows_usarmy_wd, 10450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_mk19crows_usarmy_wd, 10950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m2_v1_usarmy_wd, 5250, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m2_lras3_v1_usarmy_wd, 9250, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m240_v1_usarmy_wd, 3050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_mk19_v1_usarmy_wd, 8550, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m2_v2_usarmy_wd, 5250, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_m240_v2_usarmy_wd, 3050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1151_mk19_v2_usarmy_wd, 8550, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_BRDM2_HQ, 3300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_BRDM2, 6900, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_BRDM2_ATGM, 13250, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_CGRCAT1A2_M2_usmc_wd, 5550, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_CGRCAT1A2_Mk19_usmc_wd, 8850, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1165a1_gmv_m134d_m240_socom_d, 9300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1165a1_gmv_m2_m240_socom_d, 7650, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1165a1_gmv_mk19_m240_socom_d, 10950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1117_W, 17100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1220_M153_M2_usarmy_wd, 11200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1220_M153_MK19_usarmy_wd, 15700, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1220_M2_usarmy_wd, 6150, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1220_MK19_usarmy_wd, 9450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1230_M2_usarmy_wd, 7150, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1230_MK19_usarmy_wd, 10450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1232_M2_usarmy_wd, 6150, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1232_MK19_usarmy_wd, 9450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1237_M2_usarmy_wd, 7150, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1237_MK19_usarmy_wd, 10450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1240a1_m2_usarmy_wd, 6250, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1240a1_m240_usarmy_wd, 4050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1240a1_mk19_usarmy_wd, 9550, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1240a1_m2crows_usarmy_wd, 11300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m1240a1_mk19crows_usarmy_wd, 15800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy, 6100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy, 4900, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1083A1P2_B_M2_WD_fmtv_usarmy, 6300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy, 4900, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy, 4900, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M977A4_BKIT_M2_usarmy_wd, 4900, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_BM21_MSV_01, 36600, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_2s1_tv, 26840, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_2s3_tv, 33440, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_m109_usarmy, 34100, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_M142_usarmy_WD, 83100, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_MELB_H6M, 12600, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_MELB_MH6M, 13800, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_MELB_AH6M, 28555, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH60M2, 11400, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH60M, 12300, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH60M_ESSS2, 24875, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH1Y_UNARMED, 13200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH1Y_FFAR, 18480, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_UH1Y, 19470, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_AH64D_wd, 37425, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_CH53E_USMC_D, 15900, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsusf_CH53E_USMC_GAU21_D, 19200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_CH_47F, 15900, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8T_vvs, 9200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8mt_vvs, 9600, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8mt_Cargo_vvs, 9200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8AMT_vvs, 9200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8AMTSh_vvs, 26400, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8mtv3_Cargo_vvs, 24700, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8MTV3_vvs, 25300, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi8MTV3_heavy_vvs, 27200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_ka60_grey, 14500, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi24V_vvs, 8, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhsgref_mi24g_CAS, 8, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_Mi24P_vvs, 8, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_mi28n_vvs, 3, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(RHS_AN2, 13600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsgred_hidf_cessna_o3a, 10600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHSGREF_A29B_HIDF, 33500, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_l39_cdf, 33300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_l159_CDF, 52725, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHS_Su25SM_vvs, 67875, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_mig29s_vvs, 81025, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_mig29sm_vvs, 89400, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHS_T50_vvs_generic, 83200, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHS_T50_vvs_generic_ext, 94400, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHS_A10, 73550, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_f22, 84475, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(RHS_Stinger_AA_pod_WD, 7500, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_Igla_AA_pod, 7500, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_ZU23, 5000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(RHS_TOW_TriPod_WD, 6750, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_SPG9, 4500, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_ins_g_SPG9M, 5000, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhssaf_army_metis_9k115, 6750, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhs_Kornet_9M133_2_vdv, 7500, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(RHS_M2StaticMG_WD, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(RHS_MK19_TriPod_WD, 6000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhssaf_army_m2staticmg_minitripod, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_DSHKM, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_AGS30_TriPod, 6000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_DSHKM_Mini_TriPod, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_nat_NSV_TriPod, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhs_KORD_VDV, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhs_KORD_high_VDV, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(RHS_M119_WD, 10000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_tla_g_2b14, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_cdf_reg_M252, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_cdf_reg_d30, 13000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_cdf_reg_d30_at, 14300, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhs_sprut_vdv, 41850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t72ba_tv, 46850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t72bb_tv, 56850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t72bc_tv, 66850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t72bd_tv, 72750, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t72be_tv, 78750, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t80, 35600, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t80b, 46850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t80bv, 58350, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t80ue1, 62650, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t90_tv, 61150, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t90saa_tv, 62650, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t90a_tv, 62650, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t90am_tv, 64850, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_t90sm_tv, 67050, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a1aimwd_usarmy, 65800, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a1aim_tuski_wd, 54100, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a2sep1wd_usarmy, 50400, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a2sep1tuskiwd_usarmy, 68400, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a2sep1tuskiiwd_usarmy, 74400, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhsusf_m1a2sep2wd_usarmy, 50800, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(rhs_pchela1t_vvsc, 12500, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(rhs_tigr_m_msv, 1740, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhs_tigr_msv, 1560, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhssaf_m1025_olive, 960, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsusf_CGRCAT1A2_usmc_wd, 1380, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsusf_M1220_usarmy_wd, 1680, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsusf_M1232_usarmy_wd, 1860, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsusf_m1240a1_usarmy_wd, 1140, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(rhsgref_BRDM2UM, 1440, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
