class CUP_NorAF_Vehicles : vehicles_base
{
    ITEM(Flex_CUP_NOR_Dingo_MG, 9100, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(Flex_CUP_NOR_Dingo_GL, 16600, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(Flex_CUP_NOR_M113A3, 6600, APC, VEHICLE_CONDITION_APC);

    ITEM(Flex_CUP_NOR_Leopard2A6, 49000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(Flex_CUP_NOR_F35B, 105725, PLANE, VEHICLE_CONDITION_PLANE);

    ITEM(Flex_CUP_NOR_Bell412_Transport, 14000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Utility, 13400, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Radar, 13400, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Merlin_HC3, 12000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_MH60S_Unarmed, 12000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Armed, 18300, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Armed_AT, 22500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_dynamicLoadout, 23975, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_MH60S_Armed, 27895, HELI, VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Merlin_HC3_Armed, 17100, HELI, VEHICLE_CONDITION_HELI);
};