class vehicles_jcals : vehicles_base
{
    ITEM(E22_B_JC_W_Radar_system_01_F, 30000, "STATICAA", VEHICLE_CONDITION_STATICAA)
    ITEM(E22_B_JC_W_SAM_system_01_F, 60000, "STATICAA", VEHICLE_CONDITION_STATICAA)
    ITEM(E22_B_JC_W_AAA_System_01_F, 40000, "STATICAA", VEHICLE_CONDITION_STATICAA)
};
