class vehicles_pedagne : vehicles_base
{
    ITEM(ASZ_SuperAV_EI_battlefield, 34050, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_SuperAV_EI_Command, 14980, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VCC1_EI_plus, 14800, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_LR90_M2, 5700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_LR90_MK19, 8100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_LR90_TOW, 14100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VM90spop, 8900, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VM90_EI_P, 2600, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VM90_EI_M2, 4600, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA4x4CC_MG3, 2300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA4x4_M2, 4200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA4x4_TOW, 8700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA6x6_AT, 18150, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA6x6CC_MG3, 2500, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA6x6_hitrole, 11400, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_PUMA6x6_M2, 4400, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_Cougar_6x6, 4900, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VTML_hitrole_LR, 11300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_VTML_M2_Protect, 4300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_cougar_armed, 12000, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_cougar, 8400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_ch47_mg_cargo, 6100, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_ch47_mg, 13600, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_ec135, 9500, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_famet_tigre, 31220, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_nh90_nfh_transport, 22300, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_nh90_tth_armed, 15100, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_nh90_tth_cargo, 10000, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(ffaa_nh90_tth_transport, 16000, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(asz_spikeLR_tripode, 7500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_Centauro_B1, 43100, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_Ariete, 46700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(ASZ_Ariete_plus, 61700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
};
