class vehicles_rf : vehicles_base
{
    ITEM(I_Pickup_aat_rf, 11000, "AA", VEHICLE_CONDITION_AA);
    ITEM(B_Pickup_mmg_rf, 3900, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_Pickup_hmg_rf, 4500, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_G_Pickup_hmg_rf, 4620, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_G_Pickup_mrl_rf, 22400, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(a3a_black_Heli_EC_02_RF, 34145, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(I_Heli_EC_01A_military_RF, 15200, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(a3a_black_Heli_light_03_dynamicLoadout_RF, 29625, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(B_Heli_EC_03_RF, 32550, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(a3a_green_Heli_light_03_unarmed_RF, 12300, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(B_Heli_EC_04_military_RF, 17700, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(C_Heli_EC_01A_civ_RF, 11700, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(C_Heli_EC_01_civ_RF, 11820, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(C_Heli_EC_04_rescue_RF, 14100, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(I_G_CommandoMortar_RF, 5000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(I_TwinMortar_RF, 14000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(I_G_Pickup_rf, 1300, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(B_Pickup_Comms_rf, 1300, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Pickup_repair_rf, 6300, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Truck_01_water_rf, 650, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Truck_03_water_rf, 650, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
