class vehicles_lawsofwar : vehicles_base
{
    ITEM(I_UAV_06_medical_F, 11500, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(I_UAV_06_F, 14000, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(C_IDAP_UAV_06_antimine_F, 14000, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(I_G_Van_02_transport_F, 1820, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_G_Van_02_vehicle_F, 1840, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Van_02_medevac_F, 6500, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Van_02_service_F, 9400, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
