class vehicles_ffp : vehicles_base
{
    ITEM(ffp_bmp2, 20700, "APC", VEHICLE_CONDITION_APC);
    ITEM(ffp_bmp2_atgm, 31950, "APC", VEHICLE_CONDITION_APC);
    ITEM(ffp_cv9030, 19720, "APC", VEHICLE_CONDITION_APC);

    ITEM(ffp_rsrakh06, 75900, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);

    ITEM(ffp_122h63, 13000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);

    ITEM(ffp_gruppbat, 1900, "BOAT", VEHICLE_CONDITION_BOAT);

    ITEM(ffp_van_ambulance, 1100, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_bv206, 2100, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_rg32m, 1200, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_susi8x8_ammo, 7700, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_susi_sa420, 2450, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_susi_sa420_covered, 2450, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_susi_sa420_repair, 7800, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(ffp_susi_sa420_fuel, 7800, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(ffp_orbiter, 12500, "UAV", VEHICLE_CONDITION_UAV);

    ITEM(ffp_md500, 6900, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(ffp_nh90, 11000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(ffp_nh90_armed, 11990, "HELI", VEHICLE_CONDITION_HELI);

    ITEM(ffp_jas39e, 94300, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(ffp_jas39e_rb15, 94300, "PLANE", VEHICLE_CONDITION_PLANE);

    ITEM(ffp_leopard2a4, 48000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(ffp_leopard2a6, 48000, "TANK", VEHICLE_CONDITION_TANK);

    ITEM(ffp_23itk61, 5000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(ffp_ito2005m, 7500, "STATICAA", VEHICLE_CONDITION_STATICAA);

    ITEM(ffp_pstohj83, 7500, "STATICAT", VEHICLE_CONDITION_STATICAT);
};
