class vehicles_hafm : vehicles_base
{
    ITEM(HAFM_GD240_Unarmed2, 900, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(HAFM_HMMWV1, 900, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(HAFM_VBL2, 1080, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(Unimog1550_Covered2, 1750, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);//ADDED NODES
    ITEM(Unimog1550_SemiCovered2, 1750, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);//DIDNT ADD NODES SINCE SEATS WERE IN WAY
    //HAS AMMO AND FUEL TRUCK BUT THEY ARE TECHNICALLY NOT AN AMMO AND FUEL TRUCK SO NOT ADDING THEM TO A.D. ¯\_(ツ)_/¯

    ITEM(HAFM_GD240_Patrol2, 2400, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_HMMWV1_M2, 4400, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_HMMWV1_MK19, 7400, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_HMMWV1_Kornet, 11900, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_HMMWV1_Milan, 12900, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);//This one has Rearming Capability For Whatever Reason. I think Mod Author meant to put -1 instead of 1
    ITEM(HAFM_HMMWV1_TOW, 8900, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_VBL2_M50, 5400, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(HAFM_VBL2_M240, 3100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);

    ITEM(Leonidas2_2, 6700, "APC", VEHICLE_CONDITION_APC);
    ITEM(Leonidas3_BLU, 31850, "APC", VEHICLE_CONDITION_APC);
    ITEM(blx_M1117_GR, 20060, "APC", VEHICLE_CONDITION_APC);

    ITEM(Leopard1A4_2, 41000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(M60A3_2, 44000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(Leopard2A4_2, 41000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(Leopard2A6HEL_2, 46000, "TANK", VEHICLE_CONDITION_TANK);

    ITEM(HAFM_Naval_RHIB, 2100, "BOAT", VEHICLE_CONDITION_BOAT);//Never thought I'd see the day where I'm putting boats into the Arms Dealer
    ITEM(HAFM_Naval_CB90_BLU, 53630, "BOAT", VEHICLE_CONDITION_BOAT);

    ITEM(A7BLU, 67900, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(A7BLU_TIGER, 67900, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(F16C_BLU, 95200, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(F16_B52_BLU, 95200, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(F4E_BLU, 68500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(F4E_BLU_AG, 68500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(M2000C_BLU, 90250, "PLANE", VEHICLE_CONDITION_PLANE);
    
    ITEM(HAFM_UH1H, 9960, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(HAFM_Kiowa, 19060, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(HAFM_Kiowa_AT, 19225, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(NH90_GR2, 11000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(NH90Armed_GR2, 11990, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(CH_47F_BLU, 15390, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(HAFM_AH64D, 29025, "HELI", VEHICLE_CONDITION_HELI);

    ITEM(GR_MBT_mlrs, 69000, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);

    ITEM(HAFM_Pegasus, 12500, "UAV", VEHICLE_CONDITION_UAV);
};
