class vehicles_qav : vehicles_base
{
    ITEM(qav_brdm2, 11040, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    
    ITEM(qav_bmp1, 13240, "APC", VEHICLE_CONDITION_APC);
    ITEM(qav_bmp1_am, 15600, "APC", VEHICLE_CONDITION_APC);
    ITEM(qav_bmp1_am_p, 12740, "APC", VEHICLE_CONDITION_APC);
    ITEM(qav_bmp1_p, 19240, "APC", VEHICLE_CONDITION_APC);

    ITEM(QAV_T54, 40500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_T72A, 41500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_T90A, 59500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_su76, 28000, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_ztl11, 34500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_challenger2, 44500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_challenger2_e, 49300, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_merkava_mk2B, 48500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_merkava_mk2D, 54500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_merkava_mk3b, 48500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_abramsx, 60200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_abramsx_tusk, 63500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_abramsx_templar, 63500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(qav_abramsx_zeus, 94780, "TANK", VEHICLE_CONDITION_TANK);

    ITEM(qav_625e, 23250, "AA", VEHICLE_CONDITION_AA);

    ITEM(qav_ripsaw_Mk44, 17250, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(qav_ripsaw_c, 14100, "UAV", VEHICLE_CONDITION_UAV);
};
