class vehicles_csa38 : vehicles_base
{
    ITEM(CSA38_8rad2, 10300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_8rad, 10300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzbfwI, 4500, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_TCvz33, 5500, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(csa38_pak35, 4500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(csa38_KPUV37, 4500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_MG34t, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_brenmkiit, 2700, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_brenmkiit2, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_TKVZ37MG, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_TKVZ24mg, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(csa38_GrW34, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_2inch_vehicle, 7000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_mvz36, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_mvz17, 9000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_StugIII, 28400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzIVcv38, 32800, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzIIID, 30600, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzIIIC, 30600, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzII, 17900, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzkpfwI, 11300, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_pzkpfwIA, 11300, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_ltm35_FR, 23400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_ltm38_FR, 25600, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_ltvz34, 23400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(csa38_matildaii_1, 30400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(csa38_matildaiiCS_1, 34800, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(csa38_m3a3, 27300, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(csa38_m5, 27300, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(csa38_valentine_MkIIgreen, 29800, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_R2Tacam, 30000, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(CSA38_opelblitz, 1700, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
};
