class vehicles_scifitp : vehicles_base
{
    //Anti-Air
    ITEM(PHEN_TurretPack_B_Turret_05, 60000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(PHEN_TurretPack_B_Turret_02, 60000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(PHEN_TurretPack_B_Turret_03, 40000, "STATICAA", VEHICLE_CONDITION_STATICAA);

    //Anti-Tank
    ITEM(PHEN_TurretPack_B_Turret_06_cannon, 10000, "STATICAT", VEHICLE_CONDITION_STATICAT);
    ITEM(PHEN_TurretPack_B_Turret_05_AT, 9750, "STATICAT", VEHICLE_CONDITION_STATICAT);

    //Artillery
    ITEM(PHEN_TurretPack_B_Turret_06, 16500, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);

    //Anti-Infantry
    ITEM(PHEN_TurretPack_B_Turret_01, 12600, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(PHEN_TurretPack_B_Turret_01_GAU, 16200, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(PHEN_TurretPack_B_Turret_04, 16200, "STATICMG", VEHICLE_CONDITION_STATICMG);

    //Railgun
    ITEM(PHEN_TurretPack_B_Plasma_Turret_03, 15000, "STATICAT", VEHICLE_CONDITION_STATICAT);
};
