class vehicles_ifa3 : vehicles_base
{
    ITEM(LIB_SdKfz_7_AA, 12750, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_FlakPanzerIV_Wirbelwind, 22000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_Zis5v_61K, 6200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_SdKfz_7, 3600, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_SdKfz251, 5080, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_SdKfz251_FFV, 5080, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_Scout_M3, 6456, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_Scout_M3_FFV, 6456, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_SOV_M3_Halftrack, 7200, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_UniversalCarrier, 4650, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_Kfz1_MG42, 2100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_US_Willys_MB_M1919, 2100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_SdKfz124, 23100, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_US6_BM13, 39600, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(LIB_FW190F8, 15250, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Ju87, 16000, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Li2, 19600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_P39, 13850, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Pe2, 16650, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_C47_Skytrain, 19600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_HORSA, 12200, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_CG4_WACO, 9200, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_P47, 19750, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_FlaK_30, 3000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_FlaK_38, 5000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Flakvierling_38, 11250, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_FlaK_36_AA, 8000, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_61k, 4500, "STATICAA", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Pak40, 5000, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_FlaK_36, 8000, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_leFH18_AT, 9000, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Zis3, 5000, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_MG42_Lafette_low_Deployed, 3000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_MG34_Lafette_low_Deployed, 3000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_MG42_Lafette_Deployed, 3000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_MG34_Lafette_Deployed, 3000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Maxim_M30_base, 2700, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Maxim_M30_Trench, 2700, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_M1919_M2, 3000, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_GrWr34, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_leFH18, 14300, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_FlaK_36_ARTY, 10400, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Nebelwerfer41, 13000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_BM37, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_M2_60, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_StuG_III_G, 27600, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_PzKpfwIV_H, 32000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_PzKpfwV, 37000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_PzKpfwVI_E, 41200, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_PzKpfwVI_B, 52000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_SU85, 27500, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_T34_76, 32000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_T34_85, 35000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_JS2_43, 44900, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Cromwell_Mk4, 32000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Churchill_Mk7, 34000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Churchill_Mk7_AVRE, 40600, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Churchill_Mk7_Crocodile, 39500, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Churchill_Mk7_Howitzer, 41700, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M3A3_Stuart, 26500, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M5A1_Stuart, 27500, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M4A3_75, 32000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M4A3_75_Tubes, 34000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M4A3_76, 39500, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M4A3_76_HVSS, 42600, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_M4A4_FIREFLY, 46000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(LIB_Kfz1, 800, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Kfz1_Hood, 850, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Willys_MB, 800, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Willys_MB_Hood, 850, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(LIB_Willys_MB_Ambulance, 900, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
