class vehicles_unsung : vehicles_base
{
    ITEM(uns_m163, 11500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_ZU, 10500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_BTR152_ZPU, 9500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_zpu, 9000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_zu23, 10000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_type65, 12000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_s60, 13000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_transport, 2880, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_M60, 4580, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_30cal, 5780, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_M2, 6980, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_XM182, 10580, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_M134, 8180, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113A1_M60, 6140, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113A1_M2, 8740, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113A1_M40, 13340, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113A1_M134, 9740, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M132, 13520, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_BTR152_DSHK, 6280, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type63_mg, 6300, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_pt76, 13000, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_willysmg, 2100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_willysmg50, 4100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_willysm40, 6100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_willys_2_m60, 2200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_willys_2_m1919, 3000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_m274_m60, 2300, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_m274_m40, 6000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_m37b1_m1919, 2950, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_xm706e1, 3920, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_xm706e2, 6160, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_LMG, 2760, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_MG, 4760, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_patrol, 5540, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_twinMG, 7430, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_RR57, 6100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_RR73, 6100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_M40, 6100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_mg, 4070, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_M113_M30, 23320, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_m107sp, 57750, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_m110sp, 66990, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55_mortar, 18040, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UNS_Zodiac_W, 1500, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_pbr, 11700, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_pbr_mk18, 17700, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_PBR_M10, 17700, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(UNS_PATROL_BOAT_NVA, 5800, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(UNS_ASSAULT_BOAT_VC, 8800, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(UNS_VC_sampan_large, 1500, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(UNS_VC_sampan_fish1, 1300, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(UNS_VC_sampan_cargo, 1700, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_H13_transport_Army, 7950, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_H13_amphib_Army, 7100, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_H13_gunship_Army, 8500, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ch34_army, 11300, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ch34_army_M60, 10950, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_uh34_USMC, 13250, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_h21c, 13400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_h21c_mg, 13700, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ch54_army, 6500, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ch47_m60_army, 16000, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ach47_m134, 23100, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_ach47_m200, 23100, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_rh53a_m2_usn, 17900, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_oh6_transport, 5300, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_oh6_m60, 5550, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_oh6_m27r, 12150, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_oh6_m27, 7750, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_oh6_xm8, 8300, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1D_m60, 10900, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1B_TOW, 16280, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M21_M158, 22600, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M21_M158_M134, 25900, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M21_M200, 22600, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M3_ARA, 16500, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M6_M200_1AC, 20400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M6_M158, 20400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M6_M200, 20400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_UH1C_M6_M200_M134, 23700, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UNS_AH1G, 29150, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UNS_AH1G_FFAR, 29150, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UNS_AH1G_M200, 29150, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(UNS_AH1G_SUU11, 29150, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Mi8T_VPAF, 12500, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_Mi8T_VPAF_MG, 13000, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(uns_A1J_CAS, 45500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_c1a6, 23200, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(UNS_skymaster_CAS, 27500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_A4B_skyhawk_CAS, 32300, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_F4E_CAS, 47500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_A6_Intruder_CAS, 35750, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_A7_CAS, 42500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_f8e_USMC_CAS, 34250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_ov10_usaf_CAS, 44250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_a37, 34500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_b52h, 48000, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_f100B_CAS, 41500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_f105D_CAS, 39500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(UNS_F111_D_CAS, 52750, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_C130_H, 27700, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_an2_transport, 29500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_Mig21_CAS, 43450, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(Uns_M55_Quad, 4000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_ZPU2_NVA, 5000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_ZPU4_NVA, 7000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_ZU23_NVA, 6000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type74_NVA, 6000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_S60_NVA, 6000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_KS19_NVA, 8000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_KS12_NVA, 6000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M40_106mm_US, 5000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type36_57mm_NVA, 4500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_SPG9_73mm_NVA, 5000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m60_high, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m2_high, 3600, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_US_MK18_low, 6000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_dshk_high_NVA, 3600, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_dshk_twin_NVA, 7200, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_pk_high_NVA, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M2_60mm_mortar, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M1_81mm_mortar, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M30_107mm_mortar, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(Uns_M102_artillery, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(Uns_M114_artillery, 15000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m1941_82mm_mortarNVA, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(Uns_D30_artillery, 13000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(Uns_D20_artillery, 15000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m551, 41400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_m48a3, 43400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_M67A, 46600, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_t34_76_vc, 33700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_t34_85_nva, 35900, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_ot34_85_nva, 40300, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_t54_nva, 42000, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_t55_nva, 38700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_to55_nva, 48600, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(uns_willys, 800, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_willys_2, 800, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m274, 900, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_m37b1, 1525, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M35A2, 1850, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_M35A2_Open, 1850, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_Type55, 1210, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck, 2150, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_nvatruck_open, 2150, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(uns_zil157, 2050, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
};
