class vehicles_fow : vehicles_base
{
    ITEM(fow_v_sdkfz_250_ger_heer, 3900, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_sdkfz_251_camo_ger_heer, 4500, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_universalCarrier, 4800, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_lvta2_usa, 7300, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_kubelwagen_mg34_ger_heer, 2100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_sdkfz_222_ger_heer, 5200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_sdkfz_234_1, 5200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_sdkfz_250_9_ger_heer, 5200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(fow_usa_lcvp, 5450, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_va_a6m_green, 13500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_va_f6f, 14000, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_va_f6f_c, 15500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_pak40_gray_ger_heer, 5000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_flak36_gray_ger_heer, 8000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_6Pounder_uk, 9000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_mg42_deployed_high_ger_heer, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_vickers_uk, 2700, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_m1919a6_deployed_high_usa_m41, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_type97_mortar_ija, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_w_m2_mortar_usa, 8000, "STATICMORTAR", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_ija_type95_HaGo_1_ija, 21200, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_panther_ger_heer, 37000, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_m5a1_usa, 23400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_cromwell_uk, 29800, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_m4a2_usa, 30900, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_kubelwagen_ger_heer, 800, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_type97_truck_open_ija, 1850, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_type97_truck_ija, 1850, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(fow_v_willys_usa, 1000, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
};
