class vehicles_amf : vehicles_base
{
    ITEM(AMF_EBRC_CE_01, 23750, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBCI_CE_01_F, 16868, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBMR_COMMANDEMENT_CE, 13300, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBMR_GENIE_CE, 15451, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBMR_HMG_CE, 13915, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBMR_SAN_CE, 20980, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_VBMR_TOP_127, 13915, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_VBMR_TOP_127_LOURD, 14683, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_VBMR_TOP_LG40, 18415, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_VBMR_TOP_LG40_LOURD, 19183, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_VBMR_L_CE_01, 14400, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_AMF_VAB_ULTIMA_TOP_X8_F, 11700, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(amf_pvp_01_top_CE_f, 7300, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(amf_pvp_01_mag_CE_f, 7120, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_PLFS_A, 6200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_PVP_WASP_CE_COMMANDEMENT, 7200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_PVP_FN_CE, 2520, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_PVP_WASP_CE, 7200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_PVP_WASP_EOD_CE, 7450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(amf_cougar, 9800, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_panther_FRA, 9500, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_TIGRE_01, 33835, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_gazelle_afte_f, 7400, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_gazelle_minigun_f, 9050, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_AMF_Heli_Transport_01_F, 12600, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_AMF_Heli_Transport_4RHFS_01_F, 13200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(amf_nh90_tth_cargo, 6200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(amf_nh90_tth_transport, 12200, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_TIGRE, 35505, "HELI", "(call A3U_fnc_sidesX count airportsX >= 1 || call A3U_fnc_sidesX count milbases >= 1) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(AMF_RAFALE_C_01_F, 91750, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(AMF_RAFALE_B_01_F, 92050, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(AMF_RAFALE_M_01_F, 91750, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_PLANE_FIGHTER_02_F, 48300, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_PLANE_TRANSPORT_01_F, 23400, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(AMF_WiredGuided_mmp_F, 6750, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(AMF_TVGuided_mmp_F, 6750, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(R3F_MMP_STATIC, 6750, "STATICAT", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(RHS_M2StaticMG_WD, 3600, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(R3F_FN_MAG58_fixe, 3240, "STATICMG", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(R3F_MO81_LLR, 8000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(B_AMF_AMX10_RCR_01_F, 35000, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_AMX10_RCR_SEPAR_01_F, 36280, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_TANK_01, 40800, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_TANK_CE_02_F, 43900, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(B_AMF_REAPER_dynamicLoadout_F, 20900, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(R3F_BLACKHORNET, 8000, "UAV", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(B_AMF_VAB_ULTIMA_X8_F, 1860, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(AMF_GBC180_PERS_01, 2550, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(AMF_GBC180_PLATEAU_01, 950, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(AMF_GBC180_ViV, 950, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(AMF_GBC180_AmmoTruck, 5200, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(R3F_VBMR, 3480, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(R3F_PVP_CE, 1050, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
