class vehicles_noraf : vehicles_base
{
    ITEM(Flex_CUP_NOR_M113A3, 6600, "APC", VEHICLE_CONDITION_APC);
    ITEM(Flex_CUP_NOR_Bell412_Transport, 9000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Utility, 8100, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Radar, 10600, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Merlin_HC3, 12200, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_MH60S_Unarmed, 11900, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Armed, 8990, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_Armed_AT, 14930, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Bell412_dynamicLoadout, 15315, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_MH60S_Armed, 13280, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_Merlin_HC3_Armed, 12805, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(Flex_CUP_NOR_F35B, 105725, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(F16C_NATO50, 91000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(Flex_CUP_NOR_Leopard2A6, 49000, "TANK", VEHICLE_CONDITION_TANK);
};
