class vehicles_racs : vehicles_base
{
    ITEM(PRACS_SLA_BTR40_AAM, 16200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_MTLB_ZU23, 8000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_MTLB_S60, 9000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_SA13, 17400, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_2S6M_Tunguska, 44800, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_SA9, 16200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Type63_ADA, 8000, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Ural_S60, 7200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Ural_ZPU4, 5200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_SA8, 49800, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_SA17, 55200, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M163_VADS, 17750, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M163_PIVADS, 18750, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M163_MACHBET, 31750, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M727_IHAWK, 23400, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M727_SEM_IHAWK, 25800, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_m48_chapparal, 33800, "AA", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_M577, 3800, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Type63_AT, 13140, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Type63, 5800, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_Type63_AGS, 10000, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_Pizarro, 22200, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_Pizarro_SLE, 33450, "APC", "(call A3U_fnc_sidesX count seaports >= 1 || call A3U_fnc_sidesX count resourcesX >= 3) && call A3U_fnc_sidesX count factories >= 3");
    ITEM(UK3CB_KDF_I_BTR40_MG, 5950, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_BTR40_AGS, 7800, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_BTR40_AT, 12450, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_HQ, 3100, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_M2, 9700, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_A3_M2, 12200, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_A3_Mk19, 16700, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_A3_M3_SFOD, 12050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_A3_GA1, 16700, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_ATGM, 41050, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_BMR_ATGM_TOW, 24175, "ARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_SLA_BTR40_mortar, 18040, "ARTILLERY", "call A3U_fnc_sidesX count resourcesX >= 3 && call A3U_fnc_sidesX count factories >= 3");
    ITEM(PRACS_P3C, 48400, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_Mohawk, 53925, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_AN12B, 21000, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_F16CJ, 96600, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_A4M, 62100, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_SLA_MiG27, 62375, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_SLA_SU22, 103375, "PLANE", "call A3U_fnc_sidesX count airportsX >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_M101, 10000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_M102, 10000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_M114, 13000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_M1, 15000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_M115, 18000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_M198, 15000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_SLA_M46, 13000, "STATICMORTAR", "tierWar >= 3 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_FV107, 26040, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_FV101, 22400, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_VEC_M242, 24440, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_VEC_MGS, 37200, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_M60A3, 42080, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_M60S, 47360, "TANK", "call A3U_fnc_sidesX count milbases >= 1 && call A3U_fnc_sidesX count factories >= 5");
    ITEM(PRACS_m548_open, 1640, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
    ITEM(PRACS_SLA_BTR40, 1320, "UNARMEDCAR", "call A3U_fnc_sidesX count resourcesX >= 1 && call A3U_fnc_sidesX count factories >= 1");
};
