class vehicles_optre : vehicles_base
{
    ITEM(OPTRE_M12R_AA, 12500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808B2, 19500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808B2A1, 34500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AA, 12500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AA_Needler, 13000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AA_Ultra, 13000, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_AA_Driverless, 12500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_SAM_Wraith_Needle, 28500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_AA_Wraith_Needle, 40500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_AA_Wraith_NOFLAK, 40500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_AA_Wraith, 41250, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12R_AA_ins_IND, 12500, "AA", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M413_MGS_UNSC, 24168, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M411_APC_UNSC, 5040, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M412_IFV_UNSC, 22668, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M313_UNSC, 9014, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M494_INS_IND, 33390, "APC", "([""seaports_1""] call A3U_fnc_hasRequirements || [""resources_3""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_LRV, 4100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12A1_LRV, 8600, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12G1_LRV, 15600, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AI, 8700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AI_Needler, 10700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AI_Ultra, 12700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AT, 13200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AT_Needler, 14200, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_AT_Ultra, 13700, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_Driverless, 8500, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_FuelRod_Driverless, 13000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_Zealot_Driverless, 10000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_Armor_Driverless, 9000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_Ultra_Driverless, 12500, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Ghost_Needler_Driverless, 8000, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_LRV_ins_IND, 4100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_TD_ins_IND, 11100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12A1_LRV_ins_IND, 8600, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_LRV_DME, 4100, "ARMEDCAR", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M875_SPH, 55800, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Corvette_archer_system, 309375, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_mlr_ins_IND, 69000, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M875_SPH_CMA, 55800, "ARTILLERY", "[""resources_3""] call A3U_fnc_hasRequirements && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_mg_f, 5150, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_aa_f, 9150, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_atgm_f, 9650, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_gauss_f, 12150, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_unarmed_f, 2250, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_ins_unarmed_f_IND, 2250, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(optre_catfish_ins_mg_f_IND, 5150, "BOAT", "[""seaports_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_hornet_CAP, 22650, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_hornet_CAS, 20850, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_AV22C_Sparrowhawk, 45360, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_AV22_Sparrowhawk, 46240, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_AV22B_Sparrowhawk, 49760, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_unarmed, 15, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_unarmed_SOCOM, 27, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed_SOCOM, 27, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed, 15, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed_single_seater, 40675, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed_70mm, 15, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed_70mm_single_seater, 42075, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_falcon, 14400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_falcon_S, 15400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_falcon_armed_S, 36750, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_UNSC_hornet_ins_IND, 22650, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_unarmed_ins_IND, 15, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Pelican_armed_ins_IND, 15, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_ins_falcon_IND, 33750, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_ins_falcon_unarmed_IND, 14400, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_DME_SOCOM_Pelican, 27, "HELI", "([""airports_1""] call A3U_fnc_hasRequirements || [""milbases_1""] call A3U_fnc_hasRequirements) && [""factories_3""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_EscapePod, 16900, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_YSS_1000_A, 84250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_YSS_1000_A_VTOL, 93250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_YSS_1000_A_Single, 81250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_YSS_1000_A_VTOL_Single, 90250, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spirit_Concussion, 39300, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spirit, 73300, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Type26B_Banshee, 70000, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Type26B_Ultra_Banshee, 74750, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Type26N_Banshee, 76150, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Type27_Banshee, 72000, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(vn_b_air_f4c_mr, 92300, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(vn_b_air_f100d_sead, 72500, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(vn_o_air_mig19_cap, 72700, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(vn_o_air_mig21_cap, 70100, "PLANE", "[""airports_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_LAU65D_pod, 7500, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Scythe, 40000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Scythe_AA, 40000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_AA, 7500, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Lance, 40000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T26_AA, 5000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T29B_NVar, 15000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Tyrant, 120000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_TyrantAA, 120000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T56_AAG, 16500, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T56_AA, 15000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_AA_Ins_IND, 7500, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Scythe_CMA, 40000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Lance_CMA, 40000, "STATICAA", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_ATGM, 6750, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_Gauss, 7500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Corvette_M910_Turret, 40000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Locust, 40000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T26_AT, 7500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_ATGM_Ins_IND, 6750, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_FG75_IND, 6000, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_Gauss_CMA, 7500, "STATICAT", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M247H_Tripod, 3600, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M247H_Shielded_Tripod, 3960, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M247T_Tripod, 3000, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M41, 4950, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_T26_AI, 4320, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M41_Ins_IND, 4950, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Static_M247T_Tripod_CMA, 3600, "STATICMG", "[""warlevel_3""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808B_UNSC, 43400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808BM_UNSC, 46700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808L, 48200, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808S, 47450, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M850_UNSC, 69800, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Wraith, 44000, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Wraith_Tank, 41200, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808B_INS_IND, 43400, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M808BM_CMA, 46700, "TANK", "[""milbases_1""] call A3U_fnc_hasRequirements && [""factories_5""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_FAV, 1000, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_FAV_APC, 1180, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_FAV_APC_MED, 6340, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M914_RV, 12100, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M813_TT, 1300, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M274_ATV, 600, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_cart, 700, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_unsc, 2260, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_cover_unsc, 2200, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_unsc_repair, 10100, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_unsc_medical, 7200, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_unsc_refuel, 5100, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1087_stallion_unsc_resupply, 7600, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Empty, 800, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Empty_Needler, 920, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Empty_Ultra, 1040, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Recovery, 800, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Recovery_Needler, 920, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Recovery_Ultra, 1040, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Transport, 1500, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Transport_Needler, 1620, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_FC_Spectre_Transport_Ultra, 1740, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_ins_IND, 2360, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_cover_ins_IND, 2300, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_ammo_ins_IND, 7700, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_fuel_ins_IND, 5200, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_medical_ins_IND, 7300, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_m1015_mule_repair_ins_IND, 10200, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_FAV_ins_IND, 1000, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_ins_APC_IND, 1180, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_ins_MED_IND, 6340, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M914_RV_ins_IND, 12100, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_DME_M12_FAV, 1000, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_CIV, 1000, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_Genet, 600, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M12_CIV2, 1120, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_forklift, 500, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
    ITEM(OPTRE_M813_TT_CMA, 1300, "UNARMEDCAR", "[""resources_1""] call A3U_fnc_hasRequirements && [""factories_1""] call A3U_fnc_hasRequirements");
};
