//western
["gm_dk_army_typ1200_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_typ253_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],

["gm_ge_army_iltis_milan", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_iltis_mg3", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_typ247_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_iltis_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_u1300l_medic", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_451_refuel", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_u1300l_repair", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_451_reammo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_454_reammo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_u1300l_container", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_454_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_451_container", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_452_container", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_u1300l_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_kat1_451_cargo", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_bpz2a0_noinsignia", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_Leopard1a3_noinsignia", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m113a2dk_noinsignia", ["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],

["gm_ge_army_fuchsa0_reconnaissance_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_fuchsa0_engineer_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_fuchsa0_command_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_marder1a2_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_marder1a1a_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_marder1a1plus_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_luchsa2_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_luchsa1_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_m113a1g_medic_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_m113a1g_command_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_m113a1g_apc_milan_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_m113a1g_apc_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_gepard1a1_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_bibera0_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_bpz2a0_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m109_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m113a1dk_engineer_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m113a1dk_command_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m113a1dk_apc_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_dk_army_m113a2dk_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_Leopard1a1_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_Leopard1a1a2_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_Leopard1a3a1_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],
["gm_ge_army_Leopard1a5_noinsignia",["gm_merdc_wht", 0.5,"gm_carc_tan",0.5]],


["gm_ge_army_bo105p1m_vbh_swooper_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2,"gm_ge_un",0.4]],
["gm_ge_army_bo105p1m_vbh_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2,"gm_ge_un",0.4]],
["gm_ge_army_bo105m_vbh_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2,"gm_ge_un",0.4]],
["gm_ge_army_bo105p_pah1_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2,"gm_ge_un",0.4]],
["gm_ge_army_bo105p_pah1a1_noinsignia", ["gm_ge_oli",0.8 ,"gm_ge_hornet",0.2,"gm_ge_un",0.4]],
["gm_ge_army_ch53gs_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_olo",0.2 ,"gm_ge_olu",0.2,"gm_ge_un",0.4]],
["gm_ge_army_ch53g_noinsignia",["gm_ge_oli",0.8 ,"gm_ge_olo",0.2 ,"gm_ge_olu",0.2,"gm_ge_un",0.4]],

["gm_ge_pol_w123", ["gm_darklblue",1]],
["gm_ge_pol_typ1200",["gm_saphireblue",1]],
["gm_gc_pol_p601", ["gm_kosmosblau",1]],
["gm_ge_pol_typ253",["gm_navyblue_damusowhite",1]],
//estern
["gm_gc_army_zsu234v1_noinsignia",["gm_merdc_wht",1]],

["gm_ge_army_k125",["gm_merdc_wht",1]],
["gm_dk_army_bibera0_noinsignia",["gm_merdc_wht",1]],

["gm_gc_army_brdm2_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_brdm2um_noinsignia",["gm_merdc_wht",1]],

["gm_gc_army_btr60pa_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_btr60pa_dshkm_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_btr60pu12_noinsignia",["gm_merdc_wht",1]],

["gm_gc_army_ural375d_mlrs_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_2s1_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_2p16_noinsignia",["gm_merdc_wht",1]],

["gm_gc_army_uaz469_cargo_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_uaz469_dshkm_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_uaz469_spg9_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural4320_reammo_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural375d_refuel_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural375d_medic_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural375d_cargo_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural4320_repair_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural44202_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_ural4320_cargo_noinsignia",["gm_merdc_wht",1]],

["gm_gc_army_pt76b_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_t55_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_t55a_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_t55ak_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_t55am2_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_t55am2b_noinsignia",["gm_merdc_wht",1]],
["gm_gc_army_bmp1sp2_noinsignia",["gm_gc_un",1]],


["gm_gc_airforce_mi2p_noinsignia",["gm_gc_un",1]],
["gm_gc_airforce_mi2t_noinsignia",["gm_gc_un",1]],
["gm_gc_airforce_mi2urn_noinsignia",["gm_gc_un",1]],
["gm_gc_airforce_mi2us_noinsignia",["gm_gc_un",1]],

["gm_gc_bgs_mi2p_noinsignia",["gm_gc_un",1]],
["gm_gc_bgs_mi2us_noinsignia",["gm_gc_un",1]],

["gm_pl_army_t55_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_t55a_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_t55ak_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_brdm2_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_bmp1sp2_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_ot64a_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_ural4320_reammo",["gm_merdc_wht",1]],
["gm_pl_army_ural375d_refuel",["gm_merdc_wht",1]],
["gm_pl_army_ural375d_medic",["gm_merdc_wht",1]],
["gm_pl_army_ural4320_repair",["gm_merdc_wht",1]],
["gm_pl_army_ural4320_cargo",["gm_merdc_wht",1]],
["gm_pl_army_uaz469_cargo",["gm_merdc_wht",1]],
["gm_pl_army_uaz469_dshkm",["gm_merdc_wht",1]],
["gm_pl_army_zsu234v1_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_2p16_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_2s1_noinsignia",["gm_merdc_wht",1]],
["gm_pl_army_ural375d_mlrs",["gm_merdc_wht",1]],
["gm_pl_airforce_mi2urs_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2urp_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2ch_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2p_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2platan_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2sr_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2t_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2urn_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2urpg_noinsignia",["gm_pl_un",1]],
["gm_pl_airforce_mi2us_noinsignia",["gm_pl_un",1]]