_unarmedVehicles append ["I_E_Pickup_rf","I_E_Pickup_Comms_rf","I_E_Pickup_Covered_rf"];
_armedVehicles pushBack "I_Pickup_mmg_rf";
_militiaLightArmed pushBack "I_Pickup_hmg_rf";
_militiaCars append ["I_E_Pickup_rf","I_E_Pickup_Comms_rf","I_E_Pickup_Covered_rf"];
_uavsPortable pushBack "O_UAV_RC40_SENSOR_RF";
_policeVehs append ["a3a_police_Pickup_rf", "B_GEN_Pickup_covered_rf", "a3a_police_Pickup_comms_rf"];
_helisLight pushBack "I_E_Heli_light_03_unarmed_RF";
_transportHelicopters append ["I_E_Heli_EC_01A_military_RF","B_Heli_EC_04_military_RF"];
_helisLightAttack append ["a3a_LDF_Heli_light_03_dynamicLoadout_RF","B_Heli_EC_03_RF"];
_helisAttack = ["a3a_LDF_Heli_EC_02_RF"];
_aa pushback "I_Pickup_aat_rf";